### ISSUE TITLE
Visual Alignment with new look and feel

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#100]
### Goal
This issue is to collect and track all the visual changes we need to make to the library to align with the new look and feel

### Visual reference
https://app.zeplin.io/project/5a5e1cb96e836180d25dfebd/screen/5a7d9f3c50ceaa7561911ad2

### General Visual changes
* #125 **Color palette**: The new look and feel is more "light" and neutral. 
* #126 ~**Spacing**: The overall spacing of the components need to be more compact~
* #127 ~**Fonts**: The font should be a default font -Arial, Helvetica- or 72~

### Individual Component changes
* #128 **Top and Side navigations**: align with the new style
* #142 **ActionBar**: Spacing, lighter fonts sizes, lighter colors
* **Alerts**: No change
* #143 **Buttons**: Rounded borders and smaller spacing and font-sizes
* #144 **Table**: Header style and colors, spacing and font sizes
* #144  **Tree**: see **Table**
* #161 **Sections**: Spacing and new background color
* #162 **Panel**: Visual style of the panel to look like the new modular cards
* #163 **Cards**: Rounded corners
* **Dropdown**: Rounded Corners in the main element
* **Forms & Input groups**: Rounded corners and more compact spacing
* **List**: ---
* **Modal**: Less spacing
* **Tabs**: Compact space
* **Toolbar**: to be decided

**Comment by xak** [comment]
@LeoT7508 Can you verify these are complete and close?
