### ISSUE TITLE
Bug: fd-button does not work on the anchor tag

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1029]
**Describe the bug**

`fd-button` does not work with an anchor tag - `<a class='fd-button' href="#">Button</a>`
<img width="137" alt="screen shot 2018-11-26 at 6 36 07 pm" src="https://user-images.githubusercontent.com/15215400/49050687-2b6b8080-f1aa-11e8-81dd-ebfbdeda7aa8.png">

We are also seeing problems with `input[type=button]` rendering.

There are some style tweaks that are needed to make `fd-button` compatible with an anchor tag. 

> Is this issue related to a specific component?

`fd-button` and  `input[type=button]`

> What version of the Fiori Fundamentals are you using?

latest 

**To Reproduce**
1. add `fd-button` to an a tag - `<a class='fd-button' href="#">Button</a>`

**Expected behavior**
it should look the same as the `<button>` tag 

See also #954 and #1070

**Comment by xak** [comment]
Set line-height to height of button.

**Comment by saad-mo** [comment]
duplicate
