### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by eurushibata** [SAP/fundamental#1040]
Name convention is to be Fiori 3 instead of Fiori 3.0 as written in this git repo.

**Comment by saadmhybris** [comment]
@eurushibata, thanks we'll use Fiori 3 moving forward.

**Comment by eurushibata** [comment]
looks like it is still incorrect on the git repo description.

![image](https://user-images.githubusercontent.com/1073093/56889439-40f11900-6a6e-11e9-9dbe-54de0a0bb096.png)
