### ISSUE TITLE
[Image] Need shellbar component image

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1055]
Need a `shellbar` component image for the index page.
https://sap.github.io/fundamental/components/index.html

![screen shot 2018-12-02 at 9 08 04 pm](https://user-images.githubusercontent.com/424119/49350877-6e2fcb80-f676-11e8-96b7-fb2344c07f08.png)

**Comment by xak** [comment]
@LeoT7508 Can you prioritize this so we can release the shellbar docs?

**Comment by LeoT7508** [comment]
@saadmhybris 

![shell](https://user-images.githubusercontent.com/28761982/49462486-c7edde00-f7bb-11e8-93e3-def4003c8c15.png)
