### ISSUE TITLE
[Bug] Toggle styling issue 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1067]
**Describe the bug**
Toggle slider is peaking through. 

>happens only in :focus state 

<img width="322" alt="screen shot 2018-12-02 at 9 32 34 pm" src="https://user-images.githubusercontent.com/15215400/49461353-1188f980-f7b9-11e8-91c5-d6945f4c304f.png">

> Is this issue related to a specific component?
toggle 

**To Reproduce**
1. Go to https://sap.github.io/fundamental/components/toggle.html
2. Click on toggle 
3. observe the behavior in :focus state 

**Expected behavior**
slider should should not be visible

**Comment by xak** [comment]
#1044 is also a toggle bug

**Comment by ckoutsiaris** [comment]
This can be addressed with this https://github.com/SAP/fundamental/issues/1044#issuecomment-444508503
