### ISSUE TITLE
Website: Update copy on Type card

### ISSUE THREAD

**Issue by mobot11** [SAP/fundamental#1085]
The copy for the `type` and `grid` sections on https://sap.github.io/fundamental/ have the same copy. It looks like the copy for `type` needs to be updated.
<img width="625" alt="fiori-fundamentals" src="https://user-images.githubusercontent.com/9958488/49629254-79983500-f99d-11e8-9dda-ea8542ac0430.png">

**Comment by xak** [comment]
Good catch ... this is the copy.

> Fundamental UI uses a set of sans-serif system fonts. They are timeless fonts ensures that the fresh, clean, and minimalist style. It works well across all browsers, devices, and platforms for customization to be easy.

**Comment by eboyer** [comment]
This was addressed in https://github.com/SAP/fundamental/issues/1085
