### ISSUE TITLE
Lib: Update theme to use new name

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#11]
Change from `techne` to `fundamental`

**Comment by joseegm** [comment]
@xak 
This is in the filename, the folder, where it is?

**Comment by saadmhybris** [comment]
most likely in the scss. Neihi was working on this as a trial ticket, though she is not added to the project yet.

**Comment by xak** [comment]
The theme is still called `techne`. I didn't change it since it's not that relevant and you could argue that the look and feel is Techne. We may want to retain the old settings for the old theme but at the end of the day, it's not a big deal to make everything `fundamental`. 

Whatever you think is best. The file needs to be renamed and the `@import` in `all.scss` changed. That's it.
