### ISSUE TITLE
Compiled pagination css/minified css contains bad icon import

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental#110]
Found this issue while trying to import individual components.  

https://github.com/SAP/fundamental/blob/master/dist/components/pagination.css#L226

This line contains imports src: url(components/FundamentalIcons.woff2) format("woff2"),url(components/FundamentalIcons.woff) format("woff");

The FundamentalIcons.woff/woff2 files are at the root of the dist/ directory, not components.  This block of code is not in the pagination SCSS so I'm not sure how it ended up in the CSS.  This prevents the angular-cli from compiling

**Comment by xak** [comment]
@mikerodonnell89 This should have been fixed. @saadmhybris, it looks like the compiled `pagination.css` does not match the `scss` version. Is it possible the build tasks were not run properly before the last release.

**Comment by saadmhybris** [comment]
This was automatically fixed during the release of beta 3. all the CSS generation worked as expected. pagination refactoring might not have merged properly as that is the only explanation.
