### ISSUE TITLE
Docs: Make Documentation site responsive. 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1104]
The goal of this task to make the documentation responsive so that it holds up when the browser window is resized. We don't necessarily need to make it compatible with mobile screens. The use case here is when developers are working with the documentation site, they may be splitting screen with code editor or any other programs that they may have open. 

Example Sites: 
- https://www.carbondesignsystem.com/
- https://material.angular.io/components/categories
- https://devportal.yaas.io/gettingstarted/

Requirements: 
- [ ] Left nav should collapse into hamburger menu 
- [ ] main content area should take up 100% width of the window 
- [ ] The responsive behavior should not have any dependency on bootstrap

> Bootstrap will be removed as a depenency from the documentation site soon.

**Comment by ckoutsiaris** [comment]
@saad-mo Can we close this? Are you ok with the changes?
