### ISSUE TITLE
https://sap.github.io/fundamental is not responsive

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental#111]
I doesn't work well in small resolution
<img width="421" alt="screen shot 2018-03-12 at 9 33 05 am" src="https://user-images.githubusercontent.com/4380815/37286475-700ea292-25d8-11e8-85a6-8ea0f6bf6c4d.png">
<img width="416" alt="screen shot 2018-03-12 at 9 33 20 am" src="https://user-images.githubusercontent.com/4380815/37286476-70213038-25d8-11e8-9e6b-a240b6c70d85.png">

I attached 2 screenshots how the website looks on iphone 7 and iphone 8

**Comment by joseegm** [comment]
@saadmhybris 
We had a ticket for this, right?

**Comment by ivijan** [comment]
Hello!
As I was testing FUI, and had issues with smaller resolutions, I came up with solution for my project, so I could also propose same fix here, for better responsive behaviour of app layout with sidebar navigation.

Normal sidebar: 
![screen shot 2018-07-16 at 14 27 05](https://user-images.githubusercontent.com/13087038/42758820-101de72c-8905-11e8-825a-4028bf2d76c7.png)

Smaller resolution with broken sidebar:
![screen shot 2018-07-16 at 14 26 50](https://user-images.githubusercontent.com/13087038/42758825-13e1434a-8905-11e8-831d-3a313f0f0364.png)

Smaller resolution with slim sidebar (proposal):
![screen shot 2018-07-16 at 14 31 23](https://user-images.githubusercontent.com/13087038/42758827-172bf95a-8905-11e8-9beb-ddb358d632db.png)

SCSS fix code:

`
.fd-app {
  display: flex;
}

.fd-ui__app,
.fd-app {
  height: calc(100vh - 50px);
  min-height: calc(100vh - 50px);
}

.fd-app__sidebar {
  overflow-x: hidden;
  overflow-y: auto;
  max-height: 100%;
}

@media (max-width: 799px) {
  .fd-app__sidebar {
    width: 60px;
  }
  .fd-side-nav__icon {
    padding-right: 30px;
  }
}
`

**Comment by saad-mo** [comment]
We have improved responsive support documentation site.
