### ISSUE TITLE
fundamental modal is not responsive

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#112]
the modal looks odd on small resolutions:
![img_9728 2](https://user-images.githubusercontent.com/4380815/37286318-f63f9340-25d7-11e8-996f-7dfe6d0c8705.PNG)
![img_9729](https://user-images.githubusercontent.com/4380815/37286346-0a6e47d0-25d8-11e8-8972-1591a4e6dcc9.PNG)

it could be a result of the website

It would be great to have a design for small resolutions. In the current one the header and the footer looks quite big and it doesn't give much space for the body without scrolling

**Comment by saadmhybris** [comment]
width was changed to max-width to allow for some responsive behavior. 

for spacing issue, it will have to go through design first, so please open a new ticket.

**Comment by SAPMontreal** [comment]
@saadmhybris, really?

**Comment by saadmhybris** [comment]
@SAPMontreal modal was built per design specs - https://zpl.io/blBJ95V 

So we cannot make any modification unless there is some direction form UX and design.

**Comment by SAPMontreal** [comment]
tagging @LeoT7508 for feedback.
Who is the UX?

**Comment by saadmhybris** [comment]
@jeannewalters and @joseegm for UX

**Comment by jeannewalters** [comment]
@saadmhybris - Jose was the UX for this component and I'm not sure the reasoning for creating the modal at 700 pixels. From my perspective, we should definitely support down to mobile with all components over a default mobile pixel width (looks like Techne supported a screen size down to 400 pixles).  For Techne modals, the default size looks like it was 600 pixels and goes down to 380 pixels.  I would suggest we do the same.  https://techne.yaas.io/patterns/Dialogues-Modals.html

**Comment by joseegm** [comment]
This first fix resolve the problem of the modal taking more space than the actual screen on modal.

The spacing of the modal will be reworked as part of the visual alignment on #100 

@SAPMontreal 
There is something else for now? Otherwise we can close this one.
