### ISSUE TITLE
Menu with icons - icon controls are not aligned with text when each item displays icon

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental#1137]
Working on this enhancement: https://github.com/SAP/fundamental-ngx/issues/374
When each menu item has an icon, the icons are sized differently from the text, causing the icons to be misaligned to the corresponding text.

> Is this issue related to a specific component?

Menu

> What version of the Fiori Fundamentals are you using?

1.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

fundamental-ngx

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular (however I could reproduce this issue with fiori-fundamentals)

**To Reproduce**
Add an icon to every menu item for a menu with icons

**Screenshots**
<img width="469" alt="screen shot 2018-12-31 at 4 06 37 pm" src="https://user-images.githubusercontent.com/2471874/50568893-b9410b00-0d16-11e9-83e1-397679b3673a.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome

**Comment by droshev** [comment]
this is blocking the release of shell-bar for angular, react, and vue

**Comment by droshev** [comment]
@saadmhybris we are able to release the shell-bar for angular, react, and vue so it is a *blocker* for all the libraries. Do you think you can fix is fast?
