### ISSUE TITLE
Component: select

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#115]
Fundamental is missing a design/styling for a select component that behaves as a classical dropdown:
https://en.wikipedia.org/wiki/Drop-down_list
The current design is more like menu options. On the other side the bootstrap dropdown is similar to what fundamental has.

**Comment by xak** [comment]
@SAPMontreal The regular `select` element is styled to look the same.

<img width="377" alt="screen shot 2018-03-12 at 10 54 47 am" src="https://user-images.githubusercontent.com/424119/37294494-e57cfdca-25e3-11e8-8f0b-eaa571d14edf.png">

**Comment by SAPMontreal** [comment]
then I would be great having it in the documentation page for the dropdown, no?

**Comment by SAPMontreal** [comment]
But It doesn't look like:
<img width="150" alt="screen shot 2018-03-12 at 12 52 29 pm" src="https://user-images.githubusercontent.com/4380815/37297528-485e3912-25f4-11e8-9fe0-e8469c67a5eb.png">

**Comment by xak** [comment]
Browsers do not allow for styling of native `option` elements. We cannot style the "dropdown" part without scripting support.

**Comment by joseegm** [comment]
This one's name is Dropdown, is a different component and a base for more complex components like search-ahead, or a date picker. It is fine to use the simple select for simple cases. 

So, simple select for simple cases, Dropdown for more complex scenarios. Note the difference in names.

That will answer the style inconsistency question.
