### ISSUE TITLE
[Test] Expand Visual regression testing

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1150]
We have already proven Backstop to be a good solution to perform VRT. It's not time to expand it to more components and possibly incorporate into the build process. 

Todo: 
- [x] Move `backstop_data` under `test/visual-regression-testing` folder so that we can keep the project root clutter free and organized 
- [ ] Expand test cases to cover all components if possible 
- [x] Integrate into test framework. For example, `npm test --vrt` can to start the test site and perfrom VRT as the same time as well.
- [x] Add README.md to `test/visual-regression-testing` that expains how VRT works and how to use it.

**Comment by xak** [comment]
See #1169. We can break the components down into logical groups to expand the coverage.

**Comment by ianquigley-sap** [comment]
Unfortunately It looks like the travisCI build sometimes hangs and fails to return any visual elements for testing.  Needs a little more investigation - perhaps using Puppeteer or another headless browser might be more stable.
