### ISSUE TITLE
actions card - item on hover issue

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#116]
The text and background don't make the text readable
![screen shot 2018-03-13 at 9 11 08 am](https://user-images.githubusercontent.com/4380815/37344380-9a1cff52-26a0-11e8-804e-c581d15f4593.png)

**Comment by joseegm** [comment]
@saadmhybris 
This is some css statement from the website bleeding to the component, it doesn't happen on the sample app.

**Comment by joseegm** [comment]
This is still broken

On the website
![screen shot 2018-03-19 at 11 42 10](https://user-images.githubusercontent.com/22662903/37591086-a4596630-2b6a-11e8-8dab-aaf4bed80fca.png)

On the sample app now as well
![screen shot 2018-03-19 at 11 41 14](https://user-images.githubusercontent.com/22662903/37591100-adb23752-2b6a-11e8-8877-4af6768faf2f.png)
