### ISSUE TITLE
Test: Implement visual testing for link elements

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1169]
We want to expand coverage for the visual testing. See #1150 

- [ ] `button-group` http://localhost:3030/button-group | https://sap.github.io/fundamental/components/button.html#button-group
- [ ] `link` http://localhost:3030/link
- [ ] `tabs` http://localhost:3030/tabs

Add scenarios to `test/visual-regression-tests/backstop.json`

**Comment by saad-mo** [comment]
current VRT covers this case
