### ISSUE TITLE
default size value in different components is not consistent

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#117]
Examples:
- Icon's default size is the small
- button's default size is the medium

It would make it logical, predictable and easier if we stick to one of the sizes as default

**Comment by joseegm** [comment]
Where exactly is this found? 
Icons and buttons can be used together or separated. Most of the icons usage is small that's why it is default. Also the spacing and sizes are standard

**Comment by xak** [comment]
This is no longer relevant with the `button` refactor. It is no longer necessary to specify the size of the icon.
