### ISSUE TITLE
Test: Implement visual testing for nav elements

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1175]
We want to expand coverage for the visual testing. See #1150 

- [ ] `breadcrumb`
- [ ] `menu`
- [ ] `nav`
- [ ] `dropdown`
- [ ] `popover`
- [ ] `pagination`

Add scenarios to `test/visual-regression-tests/backstop.json`

**Comment by saad-mo** [comment]
current VRT setup covers this case.
