### ISSUE TITLE
Website Improvement: Getting Started Page

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#1193]
Work on content to add more information and meaning to this page. Something like what we have in the Sketch file with steps to get Devs started.

**Comment by JordanTranchina** [comment]
Hi @LeoT7508 anything I can do to help here?

**Comment by LeoT7508** [comment]
@JordanTranchina 

Thanks for the help, but I think at this point Jeanne our UX lead has already done the work for the website, I just need to align and design out the page.
