### ISSUE TITLE
UI Kit downloads not working

### ISSUE THREAD

**Issue by ianquigley-sap** [SAP/fundamental#1200]
**Describe the bug**

The latest version of the documentation contains UI Kit downloads, including the sketch files.  This link works locally, but not when deployed to Github Pages.

> Is this issue related to a specific component?

No.

> What version of the Fiori Fundamentals are you using?

1.4.1

**To Reproduce**
1. Go to https://sap.github.io/fundamental/resources/ui-kit.html
2. Click on the link to download the sketch file or font or icons.
3. A 404 error is returned.

**Expected behavior**
The download link should work.

**Comment by saad-mo** [comment]
this issue is fixed now.
