### ISSUE TITLE
Modal component: inconsistency with fundamental-ngx library

### ISSUE THREAD

**Issue by jesusreal** [SAP/fundamental#1205]
**Is your feature request related to a problem? Please describe.**
Currently the support for backdrop in modal component is the usage of css _overlay_ classes, as proposed here: https://sap.github.io/fundamental/demo-pages/modal-overlay-demo-page.html. Which arguably is not a proper implementation of a backdrop modal.

[ngx fundamental](https://github.com/SAP/fundamental-ngx) is not using those css classes. Instead, there are other css classes specifically added with their own css styles. As a consequence, modal backdrop looks different depending on if I use fundamental or fundamental-ngx.

IMHO this inconsistency should be avoided. Otherwise each other fundamental library specific to a JS framework (fundamental-ngx, fundamental-react, fundamental-vue, etc...) will offer an inconsistent visualisation of components. 

Fundamental should be the single source of truth regarding styles, any fundamental-XXX library built on top of it should not implement its own styles, just use the existing css selectors provided by fundamental. Any styling I can apply through any fundamental-XXX library, should be possible to be applied with plain fundamental. 

> Is this issue related to a specific component?
Modal component

> What browser are you working in?
Chrome latest

> What version of the Fiori Fundamentals are you using?
1.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Kyma

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular and Svelte

**Describe the solution you'd like**
I would like a proper and consistent implementation of modal backdrop, regardless of using fundamental or any fundamental-XXX library.

**Comment by xak** [comment]
> Which arguably is not a proper implementation of a backdrop modal.

Do you have a recommendation as to the proper implementation?

**Comment by jesusreal** [comment]
Hi @xak, thanks for your answer. My recommendation would be to implement the html of the modal component as in here (where possible): https://sap.github.io/fundamental/demo-pages/modal-overlay-demo-page.html. 
Looking at the already referenced issue, it seems you already figured the same out.

**Comment by jesusreal** [comment]
Issue is solved, thanks for the great work!
