### ISSUE TITLE
Lib: Implement top navigation component

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1208]
# HOLD - WIP

### Component name
> Propose a new or variant name

`fd-top-navigation`
`fd-top-navbar`

### Detailed description
> Describe the request

A top navigation bar should be available to hold 3rd and 4th level navigation. It will be placed directly below the shellbar. Each nav item should support a child menu.

![top nav - responsive](https://user-images.githubusercontent.com/424119/51568764-80eda200-1e68-11e9-97c2-201438c75df9.png)

### Use case
> Describe when to use (and when not to use)

The top nav bar is most applicable for applications that have a limited number of nav items or those that need a maximum amount of screen space.

### Visual style
> Describe specific needs related to color, typography, iconography, borders, space, size, and other visual properties.

Use action color and action states to indicate selected items.

> Describe how to arrange multiple instances and other alignment specifics.

May only use one instance per page.

> How should this respond to common contexts, i.e., touch, RTL, small screens.

Must support RTL. The component will vary between small and medium screens (described below).

> Describe interactive states, e.g., disabled, expanded, pressed.

Active and selected nav items will be marked with either bottom or side border.

![nav item states](https://user-images.githubusercontent.com/424119/51568931-efcafb00-1e68-11e9-8f84-98549c34b3d0.png)
![overflow menu states](https://user-images.githubusercontent.com/424119/51568934-f22d5500-1e68-11e9-9a1b-0a3bd8a42b63.png)

### Expected behavior
> How should this handle events, outcomes, and transitions

#### Small screen
- The user shall see the selected nav item. 
- Clicking the nav bar will open a menu with the top-level nav items, the selected nav item should be included in the menu and marked as selected. 
- Nav items with children will show a down arrow and expand the onclick. 
- If the selected item is a child element, the menu should be expanded.

![small-selected flow](https://user-images.githubusercontent.com/424119/51568656-3cfa9d00-1e68-11e9-8470-7b158390d05b.png)

#### Medium and above
- The user shall see the max number of items that can be displayed based on the screen width, the selected item should be marked. 
- Nav items with children will show a down arrow and open a menu onclick. 
- Overflow nav items shall be available under menu labelled "More", open the menu onclick.
- If the selected item is a child element, the parent item and selected item should be will be marked. If the selected item 
- If the selected item is in the overflow menu, the "More" item shall be marked as well as the item.

![desktop-selected flow](https://user-images.githubusercontent.com/424119/51568662-41bf5100-1e68-11e9-83fc-b581dde59014.png)

## Additional information

There may be constituent components required to fully realize this component. For example, `nav` could be expanded to handle an addt'l level of navigation.

**Comment by JKMarkowski** [comment]
Hi, just FYI, I started to work on this component.
