### ISSUE TITLE
Docs: Alert Colors on Lib and in Github

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#1211]
The alerts colors on the lib site do not match the https://github.com/SAP/fundamental/wiki/Component-Versions-and-Status.

After looking at other libraries, I also had some suggested updates:

1) Consider changing Experimental to Beta
2) Show checkmarks rather than hearts for New Release, Ready, Beta
3) Show ! for In Process
4) Show X for Deprecated

5) Update descriptions on https://github.com/SAP/fundamental/wiki/Component-Versions-and-Status to the following:

New Release - Newly released and ready to use. Could change slightly.
Ready - Available and ready to use.
Beta - A work in progress. Available to use but will most likely change.
In Process - Being refactored. Contact us before using/use with caution. 
Deprecated - **Do Not Use**. It will be removed soon.

**Comment by droshev** [comment]
@jeannewalters i think this is outdated?

**Comment by jeannewalters** [comment]
Outdated
