### ISSUE TITLE
Currently released SCSS invalid

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#1212]
I tried to integrate the currently released SCSS into our existing project and I noticed that the scss of 1.4.1 is invalid.

https://github.com/SAP/fundamental/blob/v1.4.1/scss/core/root.scss#L31

I am getting the following error:

```
essage:
    node_modules/fiori-fundamentals/scss/core/root.scss
Error: Invalid CSS after "...ackground-color": expected "}", was ")};"
        on line 31 of node_modules/fiori-fundamentals/scss/core/root.scss
>>   --fd-forms-background-color: #{$fd-forms-background-color)};
   ---------------------------------^

Details:
    status: 1
    file: xxx/node_modules/fiori-fundamentals/scss/core/root.scss
    line: 31
    column: 34
    formatted: Error: Invalid CSS after "...ackground-color": expected "}", was ")};"
        on line 31 of node_modules/fiori-fundamentals/scss/core/root.scss
>>   --fd-forms-background-color: #{$fd-forms-background-color)};
   ---------------------------------^

    messageFormatted: node_modules/fiori-fundamentals/scss/core/root.scss
Error: Invalid CSS after "...ackground-color": expected "}", was ")};"
        on line 31 of node_modules/fiori-fundamentals/scss/core/root.scss
>>   --fd-forms-background-color: #{$fd-forms-background-color)};
   ---------------------------------^

    messageOriginal: Invalid CSS after "...ackground-color": expected "}", was ")};"
    relativePath: node_modules/fiori-fundamentals/scss/core/root.scss
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

I tried different scss-compiler and all reported an issue with the line linked above.

**Comment by xak** [comment]
Interesting mistake. This has been fixed already in `develop` and will go out with the next release. https://github.com/SAP/fundamental/blob/develop/scss/core/root.scss#L37

In my testing it seems to compile OK despite the error. Is this stopping compilation in your project?

**Comment by ChristianKienle** [comment]
Yes. It is not working - I get the error shown in my first post.

Our integration is a bit special since we are not including the core/elements and core/forms styles because they contain global styles that we cannot use in he beginning.

Maybe it has also something to do with this partial integration.

This is currently making our integration efforts complicated because I have to work around it until this has been fixed with a new release or some workaround... maybe it is also a level 7 error. 🙈

**Comment by ChristianKienle** [comment]
And i tried different scss Compiler and included just the line in question. There are several REPL-like scss compilers available online. I found 2 via google and both failed.

**Comment by ChristianKienle** [comment]
This is how I import it:

```
// Fundamental Import
$fd-icons-path : "./../node_modules/fiori-fundamentals/scss/icons/";
$fd-scss-font-path : "./../node_modules/fiori-fundamentals/scss/fonts/";

// We are not simply importing all.scss because this may override styles for well known
// elements like button, a, body. Instead we only import everything that is scoped.
@import "./../node_modules/fiori-fundamentals/scss/settings";
@import "./../node_modules/fiori-fundamentals/scss/fonts";
@import "./../node_modules/fiori-fundamentals/scss/icons";
@import "./../node_modules/fiori-fundamentals/scss/core/root.scss";
@import "./../node_modules/fiori-fundamentals/scss/layout";
@import "./../node_modules/fiori-fundamentals/scss/components";
@import "./../node_modules/fiori-fundamentals/scss/helpers";
```

**Comment by ChristianKienle** [comment]
Using a newer scss compiler solved this issue for us.
