### ISSUE TITLE
[BUG] Information alert background is transparent

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental#1214]
Fiori Fundamentals v1.4.1, the information alert background is transparent

**Screenshots**
<img width="605" alt="screen shot 2019-01-25 at 4 49 48 pm" src="https://user-images.githubusercontent.com/2471874/51778943-a45f5980-20c1-11e9-8b0a-21bb8cdd4ceb.png">

**Desktop (please complete the following information):**
OSX Mojave, Chrome 70

**Comment by saad-mo** [comment]
@xak  we are `adjust-color` function to render these state colors which results in rgba values. To avoid this problem, we need to hardcode these state values in hex. As I have not found any other method that will return a color without transparency. Modifying HSL values has not returned the right color as well. Open to any other suggestions you may have on this.
