### ISSUE TITLE
Align Color Palette 

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#125]
### Tasks
Modify the current color palette to match the new visual style

### Current palette
https://sap.github.io/fundamental/fundamentals/colors.html

### Reference visual Styles
https://app.zeplin.io/project/5aa6865cca18fbef58c65700/screen/5aa6e033eb62280b8f68eb4e

## Visuals
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb

**Comment by LeoT7508** [comment]
@joseegm 

The color palette is here:

https://zpl.io/VDDmK4e

The rest of the Design System Basic Elements are also finished.
