### ISSUE TITLE
Bug: Buttons in Action Bar squished (IE11)

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#1258]
The screenshot below demonstrates the issue. As you can see, the buttons on the right are squished. This is the normal action bar without any modifications. Depending on the width of the view port, the squishiness becomes more or less apparent.

![actionbar](https://user-images.githubusercontent.com/153225/52413128-fbf9be00-2ae0-11e9-9173-ce7145910066.png)

**What I did:**

I have built an IE compatible version of Fundamental as described by #1149.
I also checked out this repository and built and used the IE CSS artefact myself in order to exclude an incorrectly configured SCSS processing on my end.

Then I used Fundamental Vue as to generate the HTML and compared what I see with what to expect.

**Comment by ChristianKienle** [comment]
Fiddle using the latest Fundamentals:
https://jsfiddle.net/christiankienle/xsy071qu/8/embedded/result,css,html,js

**Comment by saad-mo** [comment]
@ChristianKienle this issue should be fixed now. We added some more clean up to ie11.scss with postcss and the buttons render correctly. 

this is the screen shot from you [jsfiddle](https://jsfiddle.net/christiankienle/xsy071qu/8/embedded/result,css,html,js)
<img width="861" alt="Screen Shot 2019-05-13 at 12 13 18 PM" src="https://user-images.githubusercontent.com/15215400/57640601-9b16d180-7578-11e9-9965-390393b50ad2.png">

**Comment by saad-mo** [comment]
still is still an issue
