### ISSUE TITLE
Bug: Warning Alert has incorrect Background Color (IE11)

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#1259]
I think the background color is the same as the border color which makes it look incorrectly.

![alert](https://user-images.githubusercontent.com/153225/52415317-f606db80-2ae6-11e9-8559-a4e2aa534ac3.png)

**What I did:**

I have built an IE compatible version of Fundamental as described by #1149.
I also checked out this repository and built and used the IE CSS artefact myself in order to exclude an incorrectly configured SCSS processing on my end.

Then I used Fundamental Vue as to generate the HTML and compared what I see with what to expect.

**Comment by i5un** [comment]
Here's the issue. Online line 111, ```@include fd-var-color("background-color", $fd-alert-border-color--warning);``` applies the border colour as the background. 

Adding this line to the base class fixes the issue for now. ```background-color: var(--fd-alert-background-color);```


<img width="716" alt="Screen Shot 2019-03-30 at 12 17 55 PM" src="https://user-images.githubusercontent.com/35351414/55278785-1719ca80-52e7-11e9-9fbe-e57041fa7fe4.png">
