### ISSUE TITLE
Bug: Panel Grid Fallback not working (IE11)

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#1268]
The following fiddle contains the default panel grid (which can also be found in your documentation):

https://jsfiddle.net/christiankienle/deftr5py/1/embedded/result,css,html,js

I expected three columns but got 4-5.

The documentation says:

> This [Panel Grid] uses CSS grid which is not supported by some older browsers. A flexbox fallback is included but it is recommended you test your page if you have a significant number of users on IE 11, for example.

So me it seems that the fallback is not working.

![panel-grid](https://user-images.githubusercontent.com/153225/52566277-a50a2680-2e09-11e9-8f03-44d86ea1e98c.png)

**Comment by saad-mo** [comment]
@ChristianKienle can you please verify if this is still an issue? the jsfiddle link you shared seems to render the columns correctly.

![screen shot 2019-02-27 at 3 25 12 pm](https://user-images.githubusercontent.com/15215400/53524028-0259d500-3aa4-11e9-95c8-aafb261fda3a.png)

**Comment by ChristianKienle** [comment]
I have opened the Fiddle linked above on IE 11. Still an issue.

<img width="1267" alt="screenshot 2019-03-02 at 16 09 46" src="https://user-images.githubusercontent.com/153225/53683821-a7271d00-3d05-11e9-9747-b2aa4edbb3e3.png">

This is also broken in the official documentation as you can see below:

<img width="1230" alt="screenshot 2019-03-02 at 16 10 59" src="https://user-images.githubusercontent.com/153225/53683829-d9387f00-3d05-11e9-8579-5c6d6accac56.png">

I am using a standard WTS instance and thus I have no control over the actual "setup" when it comes to the OS (…).

**Comment by saad-mo** [comment]
@ChristianKienle is this on IE11?

**Comment by ChristianKienle** [comment]
@saad-mo yes. I think I mentioned that in the title of this issue. :)
