### ISSUE TITLE
Bug: Focus ring misalignment.

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental#1271]
> Is this issue related to a specific component?
Alert dismiss focus ring is not aligned. There may be others

> What version of the Fiori Fundamentals are you using?
1.4.2

**To Reproduce**
go to 
https://sap.github.io/fundamental/components/alert.html

focus on one of the alerts, and then use tab to gain focus on the close button.

**Expected behavior**
focus ring neatly aligns. 

**Screenshots**
alert
![image](https://user-images.githubusercontent.com/5056972/52739048-ec68f200-2f84-11e9-9009-c936b271561c.png)

This was done properly in SAP Concurs  pre-fundamental component library. See

![image](https://user-images.githubusercontent.com/5056972/52739228-4c5f9880-2f85-11e9-8af2-1b00ad86c6f7.png)

**Comment by girraj-ch** [comment]
Used this CSS for alert issues 
```
.fd-alert__close {
    right: 0px;
}
```

**Comment by bcullman** [comment]
@saad-mo - I see this is on the IE Improvement milestone. 

Just an fyi, but this is not specific to IE
