### ISSUE TITLE
CSS header version # is incorrect

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#1272]
**Describe the bug**

The version number in the dist files header is incorrect.

https://github.com/SAP/fundamental/blob/develop/dist/components.css#L2

This can be useful for troubleshooting.

<img width="751" alt="screen shot 2019-02-14 at 12 00 50 pm" src="https://user-images.githubusercontent.com/424119/52782803-35d24380-3050-11e9-8bd4-bb05294762b1.png">

**Comment by girraj-tm** [comment]
yes incorrect the version number

**Comment by saad-mo** [comment]
@eboyer can we correct this asap and get a patch release out. we need to bump it up again to `v1.4.3`

**Comment by eboyer** [comment]
@saad-mo yep! on it.

**Comment by eboyer** [comment]
Fixed in 1.4.3 release: https://github.com/SAP/fundamental/releases/tag/v1.4.3
