### ISSUE TITLE
Lib: Button nomenclature

### ISSUE THREAD

**Issue by bcullman** [SAP/fundamental#1278]
Is this issue related to a specific component?
* https://sap.github.io/fundamental/components/button.html

What version of the Fiori Fundamentals are you using?
* 1.4.2

> There are only 2 hard things in computer science
> Cache invalidation
> Naming things
> off-by-one errors.

# The use of "Type"
Under buttons, there is a section called `Types`. We should consider renaming this, because `type` is a valid attribute for <button> (`submit`, `button`, and `reset`)

It appears that the buttons "Types" correspond roughly to the contextual variations  seen for alerts. this might be good opportunity to unify naming convention around contextual variations

bootstrap unify naming convention around contextual variations  as well:
https://getbootstrap.com/docs/4.3/components/buttons/
https://getbootstrap.com/docs/4.3/components/alerts/
https://getbootstrap.com/docs/4.3/components/badge/#contextual-variations

# Medium Type
The word `medium` is generally used to describe a size in between large and small. Consider `neutral`

**Comment by droshev** [comment]
We had done the same issue in fundamental-ngx and we started using `fdType` just to avoid overlapping with the html button attribute.
