### ISSUE TITLE
Align Top and side navigation Visual style

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#128]
### Goal
Align the present top and side navigation to the new Visual Style

### Current
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/5a940e0faa10e027813e7ecb

### Visual style reference
https://app.zeplin.io/project/5aa6865cca18fbef58c65700/screen/5aa6e0354e98054d04a45de4

### Tasks
- [ ] Top Navigation
- [ ] Side Navigation

**Comment by saadmhybris** [comment]
moving this ticket back to design board. we need to keep the tickets seperate. 

opened two separate tickets for the top nav (#148  and side nav (#149)

**Comment by LeoT7508** [comment]
@joseegm @saadmhybris @xak 

The first version of the Global & Side nav are posted here:

https://zpl.io/VkrL9Rg

https://zpl.io/bW157on

**Comment by saadmhybris** [comment]
@LeoT7508 i need the following icons for this - 

<img width="1089" alt="screen shot 2018-03-28 at 12 49 37 pm" src="https://user-images.githubusercontent.com/15215400/38046995-b2fd99cc-3286-11e8-8af6-fde99c6ee901.png">


1 hamburger 
2 sap hybris [y] logo 
3 home icon 
4 chat icon 
5 person icon 

I am assuming the search, gear and more icons are the same as we have now.

**Comment by joseegm** [comment]
@saadmhybris 
For the logo you can use text, but make sure that it support an image as well.
