### ISSUE TITLE
Bug: Inputs without a type are not styled

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#1280]
If you have an `input`-element without a `type`-attribute you will notice that it does not receive the proper fundamental styles.

[Fiddle to reproduce the issue](https://jsfiddle.net/christiankienle/kLyzcr2h/1/)

The [value `text` for the `type`-attribute is the default](https://www.w3.org/TR/html52/sec-forms.html#element-attrdef-input-type).

> The missing value default is the Text state.

Thus, some HTML minifiers will transform

```html
<input class="fd-form__control" type="text" />
```

into

```html
<input class="fd-form__control" />
```

resulting in input element which looks not "fundamentally". :) Actually this happened to us when we tried to integrate Fundamental into our code base.

I will open an PR in 5 minutes. I am writing this issue in order to be able to ref. it from the PR and for documentation purposes.

**Comment by MattL75** [comment]
Linking to #1248 which wants to either remove this altogether or provide some easy way to opt-in or out
