### ISSUE TITLE
Lib: Table Cell vertical alignment bad readability

### ISSUE THREAD

**Issue by antiheld** [SAP/fundamental#1285]
> Is this issue related to a specific component?

Table Component

> What version of the Fiori Fundamentals are you using?

v1.4.3 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Kyma / CDS / ModelT

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular 

**To Reproduce**
Create a table that has multiple lines within one cell and resize the page to a narrow viewport width.

<img width="973" alt="screenshot 2019-02-21 at 17 33 03" src="https://user-images.githubusercontent.com/1991339/53185188-cedbfe00-35fe-11e9-9366-63a0935bd03d.png">

**Expected behavior**
vertical-align:top; would resolve the readability issue.

**Comment by droshev** [comment]
@LeoT7508 what is your advice here?

**Comment by LeoT7508** [comment]
Is there really a scenario where a person will have 12 first names? What situation would call for there to have the information listed? Why wouldn't the names be in a sentence format separated by commas? The columns should be more thought out, how can you more affectively use the space? First off the first column is way too wide, shorten that up, make the First Name column wider and make those names into sentences separated by commas like I mentioned above. This will begin to address your spacing issue. To give the best answer we would need a more realistic scenario, unless I'm misunderstanding why would someone have 12 first names?
