### ISSUE TITLE
Lib: Popover body arrows in other directions

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental#1286]
We would like to have popover body arrows for the left/right/bottom in addition to the top

> Is this issue related to a specific component?

Popover

> What version of the Fiori Fundamentals are you using?

latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

fundamental-ngx

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

**Describe the solution you'd like**

We have received several requests for auto-placement of the popover body depending on available screen room, scroll position etc.  We have implemented popper.js/ngx-popper to achieve this, however, we need popover arrows for each position the body can be in.

Check out the popper.js docs: https://popper.js.org/

A list of the possible placements (each might need its own arrow): https://popper.js.org/popper-documentation.html#Popper.placements

Here's a screenshot of what we've got now, the popover body has repositioned itself above the control but the arrow still points up
<img width="190" alt="screen shot 2019-02-21 at 10 37 39 am" src="https://user-images.githubusercontent.com/2471874/53204812-cc22de00-35e9-11e9-8a1a-159eb0de9d22.png">

**Comment by bcullman** [comment]
positioning and edge detection library popperJS does this. https://popper.js.org/

**Comment by mikerodonnell89** [comment]
We are working on implementing this with popper.js, closing
