### ISSUE TITLE
Bug: Button border missing (IE11/Edge)

### ISSUE THREAD

**Issue by OldHippie68** [SAP/fundamental#1287]
**Describe the bug**
Button borders are missing after running npm run build

Is this issue related to a specific component?
Buttons

What version of the Fiori Fundamentals are you using?
1.4.3

Front-end framework:
React

**Screenshots**
Expected Button Style in IE11which occurs when using npm start
![expectedbuttonstyle](https://user-images.githubusercontent.com/33554749/53211670-4a3daf80-35ff-11e9-8fb0-04c876685fb9.JPG)

Unexpected Button Style in IE11 which occurs after npm run build
![image](https://user-images.githubusercontent.com/33554749/53211775-a6a0cf00-35ff-11e9-83c5-7ece145b470e.png)

**Desktop information**
 -OS Windows 10 
 - Browser Internet Explorer 11
 - Version 11.1540.10586.0

**Additional context**
The application imports fiori-fundamentals/dist/fiori-fundamentals-ie11.css
Inspector shows:
 .fd-button,[class*=1px solid var(--fd-button-border-color)      
../node_modules/fiori-fundamentals/dist/fiori-fundamentals-ie11.css  (4614)

**Comment by saad-mo** [comment]
hi @OldHippie68, 

can you please test this issue again with the latest version of the library? I tried to recreate this issue, but the buttons seem to render without any issues. 

You can utilize this js fiddle - https://jsfiddle.net/n00b3/h64q7tr8/2/

Here is a result of my testing on IE11

<img width="1440" alt="Screen Shot 2019-05-09 at 10 30 29 AM" src="https://user-images.githubusercontent.com/15215400/57466168-b2d31a80-7245-11e9-9000-dde8db55407c.png">

Please reopen the issue if the problem persists.
