### ISSUE TITLE
Bug: Dropdown arrow incorrect for disable dropdowns for IE11 compatible file

### ISSUE THREAD

**Issue by roshini-david** [SAP/fundamental#1288]
We have tested this in Fieldglass application using the ie11-compatible less copy provided by the FD team.
It is only happening with this file, the official one on https://sap.github.io/fundamental/components/form.html looks fine.
Html:
```
<select class="fd-form__control" id="select-2" name="" disabled="">
    <option value="1">Duis malesuada odio volutpat elementum</option>
    <option value="2">Suspendisse ante ligula</option>
    <option value="3">Sed bibendum sapien at posuere interdum</option>
</select>
```

![image](https://user-images.githubusercontent.com/30301448/53270520-8f221e80-36b1-11e9-9873-66c23c874e9e.png)

**Comment by droshev** [comment]
@roshini-david could you retest with the latest version?
