### ISSUE TITLE
Linting rules

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#1298]
Working on fundamental-aurelia preparation, I would like to follow the same style linting rules defined in fundamental project, rather than spending efforts on maintaining own. 

Trying to find out more about fundamental sass linting, I found only [/.sass-lint.yml](https://github.com/SAP/fundamental/blob/develop/.sass-lint.yml) and apparently no linter in [package.json](https://github.com/SAP/fundamental/blob/develop/package.json) using these settings. Briefly inspecting [gulp tasks](https://github.com/SAP/fundamental/tree/develop/ops/gulp) I found nothing related to linting either. In fundamental angular and vue implementations also nothing related to style linting.

Considering that style extensions and adaptations are often required in projects, would it make sense to define the default linting rules and the default linter in fundamental project, which other implementations could reuse? So far I am using [stylelint](https://github.com/stylelint/stylelint), offering very good start-up configurations like [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended) or [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard), incorporating best practices from Google, Facebook, Airbnb ...

Stronger and more consistent linting rules would be IMHO good from the very beginning because later changes are costly, requiring mostly manual rework of the sass codebase.

**Comment by saad-mo** [comment]
@bsrdjan we definitely want to implement linting in fundamentals, but very low on dev resources at the moment. We would definitely welcome any contribution on this topic. :)

**Comment by eboyer** [comment]
@bsrdjan ~ Closing this issue as linting is now making its way in one rule at a time! As Saad mentioned feel free to jump in and contribute to the updates/discussion as we go.
