### ISSUE TITLE
Audit: components that do not have proper markup for a11y

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#1319]
Relevant: #1178

In addition to what's described in issue #1178 ~ audit and identify components in the library that are currently relying on generic `<span>`, `<div>`, etc tags to describe text. These either need to be paired with proper aria attributes or utilize better semantic markup alternatives.

This issue is complete once there is an audit of all components in the library, and specific issues that are identified as a result.

**Comment by jbadan** [comment]
@eboyer To not duplicate effort, there are a couple a11y issues in the markup of the components that have been identified in this list: https://github.com/SAP/fundamental-react/wiki/Topics-for-Fiori-Fundamentals

**Comment by jbadan** [comment]
Related to #1346, #1348, #1349, #1350, #1351, #1352, #1353, #1345
