### ISSUE TITLE
Lib: Alert component updates

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#1332]
Update the X color, include wrapping, update icon, add variation with text only and icon and wrapping text.

**Comment by eboyer** [comment]
@LeoT7508 ~ Tracking the issue for Alert updates here. Could you let me know when you update the sketch file to be released with this?

**Comment by LeoT7508** [comment]
Updated design sheet can be found here:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5c61a6e1015f1e11aa68832b

Updates include:

- Updated information icon for Information message

- Close "X" icon color change to 0A6ED1

- Addition of message with only text

- Addition of message with wrapping text.

**Comment by droshev** [comment]
<img width="150" alt="Screen Shot 2019-03-27 at 11 40 57 AM" src="https://user-images.githubusercontent.com/4380815/55090306-416c4d80-5085-11e9-92b8-754a2f595ae4.png">
