### ISSUE TITLE
Lib: Checkbox component updates

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#1333]
Update selected state and checked state (only showing arrow now)

**Comment by eboyer** [comment]
@LeoT7508 ~ Tracking the issue for Checkbox updates here. Could you let me know when you update the sketch file to be released with this?

**Comment by LeoT7508** [comment]
Updated design sheet can be found here:
https://zpl.io/2Gokp8m

Updates include:

- Selected check box does not have a filled shape anymore, its an blue outlined box filled with white, and  a blue check mark
