### ISSUE TITLE
Lib: Radio component update

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#1334]
Size of inside filled in selected circle - Fund 4 / GD is 1o, Size of outside circle Fund 16/GD 22

**Comment by eboyer** [comment]
@LeoT7508 ~ Tracking the issue for Radio updates here. Could you let me know when you update the sketch file to be released with this?

**Comment by LeoT7508** [comment]
Updated design sheet can be found here:
https://zpl.io/2Gokp8m

Updates include:

- Selected check box does not have a filled shape anymore, its an blue outlined box filled with white, and  a blue check mark

- Radio button inner circle increased in size by 2px.
