### ISSUE TITLE
Lib: Input component updates

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#1335]
Colon after labels, update Active, Read-only and Disabled styling

**Comment by eboyer** [comment]
@LeoT7508 ~ Tracking the issue for Input updates here. Could you let me know when you update the sketch file to be released with this?

**Comment by LeoT7508** [comment]
Updated design sheet can be found here:
https://zpl.io/VqlZO8G

Key updates include:
- Updated Read Only input
- Updated Disabled input
- Updated Alerts & Messages Inputs. Message text color updated, color added behind messages, and   Success and Informations variations added.

**Comment by MattL75** [comment]
Not sure if I should tie this here or elsewhere, but I'll link https://github.com/SAP/fundamental-ngx/issues/735
