### ISSUE TITLE
Responsive Layouts' Issues

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#1356]
Tested with v1.4.9-rc.1 and macOS Chromium Version 73.0.3683.86 (Official Build) (64-bit)

[**Full Width App Layout**](https://sap.github.io/fundamental/demo-pages/full-width-app-demo.html)

The dropdown runs out of the viewport

![Screenshot 2019-03-27 at 10 07 37](https://user-images.githubusercontent.com/1697847/55063392-2c3cf200-5078-11e9-8733-d5ef205d9605.png)

[**Sidebar App Layout**](https://sap.github.io/fundamental/demo-pages/sidebar-app-demo.html)

The flow looks broken, possibly related to #1311

![Screenshot 2019-03-27 at 10 01 46](https://user-images.githubusercontent.com/1697847/55063117-93a67200-5077-11e9-9bda-c68278a705aa.png)

**Comment by droshev** [comment]
@bsrdjan the popover edge cases will be handled by the implementation libraries:
https://sap.github.io/fundamental-ngx/popover

**Comment by bsrdjan** [comment]
Thanks! The popover would fix the first issue but the second one seem to be the different one? To be handled by responsive design eventually?
