### ISSUE TITLE
implement Tenant and Region Switch as part of the shell-bar

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental#1368]
**Is your feature request related to a problem? Please describe.**

> Is this issue related to a specific component?

> What browser are you working in?

> What version of the Fiori Fundamentals are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by droshev** [comment]
@LeoT7508 do we have a design for that?

**Comment by LeoT7508** [comment]
There is a dropdown component for the Shellbar that I would think can serve either purpose. U included it in the design sheet. 

https://zpl.io/VqlZOg4

**Comment by droshev** [comment]
we agreed @LeoT7508 to update the spec in terms of dropdown colors(egular state, hover, disabled, button hover) and we should be good to go

**Comment by LeoT7508** [comment]
Per the design spec from Global Design it will require that we add colors to the palette.

**Comment by LeoT7508** [comment]
@droshev 

Correction, we already have these colors in the library. 
The updated design sheet can be found here: https://zpl.io/VqlZOg4

**Comment by eboyer** [comment]
@droshev @LeoT7508 ~ Did you guys discuss the issues/implications adding this has to the breakpoints / responsive behavior of the shellbar? This was the biggest issue its potentially causing. I wouldn't say this story is "ready for dev" until thats completely specced out and clear with a plan.

**Comment by LeoT7508** [comment]
@eboyer Can u provide details into the issues wit might cause? We have documentation about how the grid should work. It's mostly margins, nothing is really affected until you get to tablet.

**Comment by LeoT7508** [comment]
This is a valid concern. Maybe its something we bring up with GD to see how they plan to handle this? I haven't seen documentation explaining this specifically.
