### ISSUE TITLE
Accessibility: Icons for status message

### ISSUE THREAD

**Issue by gcho1023** [SAP/fundamental#138]
Based on SAP ACC, all status messaging system should not rely only on color and text. Icons need to be added. The form messages have icons next to them, but the status messages don't. It does not meet standard ACC, only covered by color.

Fundamental UI:
<img width="1139" alt="screen shot 2018-03-20 at 9 37 06 am" src="https://user-images.githubusercontent.com/32933889/37661241-580bb1bc-2c22-11e8-9d4e-f3610c86d9f5.png">
<img width="587" alt="screen shot 2018-03-20 at 9 38 09 am" src="https://user-images.githubusercontent.com/32933889/37661283-7124ba72-2c22-11e8-869b-1bc45f992cfc.png">
Fiori:
https://experience.sap.com/fiori-design-web/wp-content/uploads/sites/5/2017/03/message_view.png

**Comment by joseegm** [comment]
@gcho1023 

This is an easy one, we can do it on code. We have the icons and I think we can put the same color as the text for the icons.

@saadmhybris 
We can put this on the next milestone as well.

**Comment by gcho1023** [comment]
sounds good!

**Comment by saadmhybris** [comment]
@gcho1023 @joseegm 

what icon to use for the default alert? using error icon for error and warning icon for the warning.

**Comment by gcho1023** [comment]
example attached 
<img width="526" alt="screen shot 2018-03-26 at 8 30 20 pm" src="https://user-images.githubusercontent.com/32933889/37941586-8eeebf96-3134-11e8-8ced-61d483ff5fba.png">

**Comment by saadmhybris** [comment]
<img width="1379" alt="screen shot 2018-03-27 at 11 45 47 am" src="https://user-images.githubusercontent.com/15215400/37981854-723ab9d8-31b4-11e8-8b3f-9dfa6c02aa9b.png">


@gcho1023 @LeoT7508 @joseegm  what do you guys think? does this work?

**Comment by LeoT7508** [comment]
@saadmhybris 

This all needs re-work to align with Modular Design, so no need to think about it too much right now.

**Comment by saadmhybris** [comment]
<img width="472" alt="screen shot 2018-03-27 at 11 56 48 am" src="https://user-images.githubusercontent.com/15215400/37982387-0a7ba3c8-31b6-11e8-82a4-f83c2e75cef5.png">

added success alert

**Comment by saadmhybris** [comment]
@LeoT7508 ok. I'll save what I have now and move on to the header.

**Comment by saadmhybris** [comment]
yep. this is done already.
