### ISSUE TITLE
Fiori 3.0 Visual Update: Update Icon Library

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1386]
We are missing some icons in the fundamentals library compared to what is available on Sap icon library (32 to be exact). 

> Side note: we are specifically looking for the `task` icon to use in Smartedit/Personalization 
![Screen Shot 2019-04-12 at 8 40 14 AM](https://user-images.githubusercontent.com/15215400/56041553-9ef7cf80-5cfe-11e9-8786-6ea2dd7b1939.png)

[Sap Icon Library](https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid
) - switch to "Sap Icons" from the top bar 

Todo: 
- add new missing icons to the fundamentals library 
- update downloadable icons set on the UI Kit page

Attached is the latest set of icon font files 
[Icon Fonts.zip](https://github.com/SAP/fundamental/files/3073475/Icon.Fonts.zip)

**Comment by saad-mo** [comment]
[fundamentals-icon-list.txt](https://github.com/SAP/fundamental/files/3073891/fundamentals-icon-list.txt)
[sap-icon-list.txt](https://github.com/SAP/fundamental/files/3073892/sap-icon-list.txt)

I generated this list for both of what we have in fundamentals and what's avialable on sap icon library site. I was not able to find a good way to compare both files and return the difference.

**Comment by droshev** [comment]
I was able to identify 27 icons. There are 2 with the same name `\e284` and `\e286` are named `collapse-all`
