### ISSUE TITLE
Docs: Color page updates 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#141]
- update to new design - https://zpl.io/V1MG9Q4
- [Color pallet](https://sap.github.io/fundamental/fundamentals/colors.html) should copy the color function when you click on it. for example copy `tn-color("primary", 1)` to clipboard when you click on the first color tile. this will help developers easily pick colors.

**Comment by xak** [comment]
@saadmhybris I like this. I'll leave it to you to prioritize. It's easy enough to release at any time.
