### ISSUE TITLE
Visual Aligment with the ActionBar

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#142]
### Goal
Validate and align the action bar with the new modular design.

### Current requirements
1. The Action Bar is used to display the current title/purpose of the page.
2. The Action Bar can have actions that are performed on the object that is represented by the page.
3. The Action Bar have a "back" button that permit the user to navigate back in the flow.

### Current
https://sap.github.io/fundamental/components/action-bar.html

### Reference
https://app.zeplin.io/project/5a5e1cb96e836180d25dfebd/screen/5a86a29bb388dd4503fdd726

### Posible requirements changes
> In relation to the originals requiriments
1. The Action Bar may display a second line of text under the title; this will replace the old Page Level help - ref https://sap.github.io/fundamental/starter-pages/table-starter-page.html

### Tasks
* [ ] Validate the current requirements and *possible requirements changes* 
* [ ] Wireframes - only in case the requirements change
* [ ] Visual refresh

**Comment by LeoT7508** [comment]
@joseegm 

Action Bar visuals are on Zeplin here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5abbeac18086873b0b4a7670

**Comment by joseegm** [comment]
This one is good for start the development.
