### ISSUE TITLE
Compact datepicker button overflow bug

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental#1421]
Compact datepicker button overflows when you click on it, seems to be on both active and focus.

![image](https://user-images.githubusercontent.com/24924530/56762767-a3949d00-676e-11e9-8d25-d0b9fc496a9d.png)

Can also be seen here https://sap.github.io/fundamental/components/date-picker.html

**Comment by droshev** [comment]
even if you open the normal one there is an issue:
![Screen Shot 2019-05-03 at 3 22 53 PM](https://user-images.githubusercontent.com/4380815/57160648-6310d100-6db7-11e9-9802-ea5062dd7e80.png)
