### ISSUE TITLE
No max height on popover for long lists

### ISSUE THREAD

**Issue by hertweckhr1** [SAP/fundamental#1423]
### Description
There is no styling around a max height of the popover (or menu). This menu could get so big that it won't matter where it's positioned -- it'll be partially hidden regardless. The Fiori Fundamentals site only uses 3 items in the dropdown menu so it doesn't really expose this issue. See screenshots below.

To fix we should add styling to the popover (or menu) for max height. 

![image](https://user-images.githubusercontent.com/34703079/56828746-d5f9d500-6816-11e9-9b7c-30a6e36c1de3.png)

![image](https://user-images.githubusercontent.com/34703079/56828793-ea3dd200-6816-11e9-8dd0-abedee98cb47.png)

Fiori Fundamentals: v1.5.5

**Comment by droshev** [comment]
create a focus group

**Comment by ChristianKienle** [comment]
Related issue: What about the width? Do we want to solve this in the individual libraries since this is caused by using Popper/having the popover in the body.
