### ISSUE TITLE
Action bar description not wrapping the words

### ISSUE THREAD

**Issue by pavansokkenagaraj** [SAP/fundamental#1428]
**Describe the bug**

Action Bar descriptions are not wrapped/break
https://codepen.io/pavan-sokke-nagaraj/pen/vMMWOx

**Expected behavior**
descriptions should be multi-lined when there is no space

**Screenshots**
![image](https://user-images.githubusercontent.com/8703626/56919862-b0c3cb80-6a8f-11e9-9a2d-e0268ea21a42.png)

**Comment by droshev** [comment]
@LeoT7508 is this a valid requirement? It looks odd if we put a paragraph as a description.

**Comment by LeoT7508** [comment]
Per standards a sentence shouldn't be longer than 20 words long max. I would recommend keeping it at 15 words max, this is what UX patterns suggest. Per our grid that would put us at about 10 columns, so from a dev side if you guys can set that up to wrap at 10 columns that would be ideal. Having that line extend all the way to the end of the page isn't something we should do or allow.
