### ISSUE TITLE
Docs: Design System Utilities page return 404

### ISSUE THREAD

**Issue by rsletta** [SAP/fundamental#1432]
All links to [Design System Utilities](https://sap.github.io/guides/design-system-utilities.html) are broken, since the page return a 404 - File not found. 

This issue is related to issue [Docs: Colors page has a broken link #1295](https://github.com/SAP/fundamental/issues/1295).

Navigate to [https://sap.github.io/guides/design-system-utilities.html](https://sap.github.io/guides/design-system-utilities.html) to reproduce the issue.

**Comment by jbadan** [comment]
@rsletta The link you have is slightly incorrect- try https://sap.github.io/fundamental/resources/design-system-utilities.html

Please reopen the issue if that wasn't what you were looking for.
