### ISSUE TITLE
Visual Alignment Table

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#144]
### Goal
Align the Table component with the Modular Design.

### Current
https://sap.github.io/fundamental/components/table.html

### Reference
https://app.zeplin.io/project/5a5e1cb96e836180d25dfebd/screen/5a71abeb866bb8e6bb49d4ba

Mainly the changes are a colors and size and spacing.

**Comment by LeoT7508** [comment]
@joseegm 

Table visuals are on Zeplin here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5abe7c999d06312556f62fe7

**Comment by joseegm** [comment]
@saadmhybris 
I think this one is good to go. Don't worry about the size of the checkboxes etc; those will be addressed on other ticket.
