### ISSUE TITLE
Problem with actionBar within the Page

### ISSUE THREAD

**Issue by fkolar** [SAP/fundamental#1449]
**Describe the bug**

When you try to render https://sap.github.io/fundamental/components/action-bar.html inside the page along with context menu and with 100% of page width, the menu is render offscren. It goes over the right edge of browser. 

**Expected behavior**
Since the ... DOTS button is all the way on the right side we should show the triangle for the overlay on the right side

**Screenshots**
added 
<img width="1090" alt="Screen Shot 2019-05-17 at 4 55 47 PM" src="https://user-images.githubusercontent.com/17149942/57936739-c412cb80-78c4-11e9-8fd6-c867608e2b8a.png">
<img width="1400" alt="Screen Shot 2019-05-17 at 4 55 43 PM" src="https://user-images.githubusercontent.com/17149942/57936740-c412cb80-78c4-11e9-9089-5af877b01b0c.png">

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser Chrome
 - Version 74.0.3

**Comment by saad-mo** [comment]
Hi @fkolar -

You can you the `fd-popover__body--right` modifier on `fd-popover__body` to align the popover menu to the right edge of the button. this way, the menu should open within the page view. Please close this issue if this solves your problem. 

More info on placement options for the popover component can be found here -
https://sap.github.io/fundamental/components/popover.html#placement-options

**Comment by droshev** [comment]
@fkolar are you using `fiori fundamentals` or `fundamental-ngx`?

**Comment by fkolar** [comment]
Let me try to the placement. thanks for the info. btw. the right placement does onot have the triangle? 

@droshev for this usecase we need to use page layout, plus action bar directly from this library as we need to deliver a lightweight webcompoennt, that works in AngularJS and Angualr 4.
