### ISSUE TITLE
Footer Toolbar

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#1452]
Footer Toolbar
Requirements documented in attached image.
![footer_toolbar_bar](https://user-images.githubusercontent.com/24274321/58030554-bdff3380-7aec-11e9-9f1c-b860817bcc13.png)

**Comment by jeannewalters** [comment]
@saad-mo @LeoT7508 
Any update on this ticket? There are two teams requesting this component now and I would expect more to request it soon too.
Thanks

**Comment by saad-mo** [comment]
@jeannewalters added this to the next milestone. @LeoT7508 can you pls provide designs?

**Comment by LeoT7508** [comment]
Design sheet can be found here:

https://zpl.io/VYp0mQd

**Comment by saad-mo** [comment]
closing this and moving to fd-styles - https://github.com/SAP/fundamental-styles/issues/216
