### ISSUE TITLE
Section Heading in Panel/Card/Tile

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#1454]
There are times when a subheading is needed within a panel/tile/dialog/card. Examples attached from Cloud Commerce but other apps are requesting this as well.
![image](https://user-images.githubusercontent.com/24274321/58099581-f0bb3180-7ba9-11e9-8083-9ce048edd720.png)
![image](https://user-images.githubusercontent.com/24274321/58099356-74c0e980-7ba9-11e9-9f49-8b7da361834b.png)
![image](https://user-images.githubusercontent.com/24274321/58099416-93bf7b80-7ba9-11e9-94b5-7c9ca002f34d.png)

**Comment by LeoT7508** [comment]
@jeannewalters 

What you are looking for should be here: https://zpl.io/adpeN8L

**Comment by jeannewalters** [comment]
@LeoT7508 In the last example above, it would be the IP Filter Sets and Redirect Set. The zeplin file only handles the panel title and subtitle. These are the sections within the panel below the line. I think what UX is looking for is a styling for that which would differentiate it from a field label.

**Comment by LeoT7508** [comment]
So we just need the styling for the subheading, this doesn't involve the Panel title. It seems the way they approached in the top example you provided makes sense.

**Comment by jeannewalters** [comment]
Styling for this type of heading - 
![image](https://user-images.githubusercontent.com/24274321/58105587-c327b580-7bb4-11e9-8c79-4e83a1e9fb19.png)

**Comment by MattL75** [comment]
Is it okay to share CC screens publicly?

**Comment by LeoT7508** [comment]
@jeannewalters 

The style they are looking for is here under the Object Card: https://zpl.io/amdWYz6

**Comment by jeannewalters** [comment]
I sent it to Marie. Thanks
