### ISSUE TITLE
Docs: Search not working

### ISSUE THREAD

**Issue by jbadan** [SAP/fundamental#1476]
It looks like the search box has stopped working in between this pr https://github.com/SAP/fundamental/pull/1447 and now. 

It works in the netlify preview from that pr, but we could try reverting to see if that fixes the issue.

![Screen Shot 2019-06-03 at 12 59 32 PM](https://user-images.githubusercontent.com/29607818/58830606-8cfc2400-85ff-11e9-94fb-a0bd462d1f32.png)

**Comment by ckoutsiaris** [comment]
Something similar happened a few months ago https://github.com/SAP/fundamental/pull/1116 
The issue at that time was some html in the options part of the md file. Don't know if it is the same here but might worth checking.
