### ISSUE TITLE
Lib: Form Input design updates based on ui kit design (v1.4.3)

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#1498]
- [x] update input focus state
- [x] Updated input Disabled state
- [x] Additional support for error, warning, success, Information states of fields
- [x] Italic text for placeholder text
- [ ] Upload File button for forms (new component, will be addressed in a separate ticket) 
- [x] Required label has a red *

![Screen Shot 2019-06-17 at 10 44 18 AM](https://user-images.githubusercontent.com/15215400/59617940-e29afb00-90ec-11e9-92a8-f02f6f937883.png)

**Comment by bcullman** [comment]
@saad-mo: is the appearance of warning/error/info/success messages below the input a fiori3 design choice?

**Comment by saad-mo** [comment]
> @saad-mo: is the appearance of warning/error/info/success messages below the input a fiori3 design choice?

Yes, everything is from Fiori 3 design, unless otherwise noted.
