### ISSUE TITLE
Application Shell and Shellbar Usage

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#1504]
Reading the documentation, I could not figure out when to use the [Application Shell](https://sap.github.io/fundamental/layouts/shell-layout.html) and when to use the [Shellbar](https://sap.github.io/fundamental/components/shellbar.html)? Here my questions:

1. How one typical Fiori transactional business app should be structured, which of these two components should be used when ?

2. What this part of [Application Shell](https://sap.github.io/fundamental/layouts/shell-layout.html) documentation is actually telling? Application Shell implements the Shellbar header ?

> .fd-shell__header: Global header for shellbar component

3. According to [Shellbar](https://sap.github.io/fundamental/components/shellbar.html) documentation:

> The shellbar should be placed inside the shell layout container.

This means the Shellbar should not be the top-most application element, but the Application Shell, correct? Could you please share one example, showing the Shellbar inside the shell layout container? I could not find one.

**Comment by saad-mo** [comment]
Hi Srdjan – 

Application `Shell` is for high-level layout for the application and `Shellbar` is the top header component of the application and it should be placed inside of the .fd-shell__header container. 

Ideally, your application layout should look like this 
```
.fd-shell
   .fd-shell__header
      .fd-shellbar (component)
   .fd-shell__app
      .fd-app
         .fd-app__navigation
         .fd-app__main
   .fd_shell__footer
      .fd-shell__footer--fixed
.fd-shell__overlay
   .fd-overlay
```
Hope this helps.
