### ISSUE TITLE
Input Group search input clear button not shows up.

### ISSUE THREAD

**Issue by KakaWangSAP** [SAP/fundamental#1518]
#### 
In https://sap.github.io/fundamental/components/input-group.html, Input with icons-search input example, when enter some value in search input, the clear button is not show up, even we can find it in the DOM.
![image](https://user-images.githubusercontent.com/51769984/62516669-4671b280-b858-11e9-9952-d2c3c700ba65.png)

One more thing, can we put the search icon in the end of the input box and make it clickable?
For example:
![image](https://user-images.githubusercontent.com/51769984/62516750-791bab00-b858-11e9-9a20-2d9598f88b52.png)

**Comment by saad-mo** [comment]
@KakaWangSAP fundamental-ngx is now using fundamental-styles. Please open this issue in that backlog  -https://github.com/SAP/fundamental-styles
