### ISSUE TITLE
Error on @import ~fiori-fundamentals/scss/layout and /all

### ISSUE THREAD

**Issue by weitlos** [SAP/fundamental#1524]
Hi,

I tried to follow the steps shown in this youtube video: https://www.youtube.com/watch?v=P5AP2wTpx7Y

On importing multiple files there is always one failing:
@import "~fiori-fundamentals/scss/core";
@import "~fiori-fundamentals/scss/layout"; <-----
@import "~fiori-fundamentals/scss/helpers";

Here is the error message from the console while trying to execute ng serve:

ERROR in ./src/scss/core.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/scss/core.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
                ^
      Expected "=".
   ╷
15 │     @if $direction = horizontal {
   │                     ^
   ╵
  node_modules\fiori-fundamentals\scss\layout\_mixins.scss 15:18  @import
  node_modules\fiori-fundamentals\scss\layout\_col.scss 4:9       @import
  node_modules\fiori-fundamentals\scss\layout.scss 3:9            @import
  node_modules\fiori-fundamentals\scss\all.scss 13:9              @import
  stdin 8:9

![Error](https://user-images.githubusercontent.com/19833878/63110273-56da0980-bf8b-11e9-95f3-97d9dc54e407.JPG)

> Is this issue related to a specific component?
No 
> What version of the Fundamentals are you using?
Actually I don't know. I just started today working with it.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
No

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1. Include the following line of code in your project: @import "~fiori-fundamentals/scss/layout";
2. run ng serve

**Expected behavior**
From what I saw in the video I would expect, that ng serve would compile successfully.

Desktop:
 - Windows 10
 - Chrome

**Additional context**
This is my first issue ever so please excuse if not perfect. I hope the information above will help you! I really like the idea of Fiori Fundamentals and looking forward to great stuff.

**Comment by moloti** [comment]
I have the exact same issue

**Comment by moloti** [comment]
So after some trying, it worked with downgrading sass-loader to 7.x version. Hope that helps!

**Comment by adgasi** [comment]
This is a syntax error. I am facing the same issue in my project.
It was detected after replacing the `node-sass` with `dart-sass` (sass npm package).
New preprocessor throws the following error:
![fundamentals_bug](https://user-images.githubusercontent.com/4891031/103647910-51080e00-4f5c-11eb-88be-e91905b03f65.png)


**Fix**
As is
```
@if $direction = horizontal {
```

To be
```
@if $direction == horizontal {
```
