### ISSUE TITLE
dropdown issues

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#153]
noticed 2 issues in dropdown:
1. when you open it the menu is not visible:
2. dropdown with the icon doesn't work
![screen shot 2018-03-27 at 9 27 21 am](https://user-images.githubusercontent.com/4380815/37970359-444dd8b0-31a1-11e8-90ac-25b5fec81950.png)
![screen shot 2018-03-27 at 9 27 28 am](https://user-images.githubusercontent.com/4380815/37970360-446552d8-31a1-11e8-9eb5-08d6d81d17fd.png)

**Comment by saadmhybris** [comment]
![82548126_o](https://user-images.githubusercontent.com/15215400/37976635-8aabfb60-31a7-11e8-952a-2f0644df97dc.jpg)

**Comment by saadmhybris** [comment]
fixed
