### ISSUE TITLE
Icon Component --split icon doesn't want to load

### ISSUE THREAD

**Issue by marinagroepel** [SAP/fundamental#1566]
**Describe the bug**
The 'sap-icon--split' does not want to load.

> Is this issue related to a specific component?
It is related to icon component.

> What version of the Fundamental Library Styles are you using?
"fiori-fundamentals": "^1.7.8"

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
I'm implementing new element icons for Knowledge-management application. It should be released before mid of November

**To Reproduce**
Add line of code (to any app using fundamentals) described in documentation: <span class="sap-icon--split sap-icon--l"></span>
Build the app
See that icon does not show up

**Expected behavior**
Icon works properly as all other icons.

**Screenshots**
![image (10)](https://user-images.githubusercontent.com/71707753/93884802-a9840a00-fce3-11ea-9a0e-56a70ab039e9.png)

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome
 - Version: 85

**Comment by stefanoScalzo** [comment]
@marinagroepel Do any of the other sap icons work?

**Comment by marinagroepel** [comment]
@stefanoScalzo most of the other icons worked.
