### ISSUE TITLE
Lib: toolbar misalignments

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#159]
hello,

In smaller resolutions the toolbar looks a bit miss-aligned.
![toolbar3](https://user-images.githubusercontent.com/4380815/38095091-99e36162-333d-11e8-812b-d151e477f9dc.png)
![toolbar2](https://user-images.githubusercontent.com/4380815/38095092-99f4e950-333d-11e8-8a08-5fdba24ec730.png)
![toolbar1](https://user-images.githubusercontent.com/4380815/38095093-9a0d873a-333d-11e8-8d56-644f5193094c.png)

**Comment by xak** [comment]
The `toolbar` has been deprecated in favor of panel actions and filters with pagination now on the bottom.
