### ISSUE TITLE
Lib: Toolbar specificity

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/fundamental#160]
The toolbar styling is not 100% BEM - https://github.com/SAP/fundamental/blob/master/scss/components/toolbar.scss
Is there a way to avoid any specificity? It makes it very coupled to business specific classes (e.g. fd-toolbar__group--filter)

**Comment by xak** [comment]
I agree that it is too tied to a specific implementation and will likely break when customized being that the CSS is complicated in rearranging containers at small screens.

See https://github.com/SAP/techne/issues/1202#issuecomment-344735090

We could never come to agreement on a satisfactory approach. IMO, this is too specific and complicated to be a standalone component.

**Comment by joseegm** [comment]
Yes. We may be "re-doing" it in the future but it is not prio right now.

**Comment by SAPMontreal** [comment]
Agree with Zack - If we implement the angular version then we cannot use the fundamental ui styling.

**Comment by xak** [comment]
The `toolbar` has been deprecated. See `panel` actions and filter containers.
