### ISSUE TITLE
Docs: Global Nav

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#181]
Design - https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5ab953f947b69bd17a12f843

Component - #148 

 GDD workshop checklist - #170

**Comment by saadmhybris** [comment]
@jeannewalters please append any documentation copy you feel is relevant for this component.

**Comment by jeannewalters** [comment]
@saadmhybris 
Here is the text for copy/paste purposes:
**Global Navigation**
The global navigation component offers a similar navigation approach between Hybris applications. It allows for branding, application groupings, access to a left navigation, switch between applications, contexts and access tooling such as search or a users' profile.  
Elements and positioning in the global navigation are optional but included are: 

1) **Suite name** - identifies the suite or common grouping of the applications
2) **Logo** - allows for common branding. SAP Hybris applications display the SAP logo.
3) **Left navigation menu icon** - allows for the left navigation to be expanded or collapsed
4) **Application switcher** - allows for the identification of the application. Users can switch between applications within the suite/grouping of applications.
5) **Context switcher** - allows for switching context of application such as an organization or subscription.
6) **Search icon** - on click, a search field is displayed.
7) **User icon** - on click, user options are displayed such as Sign Off and Preferences.
8) **Additional tooling icons** - if the application requires additional tooling, it can be accessed via an icon in the same area of the global header as the search and user icons.

**Comment by saadmhybris** [comment]
@jeannewalters all the documentation is updated for the global nav - https://sap.github.io/fundamental/layouts/global-navigation.html
