### ISSUE TITLE
Docs: Update Spacing Page based on GDD workshop

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#185]
Spacing: https://sap.github.io/fundamental/fundamentals/spacing.html

Design specs - https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb?seid=5ab5235bb500a1759e6f64d6

@LeoT7508 
- Updated visuals are needed for this page. 
- Pls let Saad know when these are ready.

GDD workshop checklist - #170

**Comment by LeoT7508** [comment]
@saadmhybris 

This should be all done. Please close if you have everything you need.

**Comment by LeoT7508** [comment]
@saadmhybris 

Zeplin design sheet:
https://zpl.io/aM4x4YR

Website layout:
https://zpl.io/awy3KeM
