### ISSUE TITLE
Docs: Update Grids page based on GDD workshop

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#186]
Girds page: https://sap.github.io/fundamental/fundamentals/grid.html

Design Specs - https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5ab52483aab7e99626945eec

@LeoT7508 
- Updated visuals are needed for this page. 
- Pls let Saad know when these are ready.

GDD workshop checklist - #170

**Comment by saadmhybris** [comment]
@LeoT7508 a link to the grid design sheet, please?

**Comment by LeoT7508** [comment]
@saadmhybris 

This is what we have now:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5ab52483aab7e99626945eec

Zack had a detailed conversation with their team when I was there for the design workshop. You might want to talk to him to get a little better understanding how they see this working and how we should apply it for our needs.

**Comment by LeoT7508** [comment]
@saadmhybris 

Updated Grid visual guides. 

https://zpl.io/awykjx1

**Comment by saadmhybris** [comment]
@LeoT7508  can you please export all those images 2x resolution pls.
