### ISSUE TITLE
Lib: Global Nav Updates

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#196]
The following updates need to be applied to the designs:
@saadmhybris  - I am linking you to the ticket so you are aware of what is being changed.
-------------------------------------
Top Nav
- [x] Change "Application Name" to Suite Name next to the logo.
- [x] Placeholder logo should suffice
- [x] Remove House next to application name in center 
- [x] Remove subnav
- [x] Show 3 icons in the left side rather than 4.  Search icon, generic icon and the user box with the initials of the user (per Zack)
- [x] For the mobile inflection, remove house icon,  add the search icon to always be exposed next to the ..., and show an additional version with no left menu

Breadcrumb
- [x] Breadcrumb colors are covered in the design sheet. 

Contextual Switcher
- [x] Switcher, these are context options which is different from an application.  For example, it might be the organization, tenant or site name.

**Comment by LeoT7508** [comment]
@saadmhybris 

This all should be fine from a visual side. I'll assign it to you.

**Comment by saadmhybris** [comment]
<img width="910" alt="screen shot 2018-05-17 at 10 39 51 am" src="https://user-images.githubusercontent.com/15215400/40188060-afd96334-59be-11e8-81f9-58db8d3f7d88.png">

@LeoT7508 - Please see how the context switcher dropdown looks now after some changes to the dropdown component. Do we need to change it by removing border and background so it blends with rest of the components or leave it as it. I feel it looks a bit dominating comapred to other components.

**Comment by LeoT7508** [comment]
@saadmhybris 

You are right, this is not correct. This should work essentially like the application switcher, just on a smaller scale and  with 1px rules on either side. 

Documented here:

https://zpl.io/VkrL9Rg

**Comment by saadmhybris** [comment]
tx, i'll get it updated.

**Comment by saadmhybris** [comment]
removing from 1.1.0 milestone as no work impacting the library was done.
