### ISSUE TITLE
MDS: Update inline-help

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#202]
![screen shot 2018-04-30 at 12 39 11 pm](https://user-images.githubusercontent.com/424119/39441427-81c147b2-4c73-11e8-9cae-83f79883cc08.png)

@LeoT7508 We don't have a design example for this.

**Comment by LeoT7508** [comment]
@xak 

https://zpl.io/agnkooZ

This looks like it should cover this need? It would just be plain text instead of buttons.
