### ISSUE TITLE
Docs: Broken link on How to Use SCSS

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#211]
https://sap.github.io/fundamental/guides/how-to-use-scss.html

There is a link to the colors page that is broken.

![screen shot 2018-04-30 at 12 59 35 pm](https://user-images.githubusercontent.com/424119/39442314-5aea4820-4c76-11e8-9c62-e1d90c0eba5d.png)

**Comment by saadmhybris** [comment]
I don't think it's a broken link. it appears to be from the old structure of the site. the color page link works fine here - https://sap.github.io/fundamental/fundamentals/colors.html

**Comment by xak** [comment]
See https://sap.github.io/fundamental/guides/how-to-use-scss.html#core-functions-and-mixins

> You can refer to the colors page for the complete list of the available color options.
