### ISSUE TITLE
Left navigation update - menu with icon should not have arrows showing additional levels

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#216]
Menu with icons should not have arrows. From a UX perspective, our suggestion will not suggest using this type of menu with multiple levels because of the issue of not being able to show which level they are on when the menu is collapsed.

**Comment by saadmhybris** [comment]
removed from beta-4 milestone as it's a design related ticket.

**Comment by LeoT7508** [comment]
@jeannewalters 

We just covered every scenario. If they aren't needed then they can be excluded.
