### ISSUE TITLE
Visual Alignment for Segmentation

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#223]
Here are the wires that need visual direction needed for the Segmentation team:
table - https://k1xok8.axshare.com/#g=1&p=segments_-_all
full rule set - https://k1xok8.axshare.com/#g=1&p=7_build_segment_-_active
conditions are collapsed - https://k1xok8.axshare.com/#g=1&p=6_build_segment_-_conditions_added
drag/drop - https://k1xok8.axshare.com/#g=1&p=5_build_segment_-_drop
modal - https://k1xok8.axshare.com/#g=1&p=segment_cannot_be_active

**Comment by LeoT7508** [comment]
Visuals completed here:

https://app.zeplin.io/project/5af44f6dcc8449a90ddad8e8/dashboard?seid=5af4ac0f8e1481d953b575a2
