### ISSUE TITLE
Component: Right Panel

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#226]
**Description:**
The right sliding panel can be used for notifications, forms or navigation.  
- It slides out below the global navigation and overlays the page or pushes the page left.
- It can be closed by clicking on an action inside the sliding panel.

**Wires:**
[Wires_DesktopMobile.zip](https://github.com/SAP/fundamental/files/2058523/Wires_DesktopMobile.zip)

**Comment by xak** [comment]
@jeannewalters I posted some old screens that show one use of a slide out panel an Collection/List edit option.
https://hybrisproductdesign.invisionapp.com/d/main#/projects/prototypes/14439777

**Comment by LeoT7508** [comment]
@jeannewalters 

We might need more guidance about what might go in this side panel before we can more accurately visual representations of it. Right now its just general guidance. 

https://zpl.io/25yKzEe

**Comment by jeannewalters** [comment]
Old
