### ISSUE TITLE
Visuals: Multi-input

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#242]
Need to see how tag select dropdown should function. Is this just a special form of a dropdown with a standard menu?

https://openui5.hana.ondemand.com/#/sample/sap.m.sample.MultiInput/preview
https://openui5.hana.ondemand.com/#/entity/sap.m.MultiComboBox

<img width="495" alt="screen shot 2018-05-04 at 8 14 26 am" src="https://user-images.githubusercontent.com/424119/39629915-5457dd92-4f73-11e8-8bf5-f3248bf4127f.png">

**Comment by jeannewalters** [comment]
Is this use case going to be covered by this or will we need a new ticket to cover this?
This is a use case that is going into the Segmentation team's new UI.
![image](https://user-images.githubusercontent.com/24274321/40919253-fe98590a-67d6-11e8-895d-4913a8c50484.png)

**Comment by LeoT7508** [comment]
@xak 

This looks like either or both of the examples you have here would work. We will probably need both.

**Comment by LeoT7508** [comment]
@xak 

I think the functionality you provided looks like what we need. The visual treatment for the dropdown and the corresponding list we already have in the drop down menu design sheet.

**Comment by xak** [comment]
There is some complexity here in the interactions, typing in the `input` vs. selecting from the dropdown. Sometimes a user will only be able to select from a controlled list of tags, other times they can add any number of new tags.

**Comment by LeoT7508** [comment]
@xak @Jagoooo 

Updated design sheet here:

https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b2bd376d8c48d81b5bac674

**Comment by jeannewalters** [comment]
@LeoT7508 Looks good to me.
