### ISSUE TITLE
Docs: Update action bar to beta-4

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#263]
docs page - http://localhost:4000/components/action-bar.html
new component - http://localhost:3030/action-bar

Update the following text:

The Action Bar is located at the top of the page and is used for the following:

1) Page title
2) Main Actions for the page

**Title**
The page title is displayed prominently in the Action Bar. This is helpful for the user to know exactly where they are. 

**Main Actions**
Display main actions within the Action bar. This allows for users to find important page actions in a consistent area no matter what page they are on within the applicaiton.

**Several Main Actions in a Contextual Menu**
When there are several main actions for a page, consider displaying them under a contextual menu.  This allows the user to look in the same position they are used to but avoids cluttering the action bar with more than 3-4 actions. This also works well for a responsive/adaptive application.

**Comment by jeannewalters** [comment]
@saadmhybris 
pls update page:
1) Under Main Actions - remove "we recommend not putting more than four actions on the action bar."
