### ISSUE TITLE
Website: Update Designers Page

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#320]
Can you please take a look at the Designers page on the library website and come up with more helpful content such as:

Fiore design guidelines
Describing pages or areas around the website that are helpful and why (ex. Components)

See #74

Wire:
![image](https://user-images.githubusercontent.com/24274321/41118379-c69d08d2-6a5d-11e8-85ad-387f20e5a4f2.png)

**Comment by gcho1023** [comment]
@jeannewalters could you review the wire and clarify the content... I'm not quite sure what you mean by Fiori design guidelines? why should we add that to here...are we calling this Fiori 3.0?

https://6umx4d.axshare.com/#g=1&p=starters_designers

**Comment by xak** [comment]
@jeannewalters What do you recommend for this?

**Comment by jeannewalters** [comment]
@xak are we calling this Fiore 3? Should we be highlighting Adaptive as a goal?

**Comment by xak** [comment]
I would avoid getting too specific about Fiori 3.0 for now esp. defining a strategy. 

## Fiori Foundation
The component library is built using the same foundation as Fiori 3.0. The modular approach prioritizes flexibility of technology and experience while maintaining a consistent look and feel across applications.

**Comment by jeannewalters** [comment]
@gcho1023 Can you pls replace the Fiore 3.0 section with Zack's content above, let Leo know what images this page needs, assign it to him and move it to the visual column? Thanks!

**Comment by jeannewalters** [comment]
@LeoT7508 Can you provide a new visual for the new wire above?

**Comment by LeoT7508** [comment]
@xak @jeannewalters @saadmhybris 

Updated Designers landing page:
https://zpl.io/2ZqYKW4

**Comment by jeannewalters** [comment]
Old
