### ISSUE TITLE
Component Library in Axure

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#321]
Can you pls create a widget lib in Axure to support the new components? We can use the visuals from Leo, the components going into the lib website. We also can use the Sketch file from GD to mimic how they are creating their design guidelines there.

**Comment by xak** [comment]
Moving this to v1.1

**Comment by gcho1023** [comment]
[FundamentalUI_UIKit.zip](https://github.com/SAP/fundamental/files/2082062/FundamentalUI_UIKit.zip)

This Axure kit is based on the 050218 Sketch File that was given to be. Looking at the zeplin file, I see some color updates so the components would need an update based on the newest Sketch file.

**Comment by gcho1023** [comment]
Once Sketch files are updated,  it can be converted into Axure library by using this Sketch plugin: https://forum.axure.com/t/check-out-our-axure-sketch-plugin-for-bringing-sketch-assets-into-axure-rp/50269

This can only be used once the designer has access to sketch file.
