### ISSUE TITLE
Changes to the Library components based on the Kitchensink angular app

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#33]
On the kitchensink application there is a override CSS file with fixes to some Fundamental Component styles.
https://github.com/joseegm/fundamental-kitchensink/blob/master/src/styles.css

From that, these are the main changes to be made before the beta:
- [x] L2:   Modify app level layout to cover all the browser window
- [x] L11:  Badges doesn't have any margin to separate them from other badges or other content
- [x] L13: Add margin to give more breathing space to the last content of the page
- [x] L15: Containers doesn't grow to the with of the parent
- [x] L21: Some separation for the status is missing
- [x] L23: Card actions are missaligned
- [x] L27: Problem with hover state on disabled items
- [x] L31: Tree doesn't grow to the parent width
- [x] L41, L43: Form items margins are missing

**Comment by saadmhybris** [comment]
.fd-container - has a max width of  1290px
.fd-container--fluid - has no max width.

**Comment by xak** [comment]
@saadmhybris I'd like to review this PR when ready.
