### ISSUE TITLE
Assess which components names need to be changed

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#34]
We have now the suggested names, along with the Fiori name for the "comparable" component at:
https://wiki.hybris.com/display/yintfdes/Comparison+of+Fundamental+and+Fiore+Components

### Tasks
- [ ] Assess which of the Fundamental UI components should be really change.

Note: Some of the Fiori components are more abstract and have more functionality, for example Fiori Lists.

**Comment by saadmhybris** [comment]
@joseegm - I looked at this task and don't feel this should be completed by development. It should either come from you or we need to decide collectively what components need to be renamed. There is a rationale provided for each case.
