### ISSUE TITLE
Docs: Update layouts pages.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#347]
Update all layout pages below - 

.fd-ui .fd-app
  .fd-ui__overlay
  .fd-page
  .fd-section
  .fd-panel
  .fd-container .fd-col

**Comment by LeoT7508** [comment]
@saadmhybris 

Updated here: 
https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/dashboard?seid=5a2ad72a341e3fcdb82c3f4e

https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/dashboard?seid=5a284597dd015b9e08536e05
