### ISSUE TITLE
Visuals: Popover

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#352]
Requirements include:
- Pop over that can open from the top left, top middle, top right, bottom left, bottom middle, bottom right
- Can include action, a close icon or none
- Can contain content (Smart Edit, Conversion)
- Can contain image 

DISCUSS - Additional requirements may include:
- Popover with Nav Container (UI5 supports this)
https://openui5.hana.ondemand.com/#/sample/sap.m.sample.PopoverNavCon/preview

**UI5 examples:**
zpl://screen?sid=5ad9f0be573195ebbea03434&pid=5a8c458b6e231fc65bddbdfb

https://openui5.hana.ondemand.com/#/entity/sap.m.Popover

**Current MDS visuals** -  https://zpl.io/agnkooZ

Comment from Zack:
See #98

**Comment by LeoT7508** [comment]
@xak 

I dont know if we  need anything else. The documentation is here:

https://zpl.io/agnkooZ

That should suffice until we find another instance we need to accommodate. 

???

**Comment by xak** [comment]
@jeannewalters Are you satisfied with a simple initial implementation? Can this be closed?

**Comment by LeoT7508** [comment]
@jeannewalters @xak 

What else are we missing here? Do we need usage guidelines? Whats the ask?

**Comment by xak** [comment]
@LeoT7508 The example design doesn't show the variety of requirements described in the issue. However, @eboyer is building this to be a very generic container that can hold a variety of content. It won't do much on it's own so I think we can proceed with what we have.

The obvious issues for me are 1) overflow for a long list of items, 2) header, footer, action elements as part of the popover. We don't have uses case for the latter so I'm less concerned about that and maybe it's just part of the child content.

**Comment by jeannewalters** [comment]
@LeoT7508 do you want a wire with the options that may or may not be in here?

**Comment by LeoT7508** [comment]
@jeannewalters 

I wouldn't want you to do extra work. I'll cover what I can make sense of now, if I have questions we can talk over it next week. 

Thanks.

**Comment by LeoT7508** [comment]
@xak 

Updated Popover:
https://zpl.io/b6yPnvN
