### ISSUE TITLE
Lib: Improve global nav

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#363]
- Responsiveness
- Independent controls and menus
- Semantic containers

See ...
https://experience.sap.com/fiori-design-web/shell-bar/

**Comment by jeannewalters** [comment]
@saadmhybris @xak There is already a visual for the mobile approach:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/screen/5ab953f947b69bd17a12f843

Here's the tablet version:
![image](https://user-images.githubusercontent.com/24274321/42832806-64d21598-89c0-11e8-8714-ab28074da9ec.png)

**Comment by xak** [comment]
The visuals do not show the tenant switcher, search nor the mega menu behaviors at small screens.

**Comment by xak** [comment]
No longer relevant due to new shellbar direction
