### ISSUE TITLE
Lib: Responsive layout improvements

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#366]
## Detailed description

> Describe in detail the issue you're having.

The mobile and tablet screens maintain the same padding as the desktop.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Improvements

> Is this issue related to a specific component?

Relates to `page`,`section` and `col` components.

> What did you expect to happen? What happened instead? What would you like to see changed?

Adjustments to fix obvious issues like extreme UI padding at small screens.

- Reduce small screen UI padding — https://zpl.io/VOBr7kP
  - Page containers
  - Sections containers
- Reduce small screen gutter width — https://zpl.io/aBOnGEm
  - Columns
  - Panel grid

|breakpoint|ui padding|gutter|
|--|--|--|
| default | 8px | 8px |
| xs (320) |  | |
| s (800) | 12px | 8px |
| m (1024)  | 16px | 12px |
| l (1440)  | 32px | 16px |
| xl (1580) | | |

## Additional information

Related to sap/fundamental#366

View any of the Demo Pages in mobile and tablet sizes.
https://sap.github.io/fundamental/demo-pages/index.html

See also ... 
https://zpl.io/2ZgvWNq
https://zpl.io/anKmrNY
https://zpl.io/aB5EO9p

**Comment by saadmhybris** [comment]
@xak 

none of the zeplin links in the description are working they all say "Screen not available anymore."

**Comment by xak** [comment]
@saadmhybris @LeoT7508 moved a bunch of stuff around. I'll have to find the new locations.

**Comment by xak** [comment]
@LeoT7508 Can you organize the screens needed for this? The most concerning problem is the extreme padding of the UI/APP components where we make no adjustments to small screens.

<img width="318" alt="screen shot 2018-07-10 at 11 02 34 atm" src="https://user-images.githubusercontent.com/424119/42522498-df8ee9a4-8430-11e8-9a1b-4f76f57161ec.png">
