### ISSUE TITLE
Design: Improve table component

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#367]
## States
- drag and drop 
- Freeze column(s)
- TH sorting indicators, asc and desc

See 
https://zpl.io/29D1Rpw
https://experience.sap.com/fiori-design-web/responsive-table/

I created a listing of possible table-elements:
https://wiki.hybris.com/pages/viewpage.action?pageId=387852527

**Comment by benjaminbetz** [comment]
I am quite unsure how the normal progressing with those tickets is.
I added some wireframes for the Column-Sorting and the "Fixed Column filter" here: https://hybrisproductdesign.invisionapp.com/share/3QMUWP4AZGS#/307815572_Table_Sorting_-_States

**Comment by LeoT7508** [comment]
@benjaminbetz 

This stuff looks good. I have to put some more work into drag & drop and then I'll add it here. 

@xak @saadmhybris 

You guys see any issues with what Ben put together?

**Comment by jeannewalters** [comment]
@benjaminbetz What is your suggested approach for tablet and mobile for tables? I didn't see that in invision.
Thanks

**Comment by xak** [comment]
For the sorting and freezing scope of this story the wires work. My only comments ...

1) The mouseover should apply to the entire column header not only the text.
2) Are the dropdown headers, e.g, "Order" and "Options", critical to understanding the functionality. Every label must be translated after all.

<img width="538" alt="screen shot 2018-07-18 at 10 22 23 ptm" src="https://user-images.githubusercontent.com/424119/42923560-e6cf6b3e-8ada-11e8-9af5-a4f7c4fe1872.png">

**Comment by benjaminbetz** [comment]
Hi Zack —

Is there a reason why you want to have that mouse-over using the full column? (Not that I am against it) Isn't it a strange usage (like in your example-image) to click on the column (near the right side) and having to move your mouse to  the dropdown on the left?

**Comment by benjaminbetz** [comment]
Hi Zack —

Here is the iteration of the sortable tables.
I am still thinking we could have 2 Versions of tables in the future — One that has just the basic "Ascending / Descending" sorting and the "more complex" one with an option do display more columns and fix those with a dropdown on the column-header.

Both versions as well as a clickable dummy for the "basic one" can be found here:

https://hybrisproductdesign.invisionapp.com/boards/XA3OWFSJ4CN/

**Comment by xak** [comment]
@LeoT7508 This is OK to proceed to visuals.
