### ISSUE TITLE
Specify alert placement and usage

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#368]
Need guidance on usage — floating, inline, etc. Where does an `alert` go on the page?

https://zpl.io/V1ZvrEB
https://ui5.sap.com/#/entity/sap.m.MessageToast
https://ui5.sap.com/#/entity/sap.m.NotificationListGroup

**Comment by LeoT7508** [comment]
@xak 

Notifications:
https://zpl.io/bLwgQ87

Alerts:
https://zpl.io/V186n6Q

Let me know if there should be any other scenarios covered.

**Comment by xak** [comment]
@LeoT7508 What happens when the page is scrolled? It will be difficult to enforce 66px (global nav height + offset) if scrolled to the top, otherwise 16px if the global nav is offscreen ... not to mentioned what if the global nav is 10px offscreen with 40px visible.

If the global nav is always fixed, it could easily be 66px all the time.

**Comment by LeoT7508** [comment]
@xak are u saying the alert should be independent of the global nav and  always sit 66px from the top of the page? Or should we allow it to sit over the global nav?

**Comment by xak** [comment]
I'm saying it will be easier to fixed it in relation to the top of the viewport not the global nav. The latter gets complicated when you consider the scrolling.

**Comment by LeoT7508** [comment]
@xak 

So I looked into it some more and  based off the design we have we might have to revisit the design of the alert itself. The rounded rectangle that holds the message now has opacity, in alot of cases this alert might overlap information so that wont work since the information becomes unreadable when overlapping. Ill have to change the design and  get approval from Global Design.

**Comment by LeoT7508** [comment]
@xak 

It looks like 20px from the top of the view port will work best. But we'll have to updated the design of the component itself for that to work.

**Comment by LeoT7508** [comment]
@xak 

Updated the Alerts design sheet:
https://zpl.io/bJK3o3n

**Comment by saadmhybris** [comment]
closing as we have all the info needed.
