### ISSUE TITLE
Improve messaging

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#369]
Need specific guidance around using various messaging components. Show examples of placement on the page. Where does each type appear? When should each be used?

- Modal — alert, dialog
- Alert 
- Notification
- Toast

See 
https://ui5.sap.com/#/entity/sap.m.Dialog
https://ui5.sap.com/#/entity/sap.m.MessageToast
https://ui5.sap.com/#/entity/sap.m.NotificationListGroup

## Questions
- What should appear in a global nav notifications center?
- When should an alert be used?
- When should a toast be used?
- Is there a difference between alert and toast?

**Comment by xak** [comment]
@jeannewalters I've changed this a larger UX story to provide guidance on application messaging.

**Comment by saadmhybris** [comment]
no longer relevant. this work will be covered in the DDB workstreams
