### ISSUE TITLE
Improve indicators

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#370]
## Adjust size
Badges and labels are large when used next to 14px base font size

<img width="288" alt="screen shot 2018-05-21 at 2 38 28 pm" src="https://user-images.githubusercontent.com/424119/40326381-a347e7e6-5d04-11e8-9b17-8f4fb4ce2d31.png">

## Addt'l states
Include any new variations for `badge` and `label`

<img width="160" alt="screen shot 2018-05-31 at 6 00 14 pm" src="https://user-images.githubusercontent.com/424119/40812632-7eba1b42-64fc-11e8-974d-57b8e85f1288.png">

## Rename tag to token
https://ui5.sap.com/#/entity/sap.m.Token

**Comment by LeoT7508** [comment]
@xak 

We have multiple options: 
We can only use the online status indicators in this area and use these for something else. 

![screen shot 2018-06-07 at 10 27 24 am](https://user-images.githubusercontent.com/28761982/41109822-8961a45c-6a3d-11e8-8323-77ef7a1253e6.png)


Or we would have to make them smaller, which means adding another typeface size, 10px. 

![screen shot 2018-06-07 at 10 27 30 am](https://user-images.githubusercontent.com/28761982/41109802-800112ee-6a3d-11e8-8f97-27d0829ff174.png)

**Comment by xak** [comment]
@LeoT7508 Why do we need 10px font size? The height of these should be 20px the same as the default line-height, the font size can stay 12px. The padding is what will change.

**Comment by LeoT7508** [comment]
@xak 

If we make the type 12px it looks very cramped in the rounded square, the type label still tends to look at bit odd at a bigger size thats what it would have to get smaller.

**Comment by xak** [comment]
@LeoT7508 So why not 11px?

**Comment by LeoT7508** [comment]
@xak 

Visually the smaller 10px looks better. It competes less with the other information, which was your initial concern. 

<img width="752" alt="screen shot 2018-06-19 at 9 57 01 am" src="https://user-images.githubusercontent.com/28761982/41605529-39420a0c-73a7-11e8-9159-a5b97a4b39c5.png">

**Comment by xak** [comment]
@LeoT7508 Go with 11px. It's not worth adding a whole new font size IMO.

**Comment by LeoT7508** [comment]
@xak 

Updated indicators here:
https://zpl.io/amBrj8m

For now we can leave the additional grey versions off.
