### ISSUE TITLE
Improve breadcrumb

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#371]
## Responsiveness
Long breadcrumbs should wrap or collapse to a menu. See https://ui5.sap.com/#/sample/sap.m.sample.Breadcrumbs/preview

## Proposal
`Home > [... v] > Previous page title`

At small screens, the middle items collapse into a menu.

Description:
- Add the ...
- set max width for screen sizes to avoid wrapping
- Update demo page breadcrumb  
- Support the last breadcrumb as the current page as well as the last breadcrumb as a link

Wire:
![image](https://user-images.githubusercontent.com/24274321/40788360-dd3efb22-64bd-11e8-990a-7147fdd9d1a9.png)

**Comment by LeoT7508** [comment]
@xak 

Updated bread crumb:
https://zpl.io/VkrL9Rg

**Comment by xak** [comment]
This is OK by me. @jeannewalters Thoughts?

**Comment by jeannewalters** [comment]
Looks good to me!
