### ISSUE TITLE
Revisit form spacing

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#409]
The margin below each `.fd-form__item` is 32px which feels very open. When a group of checkboxes stack they are very much spaced out the same as text inputs even though they are all grouped.

https://sap.github.io/fundamental/components/form.html

<img width="538" alt="screen shot 2018-05-24 at 3 02 31 pm" src="https://user-images.githubusercontent.com/424119/40510945-d6c0cbfe-5f63-11e8-953b-db5143ad889b.png">

The label next to the toggle seems far away as well.

<img width="325" alt="screen shot 2018-05-24 at 4 43 00 pm" src="https://user-images.githubusercontent.com/424119/40515242-aebbf954-5f71-11e8-8c65-dc3e5c827438.png">

Please provide a spec sheet showing how various form types should stack when grouped.

**Comment by LeoT7508** [comment]
@xak 

First pass at this is here:

https://zpl.io/bAv9eNP

**Comment by xak** [comment]
Works for me. 👍
