### ISSUE TITLE
Update number input group

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#410]
The number spinner feels a little out of sync with the new look and feel.

https://sap.github.io/fundamental/components/input-group.html#number-input

<img width="647" alt="screen shot 2018-05-24 at 3 21 18 pm" src="https://user-images.githubusercontent.com/424119/40511702-2fc82146-5f66-11e8-924c-f91f4b4a8c37.png">

**Comment by LeoT7508** [comment]
@xak @jeannewalters 

Number spinner updates:
https://zpl.io/V18onzQ

**Comment by saadmhybris** [comment]
this will be addressed in #464
