### ISSUE TITLE
Define sizing for modals

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#412]
Consider some variations on the modal since not all content will fit into the smallish size. Should we have a wider option and demonstrate more complex content?

https://openui5.hana.ondemand.com/#/sample/sap.m.sample.Dialog/preview

> Note: The current implementation has scrolling built in based on the height of the browser.

<img width="567" alt="screen shot 2018-05-24 at 4 11 00 pm" src="https://user-images.githubusercontent.com/424119/40513989-2a91f4fc-5f6d-11e8-8476-24e5c02a6471.png">

**Comment by LeoT7508** [comment]
@xak 

Added two different sizes for modals:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b16a5462f6a743c5aa6a0a4

**Comment by xak** [comment]
@LeoT7508 Can you address display on small screens? How much margin should be around the modal on a phone? This is how it looks now when the text overflows ...

<img width="343" alt="screen shot 2018-06-18 at 10 27 51 atm" src="https://user-images.githubusercontent.com/424119/41546084-54fe352e-72e2-11e8-9c4a-af18356e7eac.png">

And are we not putting. rule line above the actions? I saw that in a previous design.

**Comment by LeoT7508** [comment]
@xak 

Updates here:
https://zpl.io/V411BkX
