### ISSUE TITLE
Design: Improve pagination 

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#413]
## Responsiveness
At the smallest screen size, put total number of items under the paging links. Each should be centered in the container.

<img width="393" alt="screen shot 2018-05-24 at 4 20 55 pm" src="https://user-images.githubusercontent.com/424119/40514408-a1ef28d4-5f6e-11e8-97ff-f793191724f3.png">

## Left alignment
Place total items to the left of the container. We may include the "per page" count later.
https://zpl.io/bokyp0v

Improvements
- <s>Add ability to dropdown on <#> per page to allow users to change per page.</s>

**Comment by jeannewalters** [comment]
Improvement included:
![image](https://user-images.githubusercontent.com/24274321/42832082-17239378-89be-11e8-9f76-7b349a04d352.png)

**Comment by jeannewalters** [comment]
![image](https://user-images.githubusercontent.com/24274321/42832200-7cf3c8e4-89be-11e8-80a0-92de0feab5bc.png)

**Comment by jeannewalters** [comment]
@benjaminbetz Here is a responsive pagination approach.
