### ISSUE TITLE
Docs: Component Landing Page

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#415]
Update Component landing page:

- [ ] Replace Images

- [ ] Center images vertically and horizontally in tile space. 

- [ ] Decrease hover shadow by half. 

https://sap.github.io/fundamental/components/index.html

Many of the components on the left nav are missing from the main content.

**Comment by xak** [comment]
@LeoT7508 This should be a priority.

**Comment by LeoT7508** [comment]
Saad should have everything he needs. 

I sent him image assets last week.
