### ISSUE TITLE
Visuals: Create new Starter Page layouts

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#424]
Create a set of Starter Pages based off Jeanne's wires.

**Comment by LeoT7508** [comment]
@xak @saadmhybris @eboyer 

Starter Pages. 

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b0da7c5837a3a3fa7a9643c

**Comment by xak** [comment]
@LeoT7508 and @jeannewalters Do these represent actual use cases or are they kitchen sink pages? How would these pages fit into an application flow?
