### ISSUE TITLE
Define step-through flow pages

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#429]
Several applications use a right side panel to maintain placement in a numbered step-by-step flow to create a new object, asset, environment, etc.

This is applicable to an item that has multiple data requirements with a variety of formats at each step. 

![step through](https://user-images.githubusercontent.com/424119/40690977-56365ac0-636f-11e8-904f-e8aca068fa2e.png)

This has layout (fixed second column) and floorplan (object page flavor) impacts and introduces a new stacked step indicator composite component.

**Comment by jeannewalters** [comment]
@xak - this is already covered in the Progress Indicator ticket. see #136.
