### ISSUE TITLE
Improvement: Button Names

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#431]
Description:
- Update the names of buttons to reflect best practices and other libraries.
- Updated names of buttons per Remy are:
 
- **Primary button** (main CTA blue)
- **Outlined button** (white bg / blue border)
- **Transparent button** (blue / transparent)
- **Toolbar button**

Competitive analysis of other libraries @xak  :
![image](https://user-images.githubusercontent.com/24274321/40729315-1a5c9b1e-63fa-11e8-8576-f606c0c9b083.png)

**Comment by saadmhybris** [comment]
this will be addressed in #496
