### ISSUE TITLE
Remove outer margin from contextual-menu component

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#434]
There is some margin on attached to :first-of-type on the contextual menu that is too opinionated. We'll want to suggest that layout stuff like this will be used on wrapper containers and not components themselves.

(After this is removed, we'll have to go back and fix wherever it was intended to be used, with a new wrapper.)

Screenshot: http://cl.ly/rvUL

**Comment by xak** [comment]
@eboyer That was only added to the test page to push it over — it's in a `style` block — and not part of the actual component CSS. Without that bit of CSS the menu would be off the page.

<img width="288" alt="screen shot 2018-05-30 at 1 44 37 pm" src="https://user-images.githubusercontent.com/424119/40740904-a00f83a6-640f-11e8-843e-224c97c4c60d.png">
