### ISSUE TITLE
Lib: Implement table improvements

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#450]
### Designs 
Sortable colums - https://zpl.io/a8Kz1BX
Fixable and sortable columns - https://zpl.io/bWYWyP1

## States
- TH sorting indicators, asc and desc
- Freeze column(s)

## Responsiveness
- Scrollable content
- Small screen priorities 

>Dev notes - [frozen col example](https://stackoverflow.com/questions/1312236/how-do-i-create-an-html-table-with-fixed-frozen-left-column-and-scrollable-body)

See 
https://zpl.io/29D1Rpw
https://experience.sap.com/fiori-design-web/responsive-table/

**Comment by eboyer** [comment]
@xak ~ Sorry if I missed an update along the way. Do we happen to be unblocked on this yet? Do we want to push to next release or take an initial stab at it and iterate on it when more updates come through?

**Comment by eboyer** [comment]
@xak ~ Found the update here! https://github.com/SAP/fundamental/issues/367

**Comment by xak** [comment]
See https://material.angular.io/components/table/overview. The NGX lib will use the [Material CDK](https://material.angular.io/cdk/table/overview) to implement.

**Comment by saadmhybris** [comment]
@eboyer - just an FYI that I have updated the ticket description with design links and this ticket is unblocked now.
