### ISSUE TITLE
Visuals: Design search box input type

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#457]
## Goal: Provide a standalone `search` component with built-in behaviors

**Variations**
- Standard search box with icon button (open by default)
- Collapsed search box (opens when icon button is clicked)
- Auto-complete dropdown menu (optional)

Could be used in a top nav, panel filter bar, etc.

Wire:
![image](https://user-images.githubusercontent.com/24274321/41422695-797ea69a-6fc7-11e8-8dd0-659127baaa48.png)

**Comment by LeoT7508** [comment]
@xak @jeannewalters 

What we have so far:
https://zpl.io/VDO9WJW

**Comment by jeannewalters** [comment]
@saadmhybris Leo mentioned there were some technical concerns about the search box in the header. Can you share those here? 
Thanks

**Comment by saadmhybris** [comment]
@jeannewalters - the main concern i have was how the search bar.

- When expanded, the search bar covers the contextual menu. This is a case pone component obstructing the other 
- There is no intutative to close he search bar and get out of the expanded state
- We don't really have guidelines on how the search button should work. Right now it toggles the search field, where as a common usage of a search icon is to trigger the search. 

<img width="210" alt="screen shot 2018-06-08 at 12 58 29 pm" src="https://user-images.githubusercontent.com/15215400/41173221-b4c62cc4-6b1b-11e8-96cd-4453465f9e29.png">

<img width="237" alt="screen shot 2018-06-08 at 12 56 56 pm" src="https://user-images.githubusercontent.com/15215400/41173188-9e90fb32-6b1b-11e8-881f-e999bc24a95e.png">

**Comment by jeannewalters** [comment]
@saadmhybris Please take a look at the wires and see if you have any concerns or questions.
Moving to @LeoT7508.

**Comment by saadmhybris** [comment]
@jeannewalters did we address the issues in my previous comments? also what's the latest link to the wires?

**Comment by LeoT7508** [comment]
@saadmhybris @jeannewalters 

Search is updated here:
https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b295bf122bf0153536db12a

**Comment by LeoT7508** [comment]
@saadmhybris @jeannewalters 

Updated design sheet here:

https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b295bf122bf0153536db12a

**Comment by LeoT7508** [comment]
@saadmhybris @xak @jeannewalters 

Updated design sheet:

https://app.zeplin.io/project/5b23c972a7bb309e08b88e95/dashboard?seid=5b295bf122bf0153536db12a

**Comment by saadmhybris** [comment]
design is complete
