### ISSUE TITLE
Site: Feedbacks for Homepage

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#46]
Hey Saad here's the specs for issues I found on the current site. Some of them are repeated but I just don't want to miss anything. @saadmhybris 

- [x] 1. Sidenav: width
- [x] 2. Sidenav: search bar bottom margin
- [x] 3. Hero image: Button margin top/bottom
- [ ] 4. Hero image: the Version:v1.0.0-BETA has a background
- [x] 5. Getting started: height of the section
- [x] 6. Getting started: the background images are a bit off
- [x] 7. Designer: size of the “DESIGNER” and “developers”image
- [x] 8. Designer: spacing between the image and “START DESIGNING”
- [x] 9. “START DEVELOPING” should be on the developer section
- [x] 10. UI Guidelines: top and bottom padding of the text and image div
- [x] 11. UI Guidelines: Margin between title and subtitle
- [x] 12. UI Guidelines: The image for spacing has a white grid background. The image needs to be update
- [x] 13. Support: top and bottom padding of the text and image div
- [x] 14. Support: the two icons need to be switched.
- [x] 15. Support: Bottom margin of the icons

![feedback-homepage](https://user-images.githubusercontent.com/32305332/34730867-3c64706c-f526-11e7-9946-62f6176e95de.png)

**Comment by joseegm** [comment]
@jinjiahuangsap
Can you please check that's the items on the list are fixed?
You can see the deployed version at https://sap.github.io/fundamental/

**Comment by saadmhybris** [comment]
these changes are already done and live.
