### ISSUE TITLE
Project: Add Github templates to ensure proper documentation

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#468]
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

- [x] Add Pull request tepmplate (PULL_REQUEST_TEMPLATE.md)
- [x] Add issue tepmplate (ISSUE_TEMPLATE.md)
- [x] Make sure both filesa re added to .npmignore

**Comment by saadmhybris** [comment]
Pull request tepmplate (PULL_REQUEST_TEMPLATE.md) 

Pull request name - #000 feature-name-or-description

# #123 

## List of components or changes
-  link 1
-  link 2
-  link 3

## List of related design sheets
-  link 1
-  link 2
-  link 3

## Notes for the reviewer
