### ISSUE TITLE
BUG: Contextual Menu Icon

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#497]
For the contextual menu icon lets make the change from Glyph 507 to Glyph 497. 

Glyph 507 will be used as the handle for drag and drop.

**Comment by xak** [comment]
@LeoT7508 Is this still an issue? Can you show or link to the icons?

**Comment by xak** [comment]
@LeoT7508 Is this what you mean #493?

**Comment by LeoT7508** [comment]
> @LeoT7508 Is this what you mean #493?

Yes, this looks like what this is about. I think we've already been using the horizontal three dots icon.
