### ISSUE TITLE
BUG: Form

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#501]
## Wait until #524 is complete otherwise the work will be done twice.

Fields:
- [x] Fields should have a white BG color included. 
- [x] Drop down should have a white bg color 
- [x] Field box color is updated. 
- [x] Field label text color is updated. 
- [x] Field placeholder text style and color is update.
- [x] Required fields no longer need to the field label to be bolded. 
- [x] State colors are updated. 

Select Box:
- [x] Idle states are updated. 
- [x] Chevron arrow color needs to be updated. 

Radio Buttons & Check Boxes:
- [x] Shape outlines are updated.
- [x] Active states are updated. 

Form Message & Help:
-  [x] Icons need to be updated to the SAP Icon font. 

All details can be found in the updated design sheet here:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b195719c295194d78afc36d

here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b1957268c9186ad2f22a94a

& here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5ac4931f0bca10ad7ebc07ca

**Comment by saadmhybris** [comment]
@xak any eta on this ticket?

**Comment by xak** [comment]
@saadmhybris Working on it.
