### ISSUE TITLE
BUG: Modal

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#502]
- <s>There shouldn't be a line below the content and above the buttons in a Modal. </S>
- The "X" close button should be blue since its an interactive element. 

Check design sheet here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b16a5462f6a743c5aa6a0a4

**Comment by xak** [comment]
@LeoT7508 The bottom rule line on the modal is nice when you have overflow content.

<img width="567" alt="screen shot 2018-05-24 at 4 11 00 pm" src="https://user-images.githubusercontent.com/424119/40513989-2a91f4fc-5f6d-11e8-8476-24e5c02a6471.png">

You have also introduced the divider line in the popover to separate the actions which is a very similar pattern.

What is the rationale for not including the rule line?

**Comment by LeoT7508** [comment]
@xak 

No rationale, I just used what came down from Global Design. We can make this addition no problem.
