### ISSUE TITLE
BUG: Toggle

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#504]
- [x] Update the on state with updated color
- [x] Updated the off state circle shape outline & fill color. 
- [ ] Addition of the second instance of a toggle with informative labeling. 
- [x] Revisit disabled state

Updated design sheets can be found here:

https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5ac4931f0bca10ad7ebc07ca

**Comment by saadmhybris** [comment]
@LeoT7508 can you please update the design sheet with the `hsl` adjustments?

**Comment by saadmhybris** [comment]
Moving this to 1.2.0 milestone as the color vars for this component is shared across the board with other form components. We'll have to make sure to allow enough time to test rest of the components affected by this change.

**Comment by saadmhybris** [comment]
Related to #524.

**Comment by saadmhybris** [comment]
create a seperate ticket for lables and legends

**Comment by LeoT7508** [comment]
@saadmhybris 

Im not sure what you're asking for here.

**Comment by saadmhybris** [comment]
that's a note for me. sorry for the confusion.

**Comment by saadmhybris** [comment]
@LeoT7508 We will have to defer the "Addition of the second instance of a toggle with informative labeling." item for later. I discussed this with the dev team and although it seems simple, it involves changes to a whole bunch of related components such as checkboxes, radios, and other form elements.
