### ISSUE TITLE
Visuals: Combobox

### ISSUE THREAD

**Issue by Jagoooo** [SAP/fundamental#520]
## Wires for Combo Box

Here are my wires for the Combo box with a number of different scenarios: 
Tagging, Single select, multiple select and select or create.

https://29u4kz.axshare.com/

**Comment by LeoT7508** [comment]
@Jagoooo 

Design sheet version 2 is here:

https://zpl.io/b6M7n3j

**Comment by Jagoooo** [comment]
Here is the wires for the Combo-Box

https://29u4kz.axshare.com/#g=1&p=combo-box
