### ISSUE TITLE
Establish browser support standards

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#521]
## Detailed description

> Describe in detail the issue you're having.

There is no documentation to verify which browsers are supported.

> Is this a feature request (new component, new icon), a bug, or a general issue?

New

> Is this issue related to a specific component?

No

## Additional information

The library should have unambiguous support standards. A wiki page here would suffice.

**Comment by SAPMontreal** [comment]
I guess if we aim C4 then we should fall under their PAM browser support

**Comment by SAPMontreal** [comment]
example of the PAM browser support like ui5 https://apps.support.sap.com/sap(bD1lbiZjPTAwMQ==)/support/pam/pam.html?smpsrv=https%3a%2f%2fwebsmp102.sap-ag.de#ts=7&s=SAP%20NetWeaver%207.51&o=most_viewed%7Cdesc&st=l&rpp=20&page=1&pvnr=73555000100900000895&pt=t%7CWBRPFM&ainstnr=73555000104900002472&fclfilter=S%7CUSER%20INTERFACE%20TECHNOLOGY%207.52
