### ISSUE TITLE
Lib: Color Palette Update & Addition

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#524]
Update 2 colors & add 2 new color

1. Update colors:

- [x] Update Status 1 to #118843

- [x] Update Status 2 to #F59518

2. Add additional Neutral Color:

Please add a 4th Neutral color to the Neutral colors. 

- [x] Add "Neutral 4" #ceced0

This applies to the following components:

- [x] Idle Check Box Outline

- [x] Idle Radio Button Outline

- [x] Idle Field Outline

**Comment by xak** [comment]
@LeoT7508 My recommendation is to remove `text-inverse` completely and make a 4th `text` shade for the inverse, i.e., white, color. We only use `text-inverse-1`.
