### ISSUE TITLE
Design: Responsive layout guidelines

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#539]
Related to sap/fundamental#366

## Detailed description

> Describe in detail the issue you're having.

The mobile and tablet screens maintain the same padding as the desktop. There are no specs for these layouts.

> Is this a feature request (new component, new icon), a bug, or a general issue?

Improvements

> Is this issue related to a specific component?

Relates to `page`,`section` and `col` components.

> What did you expect to happen? What happened instead? What would you like to see changed?

The padding should be appropriate for the screen size. 40px on each side on a screen that is 320px wide takes up a lot of valuable space.

## If BUG, steps to reproduce the issue

View any of the Demo Pages in mobile and tablet sizes.
https://sap.github.io/fundamental/demo-pages/index.html

## Additional information

<img width="318" alt="screen shot 2018-07-10 at 11 02 34 atm" src="https://user-images.githubusercontent.com/424119/42522814-b8ab85b2-8431-11e8-8a6a-494bf3d3fb83.png">

<img width="318" alt="screen shot 2018-07-10 at 11 02 15 atm" src="https://user-images.githubusercontent.com/424119/42522816-baba0702-8431-11e8-8152-ee86e8a14405.png">

**Comment by LeoT7508** [comment]
@xak 

https://app.zeplin.io/project/5b169f030f5e5e5d1255fe46/dashboard?seid=5b16a1615250bbe341c29e23

**Comment by jeannewalters** [comment]
@Jagoooo Jago is working on the Demo Pages to wire out the tablet and mobile versions and note what is not working.

**Comment by LeoT7508** [comment]
I will wait till this task is in the Visuals lane to begin.

**Comment by xak** [comment]
We have what we need in #366
