### ISSUE TITLE
Docs: Update Global Navigation page with required scripts to build menu actions

### ISSUE THREAD

**Issue by lacerdaeduardo** [SAP/fundamental#545]
In the documentation [global-navigation](https://sap.github.io/fundamental/layouts/global-navigation.html) there's no JS code regarding the menu actions. 
I inspected the site using Chrome's developer tools and notice that there's a script called "customscripts.js". After I added that to my project, the menu actions (dropdown, search, etc) started working.

Steps to reproduce:

1. Setup a project with fundamental ui
2. Create a page with the html available on [global-navigation](https://sap.github.io/fundamental/layouts/global-navigation.html) page
3. Click on menu and notice that nothing happens.
4. Add the following content to your project and reference it on the global-navigation page: [customscripts.js](https://sap.github.io/fundamental/js/customscripts.js)

**Comment by lacerdaeduardo** [comment]
There's also an package not mentioned anywhere on the customscripts. I guess this is anchor-js.

**Comment by saad-mo** [comment]
global-navigation is now deprecated
