### ISSUE TITLE
Design: Responsive global header

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#554]
Support a global header for not only desktop but tablet and mobile. Include the dropdowns to show where the tooling goes in smaller screen sizes.  
Demo pages and global nav component in the lib website should show mobile, tablet and desktop.

**Comment by jeannewalters** [comment]
Wire:
![image](https://user-images.githubusercontent.com/24274321/42884994-d14ac0d2-8a6d-11e8-88d5-9685f78ef3df.png)

**Comment by jeannewalters** [comment]
@Jagoooo - here are some examples for the responsive demo pages as well.

**Comment by LeoT7508** [comment]
@jeannewalters 

The example you show above doesn't make sense for the desktop global nav menu expanded. You are showing Notifications & Settings in the expanded menu, but those are already available in that same line of options. I'll include User Name & Log Out in the menu.

**Comment by jeannewalters** [comment]
@Jagoooo Zack added a few comments above. @xak Manu showed me the latest site approach for SAP this morning and everything moved into a left hamburger menu other than the logo and application name.  I don't think we should spend too much time on determining all the options since we will need to revise the global header in the near future to encompass the new approach that Irla showed last week from Llamingo.  I suggest either expose 1 or 2 of the most important tools per application in mobile (let the application team determine this) or hide everything under a menu icon that would include the dropdowns. @LeoT7508 Sorry Leo - I didn't want to write this outside of the ticket since this might be a longer conversation. @Jagoooo is working on the revised version and I will post the link to the site that Manu showed me earlier.  We can discuss more in the experience call tomorrow.

**Comment by xak** [comment]
Do we have any use cases now that actually include search, settings or notifications? Can we solve for the cases we have now without adapting to an overflow menu? We can start simple to avoid duplicating the content in an adaptive menu. Maybe transform the tenant switcher to an icon button so it can retain the same location.

Also, note that the shell has been prioritized by SAP Design so we will soon have additional input toward the Fiori 3.0 recommendation.

**Comment by xak** [comment]
The new shellbar addresses these issues.
