### ISSUE TITLE
Develop: Responsive alerts 

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#564]
The following wire displays the responsive approach for the alerts.

![image](https://user-images.githubusercontent.com/24274321/43022322-e60f323c-8c34-11e8-8f0d-c9d716d90d01.png)

These need to be added to the library too.

**Comment by xak** [comment]
@jeannewalters The alerts already respond to the width of the page. What more is needed here?

<img width="298" alt="screen shot 2018-07-24 at 9 06 40 atm" src="https://user-images.githubusercontent.com/424119/43143714-0647e2ee-8f21-11e8-98dc-18701e44a30f.png">

**Comment by xak** [comment]
@jeannewalters The doc site isn't responsive so ti's hard to test on that page. See https://sap.github.io/fundamental/demo-pages/alert-overlay-demo-page.html

**Comment by xak** [comment]
This should be pretty much in place so let's verify it.
