### ISSUE TITLE
Develop:  Responsive Action Bar

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#565]
The following are the wires to support a responsive approach for the action bar.
![image](https://user-images.githubusercontent.com/24274321/43082052-14f7c676-8e61-11e8-8309-720981a95cfd.png)

Within the library site, Mobile version is as wide as desktop. A suggestion would be to either have the components work responsively in the library (as the browser size is updated like Deno is doing in the Angular lib or appear the size of the screen size they support.

**Comment by saadmhybris** [comment]
this is already done
