### ISSUE TITLE
Visual: Notifications

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#566]
The Zeplin FUND UI has MDS Notifications in the Notifications, Alerts... area. Notifications and Alerts seem to be the same thing. Teams have asked why we have both of them in Zeplin. MDS Notifications look very nice and clean.

**Comment by saadmhybris** [comment]
We inherited the designs for notifications from MDS, but this is not currently slated for development as we still need to sort out the guidelines on where and how these works.  

There are some notification and right panel related tickets in the backlog that we can pick up and discuss if there is interest/need from teams. 

#369, #226

**Comment by xak** [comment]
@jeannewalters What is the desired outcome of this story?

**Comment by jeannewalters** [comment]
@xak It's confusing. In Zeplin, there are notifications and alerts and in the lib there are only alerts. They seem to be the same thing - just a different way to display it. I am asking for clarification - and with clarification, to update either Zeplin or the library.

**Comment by xak** [comment]
@jeannewalters I agree. #369 was created to address this.

@LeoT7508 Please remove designs from the FDUI Components Zeplin project that have not been implemented to avoid confusion.

**Comment by xak** [comment]
Closing as a duplicate.
