### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by noetejaxun** [SAP/fundamental#568]
## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Fundamental UI are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

## If BUG, steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## If FEATURE REQUEST, describe the need

* Component name
* Use case
* Expected behavior
* Examples for reference

## Additional information

* Screenshots or code
* Notes

**Comment by saadmhybris** [comment]
@noetejaxun please add relevant detail to this issue. otherwise, it will be closed.

**Comment by xak** [comment]
Closing for lack of information. @noetejaxun Please open a new issue describing your request.
