### ISSUE TITLE
[Lib] Form Input - disabled and readonly states

### ISSUE THREAD

**Issue by ivijan** [SAP/fundamental#587]
## Issue
* Form Input with disabled and readonly state has poor visibility
![screen shot 2018-07-26 at 15 15 01](https://user-images.githubusercontent.com/13087038/43264745-36690710-90e7-11e8-969d-e8dd49840afb.png)

-- with combination of gray-ish bg-color and no borders, element is melting with the background

Some examples:

![screen shot 2018-07-26 at 15 21 00](https://user-images.githubusercontent.com/13087038/43264903-9e396718-90e7-11e8-90f2-a1233e026834.png)
![screen shot 2018-07-26 at 15 24 04](https://user-images.githubusercontent.com/13087038/43265069-0ddc6840-90e8-11e8-8bea-d9ea0a6ef689.png)
![screen shot 2018-07-26 at 15 24 17](https://user-images.githubusercontent.com/13087038/43265070-0e09b106-90e8-11e8-9e17-62034bec6052.png)

## Proposal
* Keep border from disabled state when also readonly state is applied:

## Additional information
> Browser and enviroment: Chrome v67.x on Mac High Sierra v10.x

> Version of the Fundamental UI: **v1.0.0**

> Front-end framework: **Angular 6**

**Comment by saadmhybris** [comment]
@LeoT7508 any thought here?

**Comment by LeoT7508** [comment]
@saadmhybris @ivijan 

Seems these input fields were implemented incorrectly. There shouldn't be a grey background. The Input design sheet can be found here:

https://zpl.io/2y7WKYL

**Comment by ivijan** [comment]
Hi @saadmhybris @LeoT7508,
maybe you misunderstood me! I was talking about the case when input field has both "disabled" and "readonly" attributes. 
In that case CSS properties from both states are being applied, and we end up with gray background and missing borders... looks quite weird in that case.

**Comment by saadmhybris** [comment]
@ivijan - thanks I did miss the part where you are saying the combination 'disabled' and 'read-only' states on the input. 

I'll let @LeoT7508 handle this and we'd be happy to implement whatever color changes he suggests. :)

**Comment by ivijan** [comment]
Hi @saadmhybris , @LeoT7508 , today i had to take care of this topic in our app, so I came up with possible solution, using existing fui components.

Maybe we can implement this to fundamental-ui?

## proposal 
// form input disabled & readonly fix
$fd-elements-inputs--text: "input[type=text]",
"input[type=password]",
"input[type=email]",
"input[type=url]",
"input[type=search]",
"input[type=tel]",
"input[type=number]",
"input[type=date]";

@mixin fd-input-fix {
  &:disabled,
  &[aria-disabled="true"],
  &.is-disabled {
    &[readonly],
    &.is-readonly {
      border-width: 1px;
      border-radius: $fd-border-radius;
    }
  }
}

#{$fd-elements-inputs--text} {
  @include fd-input-fix;
}

![screen shot 2018-09-12 at 14 04 41](https://user-images.githubusercontent.com/13087038/45423839-d2a14700-b694-11e8-912a-69ec3d3e62fb.png)


## before
![screen shot 2018-09-12 at 14 00 53](https://user-images.githubusercontent.com/13087038/45423683-60306700-b694-11e8-81af-f036fbedca3b.png)

## after
![screen shot 2018-09-12 at 13 59 40](https://user-images.githubusercontent.com/13087038/45423694-658db180-b694-11e8-9cf8-63b366d1b58a.png)

**Comment by LeoT7508** [comment]
@ivijan @saadmhybris 

The after doesn't follow the style for disabled. It should be an underline only.

**Comment by benjaminbetz** [comment]
Hi @LeoT7508 

The ticket was about the combination of the Read-Only & Disabled state. Is your solution/proposal to use the **before** image @ivijan provided (with the line and the squared grey BG), or something else (for example the **after**  version)

The reason (as far as I understand it) is that in some cases the Read-Only + Disabled-state is used in our applications to show the user that a field is **disabled** if we would use the normal **disabled field** the backend wouldn't save that particular field. 

@ivijan Correct me if I am wrong with that. As far as I know this issue came up with our "Multi-Language inputs" were one field is "Normal" in one Language-State and "Disabled" in a different language.

**Comment by ivijan** [comment]
@benjaminbetz explained it correctly! 
To sum up, we have to use readonly HTML attribute, because angular would ignore the field if it would have disabled attribute. The field in the form would not be submitted to backend.

But... the field has to look like disabled, so we append existing FUI class .is-disabled on the input.
In that case, we get mix of FUI readonly and disabled CSS. So we propose CSS which would cover that use-case.

**Comment by LeoT7508** [comment]
If the case is that you need to represent both states at once then the "before" example demonstrates that more accurately. Our disabled state is has a grey background for the field, and the read only state has an underline online only. So those 2 combined would be a line with a grey background like what you have.

**Comment by eboyer** [comment]
Closing this issue. After some research and checking back in on what the design represents currently, a disabled and readonly input combined should: have a `Neutral 2` background (from disabled) along with an underline (from readonly).
