### ISSUE TITLE
Popover doesn't have styling for disabled state

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental#593]
## Detailed description

> Describe in detail the issue you're having.
The popover component doesn't have disabled state and corresponding styling.

> Is this a feature request (new component, new icon), a bug, or a general issue?
A bug

> Is this issue related to a specific component?
Popover and Dropdown

> What version of the Fundamental UI are you using?
v 1.1.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Fundamental-NGX

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular 6

**Comment by saad-mo** [comment]
stale
