### ISSUE TITLE
Component: Info Box

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#60]
### Description

The Info Box Component is used to Display Static Information and can contain simple actions that can be performed over the displayed information.

### Features
- **1**. The Info Box is a standalone component that can be used inside panels, sections, grids or cards.
- **2**. The information displayed can be divided by rows
- **3**. The information inside the row can contain two main parts
  - **3.1**. The title of the row, which describe the information displayed on the row
     - **3.1.1**. The tile can display very simple information like labels and icons
  - **3.2**. The content which is were the actual information is displayed
     - **3.2.1**. The content can display more complex information and have some formatting for it
     - **3.2.2**. The content area can display few actions that can be performed on the displayed information
  - **3.3**. The row can only contain the content, without a title part (3.1)
- **4**. The information inside a row can be displayed in an horizontal or vertical layout.
  - **4.1**. Horizontal: the title (3.1) is displayed above the content (3.2)
Action
The user can edit both on a high level section or per line.
Include inline field for edit per line.
Edit high level section in a modal/ side panel depending on application.

### Tasks
- [x] Design wireframes describing the features described above
  https://6umx4d.axshare.com/#g=1&p=info_component_v_1_d
  https://6umx4d.axshare.com/#g=1&p=info_component_v_1_m

- [ ] Visuals

### Some use cases/Prior art
![screen shot 2018-01-29 at 12 41 03](https://user-images.githubusercontent.com/22662903/35975965-da9c199a-0cde-11e8-9707-f54c27e4f0ca.png)
![screen shot 2018-01-29 at 12 41 16](https://user-images.githubusercontent.com/22662903/35975966-dab9582a-0cde-11e8-8331-60e94a7a235d.png)
![screen shot 2018-01-29 at 12 41 31](https://user-images.githubusercontent.com/22662903/35975967-dad48636-0cde-11e8-99c8-6dacc17161e3.png)
![screen shot 2018-01-29 at 12 41 50](https://user-images.githubusercontent.com/22662903/35975968-daf0b7f2-0cde-11e8-94b3-71c814bb839a.png)
<img width="492" alt="screen shot 2018-01-29 at 12 43 34" src="https://user-images.githubusercontent.com/22662903/35975969-db23d010-0cde-11e8-85da-630ac4f201a1.png">

**Comment by gcho1023** [comment]
are these info components editable? or is it displaying only details? does this relate to fields?

**Comment by joseegm** [comment]
Feature 3.2.2 describe it.

Regarding the input fields, no, there should not be any input fields on this components. To keep it simple.

**Comment by gcho1023** [comment]
https://6umx4d.axshare.com/#g=1&p=info_component

**Comment by joseegm** [comment]
@gcho1023 
Can you update the wires with the actions, as bespoke on the meeting?

**Comment by gcho1023** [comment]
https://6umx4d.axshare.com/#g=1&p=info_component_v_1_d 
https://6umx4d.axshare.com/#g=1&p=info_component_v_1_m

the wires has been updated

**Comment by joseegm** [comment]
@LeoT7508 
Wires are in and updated, this is ready for the visuals.

**Comment by LeoT7508** [comment]
@joseegm @jinjiahuangsap 

We will start this next week.

**Comment by xak** [comment]
@LeoT7508 Do we need this? It looks like a `panel` with 2 columns.

**Comment by saadmhybris** [comment]
no longer relevant
