### ISSUE TITLE
Panel body shouldn't define padding

### ISSUE THREAD

**Issue by pixx3l** [SAP/fundamental#602]
## Detailed description

> Describe in detail the issue you're having.

Currently panel body automatically sets 16/20 padding on the inner content. This prevents inner items from being flush with the edge. For example, if showing a grid of 5 items inside, say a numerical statistic, the padding would be applied inside of the grid item. Since the content section has it's own the extra spacing throws off the visuals.

> Is this a feature request (new component, new icon), a bug, or a general issue?

general issue

> Is this issue related to a specific component?

Panel

> What did you expect to happen? What happened instead? What would you like to see changed?

Padding should not be automatic, and instead defined by the components that appear inside of the panel content area

> What browser are you working in?

Chrome (consistent for all)

> What version of the Fundamental UI are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

CS Reporting. Not pressing, currently using an internal override

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

Angular

## Additional information
<img width="467" alt="screen shot 2018-08-03 at 2 46 39 pm" src="https://user-images.githubusercontent.com/34278658/43660131-0e7c8ca4-972c-11e8-90dd-3c7abe1f5a94.png">

**Comment by saadmhybris** [comment]
@pixx3l This change of moving padding from the panel body to the component has a wider impact on how we approached component design and layout. Given the fact that other teams are already using FDUI and do not seem to have this issue, it's hard for us to make this a permanent change in the library. We do have design system utilities that you could use, but they pretty much do the same thing as your local overrides. https://sap.github.io/fundamental/guides/design-system-utilities.html#margin-and-padding

If you are still not satisfied, pls reopen and comment on the issue :)
