### ISSUE TITLE
Fundamental Icons

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#63]
### Problems
1. The current fundamental UI icons have a different style: line height, some rounder corners or squared.
2. The current library have some icons that are not used directly by our components

### Alternatives
1. We clean -remove the unused icons- and change the Style of the current library
  **Pros**: keep the library simple and with no dependencies
  **Contra**: no
2. Use an Fiori Icon Library
  **Pro**: gain a lot more icons with a coherent style
  **Contra**: introduce a dependency. no much information if we can distribute the icon library with our own.
3. Use an external Icon Library
  **Pro**: gain a lot more icons with a coherent style
  **Contra**: introduce a dependency. unknown if we can distribute it.

**Comment by joseegm** [comment]
@LeoT7508 
Can you please chime in your opinion on the above points?

@saadmhybris 
Can you please investigate without spending much time if we can declare the Fiori Icon Library as a package dependency? 

@xak 
You have some ideas on this respect as well that I guess are in the points above, please review.

**Comment by joseegm** [comment]
I think we can go for the first alternative. Removing the icons we are not using in our components. That will reduce the effort to fix the Style on the remaining ones.

Don't like the idea of introducing a dependency

**Comment by LeoT7508** [comment]
@joseegm @xak 

I'm open to either decision I know the SAP icon font needs to be investigated some before we make a final decision.

**Comment by joseegm** [comment]
@LeoT7508 
Yes the investigation has 2 points:
1. If the fiori icons fits the Fundamental Style - @LeoT7508 can answer that
2. If the fiori icons can easily be included in the library as a dependency - @saadmhybris can investigate a little and answer that as planned on the second comment.

**Comment by joseegm** [comment]
As per the meeting we have only small improvements to the visual style of the icons are going to be done now and investigation to move the icon usage to a different method. Both will be treated in respective issues.
