### ISSUE TITLE
Design: Responsive Tabs

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#637]
This should be handled just like it's documented in MDS_Tabs in Zeplin with the overflow icon appearing when space is limited based on screen size with a popover containing remaining tabs.  This follows the top nav approach being considered by the design decision board too.

**Comment by jeannewalters** [comment]
@saadmhybris @LeoT7508 Do you need a wire based on the comments above? Seems like the approach is already there in Zeplin.

**Comment by LeoT7508** [comment]
Design sheet: https://zpl.io/a8Wz66g

@jeannewalters who was this ticket meant for?

**Comment by benjaminbetz** [comment]
Hi — 

I created the following 3 Versions for mobile Tabs: https://qntqrn.axshare.com/#g=1&p=tabs_-_v1
The Problem I tried to solve was:

"How do we show Mobile-Tabs and also differentiate between Tabs from the Main-Navigation of the App, Tabs from the Page the user is working on and Panel/Card-Tabs".

![tabs_-_v1](https://user-images.githubusercontent.com/39957237/46346011-e7934980-c646-11e8-9464-c0016d42b81b.png)

In Version 1 I remodelled the Main-Navigation-Tabs to a Dropdown/Popover. The Page-Tabs move offscreen if there are to many. If a user swipes a panel to the left or clicks the Page-Tab, those change/are activated.

![tabs_-_v2](https://user-images.githubusercontent.com/39957237/46346012-e7934980-c646-11e8-85fa-1bcbc289d7d7.png)

In Version 2 I tried to combine The Action Bar with a Hamburger-Icon that slides-in the Main-Nav.

![tabs_-_v3](https://user-images.githubusercontent.com/39957237/46346014-e7934980-c646-11e8-85e5-eb7e98ba2e1a.png)

In Version 3 I tried to add tabs under the Shell-Bar with a different design to differentiate between Main-Navigation and Page-Navigation.

**Comment by LeoT7508** [comment]
@benjaminbetz 

These looks great. Did you share this with GD? They will be working on this at some point. Would be good to get their input.

**Comment by benjaminbetz** [comment]
@LeoT7508 

Hey, no I have not. Who would be the person I should/could write to? :)

**Comment by LeoT7508** [comment]
Duplicate tickets, reference #940.

Closing.
