### ISSUE TITLE
Design: Responsive Inline Help 

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#638]
Set width to 320 pixels. 
Click on icon in mobile and tablet. Always position below. Tap icon to close or outside help area.
Add position of box below in library.

**Comment by Jagoooo** [comment]
Width should truncate to accommodate for text. 
Mobile - Max width 300px Leaving 10px each side

Tablet and desktop fixing to 400px because they look silly if they span across the screen.

**Comment by Jagoooo** [comment]
After talking to Saad we have agreed that the scrolling is a bad idea. This mechanism currently works as a roll over. If they wanted a large amount of info in there they should use a pop-over and then they can have scroll. @saadmhybris
