### ISSUE TITLE
Design Date picker

### ISSUE THREAD

**Issue by joseegm** [SAP/fundamental#64]
### Description
New component for Fundamental UI that allows to select a date.

### Features
- **1**. The component can be used inside a form containing other inputs components
- **2**. The component interaction should display a whole month with weekly rows
  - **2.1**.  The weekdays should be visible
  - **2.3**. The year should be visible
- **3**. The user should be able to navigate forwards backwards, one month at a time, inside de component
- **4**. The component should have a collapsed/standard state and a expanded state
  - **4.1**. The collapsed state display only the date in a short format. eg: 10.10.2010
    - **4.1.1**. The collapsed state should display a trigger for the interaction to display the elements described in **2.**
    - **4.2**. The expanded state should always show the elements from **2**.
      - **4.2.1**. The expanded stated should display the selected date clearly and highlight the current selected day

**Comment by jeannewalters** [comment]
@joseegm what about the Time part of the component? Will that be a separate component or should we have Date Picker and Date Time Picker?

**Comment by joseegm** [comment]
@jeannewalters 
The time input can be solved now with a single input input field and some formatting. Let’s start simple with this one.

**Comment by jeannewalters** [comment]
Here is the annotated wire for the date picker.

![image](https://user-images.githubusercontent.com/24274321/36323490-744585e2-1327-11e8-9332-e26e9e368f7b.png)

**Comment by joseegm** [comment]
@jeannewalters 
Awesome, all the flows are clear and the interaction as well. Great job. 
Sidenote: the Axure prototype doesn't display the icons. 
<img width="1084" alt="screen shot 2018-02-19 at 08 52 51" src="https://user-images.githubusercontent.com/22662903/36367450-fb2d36a4-1552-11e8-8c72-3eafcdd04ac1.png">
No biggie but you may want to take a look at it.

@LeoT7508 
All is there for the visuals. You can take it up now.

**Comment by xak** [comment]
@joseegm @jeannewalters @saadmhybris It would be good to identify which third-party date picker we recommend using and ensure the wires and design match that functionality. This looks very close to the Bootstrap date picker. Was that the inspiration?

**We will not be building this from scratch.**

**Comment by joseegm** [comment]
@xak 
We better refrain from starting introducing dependencies in the library right now. We just do the HTML/CSS.

**Comment by xak** [comment]
Our HTML/CSS will be useless if not applied to a specific implementation. We can assume there will be an `input` and `table` but otherwise there could be a lot of variation between third-party implementations. Just saying.

**Comment by joseegm** [comment]
@saadmhybris 
Can you please put the short list of alternatives for the datepicker?

**Comment by jeannewalters** [comment]
@saadmhybris Can you point me to the latest boostrap date/time picker demo?

**Comment by saadmhybris** [comment]
@jeannewalters project below seems to a widely used and active with development. Also works with bootstrap 4. 

https://tempusdominus.github.io/bootstrap-4/Usage/

**Comment by jeannewalters** [comment]
@saadmhybris I would like to explore the approach that is being used by the CDS > Customer Recovery team.  We will need to talk to Jago and their UI Dev.

**Comment by xak** [comment]
@LeoT7508 https://openui5.hana.ondemand.com/#/sample/sap.m.sample.DatePicker/preview

**Comment by xak** [comment]
@jeannewalters and @LeoT7508 Can we close this? I think we have all the visuals we need. See #353 for calendar and #417

**Comment by jeannewalters** [comment]
Reviewed.
