### ISSUE TITLE
Ops: SourceClear Security Validation - dependency lib. vulnerability - CHOWNR

### ISSUE THREAD

**Issue by ivijan** [SAP/fundamental#648]
## Detailed description

https://sap.sourceclear.io/

> SourceClear scanning for vulnerability issues reports issue with transitive dependency library [chownr](https://www.npmjs.com/package/chownr) that is dependency of [npm](https://www.npmjs.com/package/npm) that is defined in package.json under "engines" node.

## Additional information

` "engines": {
    "npm": ">=9.5.0 <10.0.0"
  }`

> Vulnerability issues: [Time Of Check To Time Of Use (TOCTOU)](https://www.sourceclear.com/vulnerability-database/security/time-of-check-to-time-of-use-toctou-/javascript/sid-7303)

> ![screen shot 2018-09-05 at 15 13 28](https://user-images.githubusercontent.com/13087038/45096013-cf034280-b11f-11e8-834a-c7996db9cbe2.png)

**Comment by saadmhybris** [comment]
@ivijan  we changed npm as an engine versus a direct dependency to the project as suggested in  #478. We also thought it will help resolve #591, but it didn't help much. 

Do you have a suggestion on how we can address all these three issues? (#478, #591 and #648)

**Comment by ivijan** [comment]
Hello @saadmhybris,
It is great that the topic of npm vulnerabilities is already known and processed.
I will also investigate the topic on the side, and if I find something, I will come back to you.

**Comment by saad-mo** [comment]
This issue has been addressed.
