### ISSUE TITLE
Shell: Product Switcher

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#669]
`product-switcher` (aka waffle)

-  [ ] popover with a waffle icon and product grid 

Design Sheet - https://zpl.io/an95Eln

**Comment by LeoT7508** [comment]
@saadmhybris @eboyer 

The waffle is still a very rough idea, so for the design sheet provided it'll probably be smart just to use it for sizing and  spacing. Details like logos, states, etc we can wait on.
