### ISSUE TITLE
Project: Release process

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#67]
Goal: Formalize release process. 

Now that we finally have a separate repo for FDUI, we need to formalize the release process. 

Todo: 
 - [x] Document the release process for github. 
 - [x]  Document the release process for NPM.
 - [ ] ~Get in touch with Wookies to see if we still need to be registered with dev portal documentation service.~
 - [x] Establish a release notes process.

**Comment by joseegm** [comment]
@saadmhybris 
Since Yaas is been put to rest now, we don't need to worry about releasing notes to Dev Portal. Is enough to put them in the Releases on github.

Saw the release documentation on the internal wiki.
