### ISSUE TITLE
Design - Responsive Breadcrumb Updates

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#678]
Revisit the breadcrumb for tablet and mobile.

**Comment by Jagoooo** [comment]
![breadcrumb](https://user-images.githubusercontent.com/38916020/45819504-5d5cf400-bcdc-11e8-81af-96f367253485.png)

**Comment by jeannewalters** [comment]
There is no update from DD Workstreams so I will close this for now.
