### ISSUE TITLE
Fiore 3.0 Component Status: In Application(Secondary) Navigation 

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#680]
Update to match DDB outcome from beginning Dec.

**Comment by Jagoooo** [comment]
5 levels deep is like trying to create a car with 10 doors. It is doable but it won't be a very good car for casual journeys.
We need to create something different... A bus... That won't be used first for casual journeys. 
Hope my little analogy manages expectations!

**Comment by Jagoooo** [comment]
[Design.docx](https://github.com/SAP/fundamental/files/2401272/Design.docx)
![tablet](https://user-images.githubusercontent.com/38916020/45818565-fc342100-bcd9-11e8-86a7-199e480ca6db.png)
![desktop](https://user-images.githubusercontent.com/38916020/45818566-fc342100-bcd9-11e8-9583-d750eef3de96.png)
![large desktop](https://user-images.githubusercontent.com/38916020/45818567-fc342100-bcd9-11e8-8564-9217e1ed5e95.png)

**Comment by Jagoooo** [comment]
![mobile](https://user-images.githubusercontent.com/38916020/45818596-10781e00-bcda-11e8-974e-5fa582bbe044.png)
![tablet](https://user-images.githubusercontent.com/38916020/45818597-10781e00-bcda-11e8-8a42-7cb10ed7102b.png)
![desktop](https://user-images.githubusercontent.com/38916020/45818598-10781e00-bcda-11e8-9567-3d1a25772557.png)
![large desktop](https://user-images.githubusercontent.com/38916020/45818599-1110b480-bcda-11e8-9ca6-89c148b36285.png)

**Comment by Jagoooo** [comment]
![mobile](https://user-images.githubusercontent.com/38916020/45819435-34d4fa00-bcdc-11e8-8b80-0561bf60b6c6.png)
![tablet](https://user-images.githubusercontent.com/38916020/45819436-34d4fa00-bcdc-11e8-94e5-af5413e0e345.png)
![desktop](https://user-images.githubusercontent.com/38916020/45819437-34d4fa00-bcdc-11e8-8f66-e24a8adc9c8e.png)
![large desktop](https://user-images.githubusercontent.com/38916020/45819438-34d4fa00-bcdc-11e8-99dc-b48aa1113d90.png)

**Comment by jeannewalters** [comment]
@Jagoooo  Can you please update this ticket based on the decision from the DDB last week? Thanks
