### ISSUE TITLE
TBD: Supported web browsers

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#690]
Thanks for starting this project. Could you please update the README file with supported web browsers?

**Comment by saad-mo** [comment]
we are working on improving IE11 support. all modern web browsers are supported.

**Comment by bsrdjan** [comment]
More specific list, like that of [TWBS for example](https://getbootstrap.com/docs/4.3/getting-started/browsers-devices/), or [SAP UI5](https://sapui5.hana.ondemand.com/#/topic/74b59efa0eef48988d3b716bd0ecc933) would be helpful for developers and users IMHO. Mentioning also handheld devices/platforms.
