### ISSUE TITLE
gulp serve error

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#691]
To start working on fundamental-aurelia, I cloned the repository on OSX and installed dependencies using `yarn install` because `npm install` was failing. Perhaps README could be updated with build platform prerequisites, like ruby, python version required, yarn install option etc.

After starting gulp, the browser window opens, with following error. The same happens with master and develop branch:

```shelll
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'
```

Please find the screenshot:
![screen shot 2018-09-14 at 09 37 40](https://user-images.githubusercontent.com/1697847/45536458-e0280f80-b801-11e8-8244-0bd433c7bc69.png)

How to fix this ?

**Comment by saadmhybris** [comment]
@bsrdjan what's the problem with npm install? We don't support yarn so it's hard to say what the problem here is.

**Comment by saadmhybris** [comment]
@bsrdjan pls follow the project configuration steps in sequence below. This should fix the problem you were having. you need to install `ruby gems` and `bundle` dependencies before running `npm install`. We are also updating the project readme with the same instructions as below. 

<hr> 

## Project configuration 
1. **Clone Repository** - Clone the repo using the git software of your choice or using the git command `git clone https://github.com/SAP/fundamental.git`

2. **Install Gulp** - In addition to Node, you must have Gulp installed globally: `npm install -g gulp`

3. **Install Ruby Gems** - These gems are need to be installed for the documentation site: `gem install ruby bundle jekyll`

4. **Install Bundle Dependencies** - Bundle dependencies must be installed the from `docs` directory
`cd docs` and then `bundle install`

5. **Install NPM Dependencies**: `npm install`

6. **Serve it locally** - The documentation website is served from the `docs/_site` directory which is generated by Jekyll. To generate and lunch the documentation site, simply execute the gulp command in the terminal at the root of the project directory: `gulp`

**Comment by bsrdjan** [comment]
Thanks for the update. Can confirm steps 1-4 work and for 5 I opened #698
