### ISSUE TITLE
Redundant CSS for Checkbox & Radio 

### ISSUE THREAD

**Issue by hamiarcher** [SAP/fundamental#697]
## Detailed description
We have huge redundant CSS in output file for 'checkbox' & "radio" button. 
This is a bug.
Any one can open current css file and search for "input[type=radio], input[type=checkbox]" keyword and result is big chuck of css is getting repeated increase the size of CSS file unnecessary.

## If BUG, steps to reproduce the issue
1. Remove line # 11 form "fundamental/scss/components/checkbox.scss"
2. do gulp/compile check the difference for 'fundamental-ui.css' or "fun-site.css" file.

**Comment by eboyer** [comment]
@hamiarcher ~ We have addressed this issue in the most recent release of v1.2.1! Thanks for pointing this out for us. :)
