### ISSUE TITLE
Hover/Focus Audit

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#723]
As we get deeper in supporting accessibility and keyboard navigation in our components, we are uncovering a handful of instances where we need to add focus/hover states. This is a running inventory on all focus/hover states that are missing from these components in the library. 

- [ ] - Menu Option / Item
- [ ] - Any anchors (breadcrumb, menu items, etc) need a more obvious visual indicator that they've been focused.  They simply change from blue to a darker shade of blue.  Side navigation items don't change color.  I think there should be an underline as well.  The fundamental ui docs site imports bootstrap, which adds the underline, but fundamental doesn't provide this itself
- [ ] - Side navigation icons need a focus state (background color change maybe?)
- [ ] - Tabs
- [ ] - Input group - number spinners, clear search button

**Comment by eboyer** [comment]
Note: removing `span/image popover controls (buttons are fine)` from the list. 

From our Slack conversation: "For the popover control specifically, I would like to leave that as an open container that you can put *anything* into. And on *those things themselves* is where you would have your focus styles.

Popover control should be a completely generic container, just as popover body."

**Comment by mikerodonnell89** [comment]
> Note: removing `span/image popover controls (buttons are fine)` from the list.
> 
> From our Slack conversation: "For the popover control specifically, I would like to leave that as an open container that you can put _anything_ into. And on _those things themselves_ is where you would have your focus styles.
> 
> Popover control should be a completely generic container, just as popover body."

That makes sense, would it possible to have a generic focus helper class that could be applied to any element?
