### ISSUE TITLE
Lib: Dropdown Direction Support 

### ISSUE THREAD

**Issue by mikeRujevic** [SAP/fundamental#731]
## Detailed description

>  If you add dropdown in any other corner then top left, you should have ability to control direction for root element <nav class="fd-menu">

> Is this a feature request (new component, new icon), a bug, or a general issue? **YES**

> Is this issue related to a specific component? **DROPDOWN**

> What did you expect to happen? What happened instead? What would you like to see changed?
Added dropdown to top right corner, expected to have "fd-menu" opened aligned with right side of display as it was located inside of  <fd-navbar-group [position]="'right'">. 
Actually "fd-menu" opened aligned to left of the "fd-menu", please see picture below. 

![fd-menu overlaping html element I](https://user-images.githubusercontent.com/17923721/46609906-9a611d00-cb09-11e8-9b63-e073f571e945.png)
![fd-menu overlaping html element II](https://user-images.githubusercontent.com/17923721/46609911-9cc37700-cb09-11e8-805b-ba002aa5bc26.png)
 
> What browser are you working in?

Google Chrome
**Version 69.**0.3497.100 (Official Build) (64-bit)

> What version of the Fundamental UI are you using?

**1.2.2**

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

**Angular** 

## If FEATURE REQUEST, describe the need

* Dropdown

* Using dropdown from:
- right top corner
- bottom left -||-
- bottom right -||- 
Generally controlling direction where fd-menu is going to display.

**Comment by saadmhybris** [comment]
left, right no arrow options are now available - https://sap.github.io/fundamental/components/popover.html#placement-options

**Comment by mikeRujevic** [comment]
@saad-mo Thanks
