### ISSUE TITLE
Link to Developer page not found

### ISSUE THREAD

**Issue by cmanciero** [SAP/fundamental#737]
## Detailed description

> Describe in detail the issue you're having.
Page not found when accessing https://sap.github.io/fundamental/foundation/getting-started-developers.html

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug

> Is this issue related to a specific component? 
No

> What did you expect to happen? What happened instead? What would you like to see changed?
Access a page describing getting started for developers

> What browser are you working in?
Chrome

## If BUG, steps to reproduce the issue

1. Access https://sap.github.io/fundamental/foundation/getting-started-developers.html

**Comment by saadmhybris** [comment]
@cmanciero - hello, we have gone through some redesign/reorg on the website. The page you are looking for can be found here - https://sap.github.io/fundamental/getting-started.html

Sorry about the confusion.
