### ISSUE TITLE
Adding a section for the implementation projects on the README.md

### ISSUE THREAD

**Issue by TheGreenToaster** [SAP/fundamental#738]
## Detailed description
I found this project and was excited about it but the thought of implementing these controls in angular sounded daunting and discouraged me a bit. It wasnt till later while trying to get back to this repo before I realized that there was already a project for it. I was thinking a section on the README.md with the links to the implementation projects could be useful?

**Comment by xak** [comment]
Added links to the top of the README. Thanks!
https://github.com/SAP/fundamental/blob/develop/README.md
