### ISSUE TITLE
Button: Implement split button

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#751]
## The button consists of one or two clickable areas. The first area can either contain text or any kind of content. The second area (optional) contains a drop-down arrow. 

https://sapui5.hana.ondemand.com/#/sample/sap.m.sample.MenuButton/preview

![image](https://user-images.githubusercontent.com/424119/46923695-46f73f00-cfe1-11e8-9e04-e13674698a98.png)
![image](https://user-images.githubusercontent.com/424119/46923696-49599900-cfe1-11e8-92c8-93948fc25ab2.png)

## Design 

TBD

**Comment by saadmhybris** [comment]
closing in favor of 954
