### ISSUE TITLE
Design: Dialog

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#754]
* simlar to `fd-modal`<br><img width="367" src="https://user-images.githubusercontent.com/15215400/46756799-e63ccf00-cc8d-11e8-9125-f81fbe5135d9.png"><br>
* [Full specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams~2FShared%20Documents~2FDesign%20Specifications~2FSpecifications~2FControls~2FDialog.pptx?threadId=19%3A6d7fc92ef619458eb00db162f50935e0%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams&fileId=719219C1-45D0-4962-801B-86A711BB56E3&ctx=files&viewerAction=view)

**Comment by saadmhybris** [comment]
duplicate of #977

**Comment by jeannewalters** [comment]
Here is the specification from UX that includes documentation:
![dialog](https://user-images.githubusercontent.com/24274321/48565295-98d80100-e8ce-11e8-80aa-79779ef4f0eb.png)
![dialog](https://user-images.githubusercontent.com/24274321/48565354-bdcc7400-e8ce-11e8-850c-1697b0f02ee3.png)
