### ISSUE TITLE
Design: Timepicker

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#756]
* Time picker different from current fdui implimentation <br><img width="220" src="https://user-images.githubusercontent.com/15215400/46811364-3b351f80-cd38-11e8-8dfd-3ba5c129802b.png"><br>
* Date time combo <br><img width="528" src="https://user-images.githubusercontent.com/15215400/46812511-77697f80-cd3a-11e8-8f2b-ee825941923c.png"><br>
* Date range picker <br><img width="512" src="https://user-images.githubusercontent.com/15215400/46812920-581f2200-cd3b-11e8-9c8c-8700f3ee5325.png"><br>
* [Full specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams~2FShared%20Documents~2FDesign%20Specifications~2FSpecifications~2FControls~2FCheck%20Box.pptx?threadId=19%3A6d7fc92ef619458eb00db162f50935e0%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams&fileId=FE4F2C79-73F4-4B65-93A0-801D2EE470E0&ctx=files&viewerAction=view)

**Comment by LeoT7508** [comment]
Duplicate ticket, #968 

Closing this.
