### ISSUE TITLE
Design: Date Time Picker (part of Inputs)

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#758]
* Time picker diffrent from current fdui implimentation and similar to [Fiori 2.0 version](https://sapui5.hana.ondemand.com/#/sample/sap.m.sample.TimePicker/preview)<br><img width="220" src="https://user-images.githubusercontent.com/15215400/46811364-3b351f80-cd38-11e8-8dfd-3ba5c129802b.png"><br> 

* Date time combo is also similar to [Fiori 2.0 version](https://sapui5.hana.ondemand.com/#/sample/sap.m.sample.DateTimePicker/preview)<br><img width="528" src="https://user-images.githubusercontent.com/15215400/46812511-77697f80-cd3a-11e8-8f2b-ee825941923c.png"><br> * Date range picker <br><img width="512" src="https://user-images.githubusercontent.com/15215400/46812920-581f2200-cd3b-11e8-9c8c-8700f3ee5325.png"><br>

* [Full specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams~2FShared%20Documents~2FDesign%20Specifications~2FSpecifications~2FControls~2FInput%20et%20al..pptx?threadId=19%3A6d7fc92ef619458eb00db162f50935e0%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams&fileId=A9D1EB3A-B65A-4A7D-9630-664598247D17&ctx=files&viewerAction=view)

**Comment by saadmhybris** [comment]
adding this to the design board

**Comment by xak** [comment]
@jeannewalters Is this approach OK or are you planning to push back and present an alternate design to the Controls workstream? How should we proceed?

**Comment by jeannewalters** [comment]
@xak Jago was working on this. @saadmhybris for some reason Jago is no longer on this project so I can't @ him.
