### ISSUE TITLE
[Docs] Show example of textarea with char message

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#759]
* The maximum length of the content shall be defined in characters. If defined, the number of remaining / exceeding characters are shown
<br><img width="463" alt="screen shot 2018-10-11 at 10 08 54 am" src="https://user-images.githubusercontent.com/15215400/46814134-b2b97d80-cd3d-11e8-9c0e-8ea65e30db68.png"><br>
* We don't show any error states for text area (same as input states) 
* [Full specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams~2FShared%20Documents~2FDesign%20Specifications~2FSpecifications~2FControls~2FText%20Area.pptx?threadId=19%3A6d7fc92ef619458eb00db162f50935e0%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams&fileId=59AA1127-3367-461A-80C7-DD139EF2EB62&ctx=files&viewerAction=view)

---
We don't need an explicit design for this. It can be shown as a part of the new Textarea section defined in #822. We can use existing helpers to demonstrate how to accomplish this character count field.

```
<div class="fd-form__item">
    <label class="fd-form__label" for="j7QPr100">
        Field Label:
    </label>
    <textarea class="fd-textarea fd-form__control is-invalid" id="j7QPr100">Pellentesque metus lacus commodo eget justo ut rutrum varius nunc. Sed non rhoncus risus. Morbi sodales gravida pulvinar. Duis malesuada odio volutpat elementum vulputate massa magna scelerisque ante et accumsan tellus nunc in sem.</textarea>
    <span class="fd-form__message fd-has-color-status-3 fd-has-text-align-right">
    4 characters exceeded</span>
</div>
```

in the above, the `is-invalid` class would be toggled on the control and the `fd-has-color-status-3` classes on the message field.

> Some refactoring would be needed to accomplish this solely with the existing message container. For example, the error icon is included as an `:after` and cannot easily move to the right, and the message container uses a modifier which should change to a state class so that it can be toggled. The Nunjucks template does not make these mods very easily so that would need to be rebuilt.

**Comment by saadmhybris** [comment]
we are waiting for specs from @jeannewalters
