### ISSUE TITLE
Ops: setup automatic branch deployment for reviews.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#76]
For internal review, set up automatic deployment to the internal staging server.

**Comment by joseegm** [comment]
@saadmhybris 
Did you already made contact with the one supporting us on this? if so please move it to In progress

**Comment by saadmhybris** [comment]
no it's in in progress yet.

**Comment by saadmhybris** [comment]
Just a short one to let you know I took time to upload my GitHub Continuous Deployment scripts on a GitHub repo:
https://github.wdf.sap.corp/hybris-pd/continuousDeploymentOnLinux

**Comment by saadmhybris** [comment]
- Prioritize the feature branch deployment of the static documentation site
- work on deployment of the test server
