### ISSUE TITLE
Lib: Add support for tokens inside of inputs 

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#760]
* token support inside an input field<br><img width="291" src="https://user-images.githubusercontent.com/15215400/46811096-b2b67f00-cd37-11e8-9d47-900975930885.png"><br>
* RTL support
* [Full Specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams~2FShared%20Documents~2FDesign%20Specifications~2FSpecifications~2FControls~2FInput%20et%20al..pptx?threadId=19%3A6d7fc92ef619458eb00db162f50935e0%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FDDBWorkstreams&fileId=A9D1EB3A-B65A-4A7D-9630-664598247D17&ctx=files&viewerAction=view)

**Comment by xak** [comment]
Converting this to a design story. This is a large effort so let's start with design.

**Comment by xak** [comment]
@LeoT7508 We need a mockup of tokens inside the input.
