### ISSUE TITLE
2 dimensional grid system?

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#766]
Would you consider a grid system based on 2-dimensional and more modern [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/), rather than basically 1-dimensional Flexbox?

**Comment by xak** [comment]
Hi, we do have this in terms of our `panel-grid` and `tile-grid` components.

https://sap.github.io/fundamental/layouts/panel.html#default-panel-grid-3-columns
https://sap.github.io/fundamental/components/tile-grid.html

They are written for specific use cases but combined with the [grid helpers classes](https://github.com/SAP/fundamental/blob/develop/dist/helpers.css#L1339) you could achieve a grid layout easily.
