### ISSUE TITLE
Multiple icon groups

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#767]
Please consider supporting more that one input group, on either side on input field.

**Comment by xak** [comment]
The element will support both before and after addons.

```
<div class="fd-input-group fd-input-group--after">
    <span class="fd-input-group__addon fd-input-group__addon--before">$</span>
    <input type="text" class="fd-input" id="" value="19387309">
    <span class="fd-input-group__addon fd-input-group__addon--after">€</span>
</div>
``` 

But the styling need some adjustments to optimize the border-radius.

<img width="553" alt="screen shot 2018-10-22 at 9 06 00 pm" src="https://user-images.githubusercontent.com/424119/47330652-a2a77500-d63e-11e8-8b69-c0d0c174172c.png">

**Comment by bsrdjan** [comment]
I meant multiple addons on a single side, like in [TWBS 4.0]( https://getbootstrap.com/docs/4.0/components/input-group/#multiple-addons). The version 3.0 had a restriction here: https://getbootstrap.com/docs/3.3/components/#input-groups-basic

**Comment by saad-mo** [comment]
@bsrdjan you would have to do your own css overrides for your use cases.
