### ISSUE TITLE
Two inputs one label layout (ranges)

### ISSUE THREAD

**Issue by bsrdjan** [SAP/fundamental#768]
Please consider layout supporting two input values, with single label. Usually ranges, like:

Temperature from/to: _____________    ________________

Trip start/end date:   ______________ .  _________________

**Comment by saad-mo** [comment]
@bsrdjan you could have to make some custom overrides on the forms input group css. this use case too specific to implement in the library. We try to keep our components as generic as possible.

**Comment by bsrdjan** [comment]
The case comes often in business applications and was a bit challenging for me to implement it before, using TWBS and similar frameworks. The 2nd input field sometimes requires a label and sometimes not, like in this date input example:
![screenshot 2019-02-28 at 11 01 46](https://user-images.githubusercontent.com/1697847/53558452-5918ea80-3b48-11e9-9b35-ef9ec50cbad1.png)
Removing the label from one form set/item, often "disturbs" the form overall layout. How is the situation/plan with fundamental form items, are both row and column form layouts supported and does the form layout remain consistent and nice, when some fields have label and some not?
