### ISSUE TITLE
Lib: Deprecate link color vars in 2.0

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#770]
## The `fd-link-color**` SASS vars should match the standard BEM-ish approach.

**Issue #734 additions**
- `fd-color--action` should be used as the main var for any action color
- `fd-color-state("hover")` should be used to access state colors

In release v1.5, deprecate the old color vars.

```
$fd-link-color: map-get($fd-colors-action, 1) !default;
$fd-link-color--hover: adjust-color($fd-link-color, $lightness: -7%) !default;
$fd-link-color--active: darken($fd-link-color, 10) !default;
$fd-link-color--pressed: adjust-color($fd-link-color, $lightness: -10) !default;
$fd-link-color--visited: adjust-hue($fd-link-color, 45deg) !default;
$fd-link-color--disabled: rgba($fd-link-color, 0.4) !default;
```

**Comment by eboyer** [comment]
Moving this issue to v1.5.0 for deprecation work, as mentioned.
