### ISSUE TITLE
Fix menu SASS variables

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#773]
## Detailed description
Setting the var in the component has no effect since the `!default` is set already. If the variables are only used by `menu` they should not be in `settings`.

### In `settings`
```
// menus and lists and navs
$fd-menu-border-color: red !default;
$fd-menu-background-color: map-get($fd-colors-background, 2) !default;
$fd-menu-box-shadow: 0 0 4px 1px rgba(map-get($fd-colors-neutral, 2), 1) !default;
$fd-menu-z-index: 2 !default;
$fd-menu-border-color: transparent !default;
$fd-menu-title-color: map-get($fd-colors-text, 3) !default;
$fd-menu-title-padding: map-get($fd-spacing, "xxs") !default;
$fd-menu-title-background-color: map-get($fd-colors-neutral, 1) !default;
$fd-menu-item-color: map-get($fd-colors-text, 2) !default;
$fd-menu-item-background-color--selected: rgba(map-get($fd-colors-action, 1), .07) !default;
$fd-menu-item-background-color--hover: map-get($fd-colors-neutral, 2) !default;
//$fd-menu-item-color--hover: map-get($fd-colors-text, 2) !default;
$fd-menu-item-padding-x: map-get($fd-spacing, "reg") !default;
$fd-menu-item-padding-y: map-get($fd-spacing, "xs") - 2px !default;
$fd-menu-link-color: $fd-link-color !default;
$fd-menu-link-color--disabled: map-get($fd-colors-text, 3) !default;
$fd-menu-transition-params: $fd-animation--speed ease-in !default;
```

### In `menu`
```
    $fd-menu-color: $fd-forms-color !default;
    $fd-menu-background-color: fd-color(background) !default;
    $fd-menu-item-color: $fd-menu-color !default;
    $fd-menu-item-color--hover: $fd-menu-color !default;
    $fd-menu-item-background-color: $fd-menu-background-color !default;
    $fd-menu-item-background-color--hover: fd-color-state("hover") !default;
    $fd-menu-item-background-color--selected: fd-color-state("selected") !default;
    $fd-menu-item-padding: fd-space(3) fd-space(4) !default;
    $fd-menu-item-color--disabled: fd-color("text", 2);
    $fd-menu-item-seperator-color: fd-color("neutral", 2);
```

**Comment by ckoutsiaris** [comment]
Hello @saadmhybris @xak @eboyer, 

After going through the code I found that there is a number of variables that been used in the dropdown component in menu option https://github.com/SAP/fundamental/blob/develop/scss/components/dropdown.scss#L153

In dropdown documentation, we don’t mention this option anywhere so I suspect that this is left over from previous versions. Then I checked where this option been used at the moment and it is in a few code examples (tile, table, tree, toolbar) and in the support option in navigation in the docs website. I took the liberty to remove this menu option from the dropdown, I did some clean-up on the variables and replaced the old dropdown code with the new one in all except toolbar which afaik we are going to deprecate and it is broken in production anyway.
 
This will cause breaking changes to any customers using the old dropdown with the __menu option so I am not sure how to proceed. Can you please let me know what you think?

Here is my code changes so far: https://github.com/SAP/fundamental/compare/cleanup/menu-sass-773
