### ISSUE TITLE
[Docs] Update spacing illustrations for sections and panels

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#782]
## Some layout components need to be updated based on the new spacing specs

The new spacing specs changes the common, regular unit from `20px` to `24px`. The standard unit for paragraph and other margins is now `16px` from `20px`.

## Detailed description

> Describe in detail the issue you're having.

The spacing illustrations are out of date — https://sap.github.io/fundamental/foundation/spacing.html

**Comment by xak** [comment]
@LeoT7508 Can you take this for the upcoming release?

**Comment by saadmhybris** [comment]
@LeoT7508 do you have an eta on the updated visuals?

**Comment by xak** [comment]
@LeoT7508 The attached images don't match the specs at https://sap.github.io/fundamental/foundation/grid.html#breakpoints

These two are wrong ... 
![4 column grid_600_s 2x](https://user-images.githubusercontent.com/424119/50245634-9a4a8c80-0398-11e9-8b73-03f6fea6881f.png)

![8 column grid_1024 2x](https://user-images.githubusercontent.com/424119/50245619-9159bb00-0398-11e9-94c5-0bda163534fc.png)
