### ISSUE TITLE
Improve RTL for button group

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#785]
## Detailed description

http://localhost:3030/button-group

> Describe in detail the issue you're having.

Border radius adjustments are not being applied properly.
http://localhost:3030/button-group

<img width="387" alt="screen shot 2018-10-22 at 8 24 16 am" src="https://user-images.githubusercontent.com/424119/47294980-1e200c80-d5d4-11e8-91b3-3bc58093130b.png">

**Comment by ianquigley-sap** [comment]
Marking as done, fix was delivered.
