### ISSUE TITLE
Improve RTL support for dropdown 

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#796]
## The `dropdown` component is broken in RTL mode

<img width="381" alt="screen shot 2018-10-22 at 7 43 37 pm" src="https://user-images.githubusercontent.com/424119/47327466-07f56900-d633-11e8-83b8-deb1da83c0a3.png">

**Comment by ianquigley-sap** [comment]
Thanks @eboyer

**Comment by ianquigley-sap** [comment]
Closing issue, fix was delivered.
