### ISSUE TITLE
Lib: Add indeterminate state on checkboxes

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#797]
## The custom styling is hiding the `:indeterminate` state.

```
input[type="checkbox"],
.#{$fd-namespace}-checkbox {
    &:indeterminate {
      // styles
    }
}
```

We should display a mark through the middle. See https://zpl.io/agnkgPM

<img width="597" alt="screen shot 2018-11-19 at 10 42 20 am" src="https://user-images.githubusercontent.com/15215400/48722607-0b582200-ebea-11e8-9b1d-7f69e884b85a.png">

**Comment by ritarora** [comment]
@xak @saadmhybris Have added the 3 states of the checkbox as in the PR screenshot.
4th state as in the designs is just a representation of mouse hover on the checkbox, so not sure if we want to add that by some javascript code?
