### ISSUE TITLE
Docs: Publish getting started tutorial for teams using the SASS source

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#80]
Some info exists here ...
https://github.com/SAP/fundamental/wiki/Advanced-Customization

Emphasis should be on using the functions and mixins to access the design system. The further teams stray from the system the more difficult it will be to implement updates.

---
More info ...

### Design system

The site shows specs for colors, spacing and type and you can compare these to the SASS implementation as maps in `core/_settings.css`.

Such as spacing ...
```
//spacing
$fd-spacing--base: 4px;
$fd-spacing: (
    base: $fd-spacing--base,    //4
    xs: $fd-spacing--base * 2,  //8
    s: $fd-spacing--base * 3,   //12
    reg: $fd-spacing--base * 5, //20
    m: $fd-spacing--base * 10,  //40
    l: $fd-spacing--base * 25,  //100
    xl: $fd-spacing--base * 37, //148
) !default;
```
To access that map, I can use the `fd-space` function and simply pass the size key (or an integer).

```
margin-bottom: fn-space(xs); //returns 8
padding-bottom: fn-space(6); //returns 24
```
For type, I use a `fd-type` mixin since it returns multiple rules.
```
@include fd-type(5);
```
returns 
```
font-size: 2.8125rem;
line-height: 1.15556;
font-family: sans-serif;
font-weight: 500
```

There are many variables available already for global styling which all use the maps to ensure consistency. The idea is that devs should rarely hard-code a color, font-sizes, etc. that is part of the design system.

### Customization

We provide a CDN link to bring in the full, compiled library if you have no customization needs, you get the default look and feel on which you can add new components and stylings.

However, many teams need direct control and will want to use the source. I compiled a quick guide to show how to implement and new theme and redefine variables to suit your needs.

https://github.com/SAP/fundamental/wiki/Advanced-Customization

Most CSS rules that can be themed are available as variables, globally and at the component level. We use a CSS-rule naming system with modifiers. The prefix is the rule the value would be used for and modifier indicates variations.

```
$fd-font-family           //global default
$fd-font-family--header
$fd-font-family--code
$fd-font-size             //global default
$fd-color                 //global default
$fd-color--link
$fd-color--error
$fd-margin-bottom         //global default
```
More specific variables use an additional prefix.
```
$fd-forms-padding
$fd-forms-color--placeholder
$fd-forms-background-color
$fd-forms-border-color
```
And components use their block name as a prefix.
```
$fd-tabs-margin-bottom
$fd-tabs-border-width
$fd-tabs-border-color
```
Any and all of these variables can be redefined in your custom theme file.

**Comment by joseegm** [comment]
@xak 
How is this related to #81? or it is something different?
This looks like different things together, not easy to break down as it is. We'll discuss it at the next opportunity.

**Comment by xak** [comment]
I've discussed this with @saadmhybris. He will do a prelim review and we can add more detail if necessary. I just wanted to get a story here for planning purposes.

The most important thing is to start exposing the toolkit to devs. Our primary use case (for Hybris teams anyway) is no longer compiled CSS, it's the full SASS and we have nothing documented toward that.

**Comment by joseegm** [comment]
@xak 
Okay, let's talk it on the next opportunity. Because right now sounds like repeating info that we have over the site in a new page with the same info. 
I'm trying to minimize having duplicate info that must be updated twice.
