### ISSUE TITLE
Docs: Improve documentation of the grid

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#801]
## The grid documentation is not very useful.

https://sap.github.io/fundamental/foundation/grid.html

## Detailed description
 
- The grid specs are not up-to-date with the Fiori 3.0 recommendations
- The breakpoints have changed

## Reference
[See specs](https://teams.microsoft.com/_#/pptx/viewer/teams/https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FFundamentalUI~2FShared%20Documents~2FGeneral~2FMVS~2FLook~2FF3_Spacing_v1.pptx?threadId=19%3A01cbf0ac99a948dd90eaec782800ba6b%40thread.skype&baseUrl=https%3A~2F~2Fsap.sharepoint.com~2Fteams~2FFundamentalUI&fileId=D8790039-0CB1-4462-B72E-24D83AA69546&ctx=files&viewerAction=view)

**Comment by xak** [comment]
@LeoT7508 This is high priority. The previous images — https://github.com/SAP/fundamental/tree/develop/docs/images/grid — are no longer valid with the new specs from #747

**Comment by saadmhybris** [comment]
@LeoT7508 any update on this?
