### ISSUE TITLE
Improve error handling of type functions

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#802]
## The error message is not helpful

This is occurring because an invalid neg number — `-2`  is being passed and failing.
```
Message:
    scss/functions/_type.scss
Error: Undefined variable: "$-size".
        on line 8 of scss/functions/_type.scss, in function `fd-font-size`
        from line 11 of scss/mixins/_type.scss, in mixin `fd-type`
        from line 95 of scss/components/shell-header.scss
>> {map-keys($_map)}. Returning `#{$_size}`.";
```
## Detailed description

When passing an invalid value, the function should not halt SASS processing. The function should be able to handle any number (pos, neg) and a string.

If the `$size` value is not valid against the type map, the default `0` should be used.

**Comment by ckoutsiaris** [comment]
Should be ok now. Thanks
