### ISSUE TITLE
Lib: Option to add remover lines in tables

### ISSUE THREAD

**Issue by Jagoooo** [SAP/fundamental#807]
## Detailed description

Add the option in the coded to remove lines in tables
Add lines in tables as the default 

I have attached Hana's research into the usability of tables.

## If BUG, steps to reproduce the issue
[Fiori-Fundamental_Tables.pdf](https://github.com/SAP/fundamental/files/2510678/Fiori-Fundamental_Tables.pdf)

## If FEATURE REQUEST, describe the need

We want users to be able to differentiate between fields of data easily
### Reqs
The goal here is to add borders by default between the cells.
```
.fd-table td {
  border-bottom: fd-color("neutral", 2);
}
```
Addt'l allow override to remove the borders.
```
.fd-table--no-borders td {
  border-bottom: none;
}
```
And allow for zebra-striping.
```
.fd-table--striped tr:nth-child(even) {
  background-color: fd-color-state("hover");
}
```

**Comment by jeannewalters** [comment]
@saadmhybris Who should this be assigned to next?

**Comment by saadmhybris** [comment]
@jeannewalters i can take it, thanks!

**Comment by xak** [comment]
The PR #1000 does not address this issue, it adds zebra striping not borders.

**Comment by eboyer** [comment]
Removed the previous highlight code from the `v1.3.3` release.

**Comment by ritarora** [comment]
Thanks for your comments @xak , I will update the zebra stripping to be added at the table level.
Regarding the borders could you please point me to the specs which has the border specs as in the attached pdf I could only see the zebra striping and no borders.

**Comment by xak** [comment]
@LeoT7508 Can you verify that neutral 2 is the correct color to use for table borders? To the table design specs please show with borders, no borders, and zebra striping.

To the last item, should we use the same color as the hover? We have only these state colors ... https://github.com/SAP/fundamental/blob/develop/scss/_settings.scss#L175

**Comment by LeoT7508** [comment]
@xak 

I have not seen any explorations for tables from GD yet, so its safe to say we can move forward with what we had previously until we hear otherwise. I will add the new requirements into the Tables design sheet when we get to that task.

**Comment by jeannewalters** [comment]
@saadmhybris it was horizontal lines.
