### ISSUE TITLE
Docs: Create a design system cheat sheet guide

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#81]
We should have a single-pager cheat sheet that illustrates the design system — type, spacing, colors — and the functions and mixins (and helpers) available to access those in the library. 

This will be useful for both designers and developers implementing the design system.

**Comment by joseegm** [comment]
@xak 
We already have the design system pages for explaining. 
What's missing on those pages is the developer info.

We have two options:
1. Incorporate the developer info on the design system pages.
2. Create a developer focused, cheat sheet, but heavily on sass information, not on design.

I personally will tend to go for the first, since there will be only a single place to updated related information.

**Comment by saadmhybris** [comment]
This cheat sheet content is a good candidate to go under 'guides' section. I like how material-angular do the guides and we could follow a similar approach. we can have scss cheat sheet, step-by-step guides on how to setup angular, using starter pages, etc. 

https://material.angular.io/guides

**Comment by xak** [comment]
@joseegm Both options makes sense to me but initially the 2nd option is the easiest. I'm most interested in getting something in the hands of devs (and designers) with a quick overview of the design system and how to access the variables. This is something that can be done by a dev alone (maybe some help of design if we want more than a WIKI page).

Let's not overthink it now. Down the line we could introduce SASSDoc or detailed comments in the SASS. Let's focus on how we can get the most important information into the hands of the teams who need to use it.

**Comment by joseegm** [comment]
@xak 
Now, guides makes more sense. Cheat sheet is something else. 
Guides have a defined scope and a goal. A cheat-sheep is a list of shortcuts and small pieces of info put together.

The way that material does I find it very good as well. Let's call it guides to avoid confusion.
