### ISSUE TITLE
Design a new Sketch template for presenting modules in Zeplin 

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#812]
## The Sketch file pages should be organized in the same way as the library.

Each screen in Zeplin should have the following ...

- Component name
- Version
- Package (`core`, `layout`, `components`, `floorplans`)
- SAP and Fiori Fundamentals branding

Each module should also have a representation of the following states (if applicable) ...

- Empty
- Loading
- Hover/Active
- Disabled
- Updated

Each module should have a representation of the following contexts ...

- Compact
- Responsive

**Comment by saad-mo** [comment]
closing as this seems to be done.
