### ISSUE TITLE
Fiori 3.0 Component Status: Slide Toggle

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#813]
Need example from Core Systems - meeting on 11/11

**Comment by xak** [comment]
@jeannewalters Any update on this? Is this what is needed?

![f3_slider_rangeslider](https://user-images.githubusercontent.com/424119/49661823-c3b9fe80-fa0f-11e8-9b7f-5642ada8f074.png)

**Comment by jeannewalters** [comment]
There is no decision from Controls but this is the latest from the Sketch file so this works. I will work on documentation.
