### ISSUE TITLE
Design - Date Time Input

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#814]
Waiting on Core Systems on requirements - 11/11

**Comment by xak** [comment]
@jeannewalters Any update on this?

**Comment by jeannewalters** [comment]
This is still in the Control teams. Closing for now.

**Comment by jeannewalters** [comment]
From Controls Team:
Date Range Input Field 
![image](https://user-images.githubusercontent.com/24274321/49763335-b8cacc80-fca2-11e8-9f66-f19e7ee998f2.png)

Date Range Picker
![image](https://user-images.githubusercontent.com/24274321/49763428-f7608700-fca2-11e8-9ddd-5e8b5ef051a8.png)

Date entered should be validated based on the following rules:
![image](https://user-images.githubusercontent.com/24274321/49763493-31ca2400-fca3-11e8-93a0-45c4dcb34ef1.png)

There is no example for Date/Time Range. There is also no specified documentation from the team in the spec. I will add more to this.

**Comment by jeannewalters** [comment]
Closing. Duplicate.
