### ISSUE TITLE
Add new Floating Button types

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#816]
### Detailed description
> Describe the request

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

> What front-end framework are you implementing in, e.g., Angular, React, etc.?

### Component name
> Propose a new or variant name

### Use case
> Describe when to use (and when not to use)

### Visual style
> Describe specific needs related to color, typography, iconography, borders, space, size, and other visual properties.

> Describe how to arrange multiple instances and other alignment specifics.

> How should this respond to common contexts, i.e., touch, RTL, small screens.

> Describe interactive states, e.g., disabled, expanded, pressed.
 

### Expected behavior

> How should this handle events, outcomes, and transitions

> What [states should be available](https://medium.com/swlh/the-nine-states-of-design-5bfe9b3d6d85), i.e., nothing, loading, none, one, some, too many, incorrect, correct, done.

### Editorial

> Advise on labels, tone, length, punctuation, truncation.

## Additional information

* Screenshots or code
Material Design (Provided by Core Systems)
![image](https://user-images.githubusercontent.com/24274321/47504680-b8818980-d83a-11e8-96ac-596379d3a39a.png)

SmartEdit
![image](https://user-images.githubusercontent.com/24274321/47505027-4f4e4600-d83b-11e8-8750-460d01467d2b.png)

* Notes
This request is from Core Systems and SmartEdit.

**Comment by xak** [comment]
@jeannewalters We need to evaluate the request first and then it can be prioritized before proceeding to design. Please expand on the request with the details added to the issue above.

**Comment by xak** [comment]
This request should go through SAP Design and the DDB approval process. Please provide the information requested above to explain the need and the use cases and provide to your DDB representative.
