### ISSUE TITLE
Documentation - Link

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#817]
Use Controls Workstream documentation created for the link component to improve Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > link.pptx

Add content to the following sections (**if applicable**):

**Intro:**

**Usage:**

**Structure:**

**Behavior & Interactions:** 

**Responsive & Adaptive:**

**Comment by xak** [comment]
The spec has nothing especially useful over the current documentation.
