### ISSUE TITLE
Documentation - Buttons

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#818]
Use Controls Workstream documentation created for the button component to improve Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > button.pptx

Add content to the following sections (**if applicable**):

**Intro:**

**Usage:**

**Structure:**

**Behavior & Interactions:** 

**Responsive & Adaptive:**

**Comment by xak** [comment]
The spec has nothing especially useful that we do not already capture.
