### ISSUE TITLE
Documentation - Input

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#819]
Use Controls Workstream documentation created for the input component to improve Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > Input et al..pptx

Add content to the following sections (**if applicable**):

**Intro:**

**Usage:**

**Structure:**

**Behavior & Interactions:** 

**Responsive & Adaptive:**

**Comment by xak** [comment]
Consolidated into #822
