### ISSUE TITLE
Documentation - Label

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#820]
Use Controls Workstream documentation created for a label component in the Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > label.pptx

Add content to the following sections (if applicable):

Intro:

Usage:

Structure:

Behavior & Interactions:

Responsive & Adaptive:

**Comment by xak** [comment]
Consolidated with #822
