### ISSUE TITLE
Documentation - Radio Button

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#824]
Use Controls Workstream documentation created for a radio button component in the Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > Radio Button.pptx

Add content to the following sections (if applicable):

Intro:

Usage:

Structure:

Behavior & Interactions:

Responsive & Adaptive:

**Comment by xak** [comment]
We have no specific radio button page and much of the spec doc is default browser behavior that we do not need to document explicitly.
