### ISSUE TITLE
Documentation: Text Area

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#826]
Use Controls Workstream documentation created for a text area component in the Fiore Fundamental Library Content.

Documentation: Teams > DDB Workstreams > Design Deliverables > Controls > Text Area.pptx

Add content to the following sections (if applicable):

Intro:

Usage:

Structure:

Behavior & Interactions:

Responsive & Adaptive:

**Comment by xak** [comment]
Consolidated into #822
