### ISSUE TITLE
Bug: Combobox Artifacts

### ISSUE THREAD

**Issue by ChristianKienle** [SAP/fundamental#829]
If a combobox is positioned below another combobox, drawing artefacts occur once the top combobox is expanded.

I have deployed a sample here: https://bugs-pjhlhlkswd.now.sh/

Decreasing the z-index fixes this issue. This also happens when using the JavaScript code you use in your documentation app. Am I supposed to change the z-index myself or is it a bug?

**Comment by xak** [comment]
Please validate this is now fixed in `develop` branch.

**Comment by saadmhybris** [comment]
This issue has been fixed. 

closed 
<img width="899" alt="screen shot 2018-11-08 at 11 39 40 am" src="https://user-images.githubusercontent.com/15215400/48216712-1342d700-e34b-11e8-95b1-2e6fc6e7f346.png">

open
<img width="901" alt="screen shot 2018-11-08 at 11 39 48 am" src="https://user-images.githubusercontent.com/15215400/48216713-1342d700-e34b-11e8-976b-76a38788f060.png">

can be tested live at - https://sap.github.io/fundamental/components/combobox-input.html
