### ISSUE TITLE
Popover arrow audit

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#836]
## Detailed description

Before the release of v1.3: since we've added the visual arrow back to popovers, we must do an audit in the system to make sure it's properly aligning everywhere it needs to be. 

- [x] no border on the arrow
- [x] modifiers for no-arrow 
- [x] modifier for left and right 
- [x] fix combobox-input
- [x] fix date-picker
- [x] fix time-picker 
- [x] fix search-input
- [x] fix localization-editor 
- [x] fix multi-input 

http://cl.ly/b8386a7e9346

**Comment by saadmhybris** [comment]
not pretty! :(
