### ISSUE TITLE
Docs & Lib: Update action placement in all examples

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#840]
> We need to make this update in on the Documentation pages as well as test framework. 

## New product standard has guidelines for action or and placement

All products must adopt the standard approach ... actions appear on the right, primary action appears first, addt'l actions appear in decreasing priority order.

For example, an action bar on an editable details page should show button on the right with Save and then Cancel. A modal would show, Confirm and Cancel.

## Detailed description

Any component and page examples should be updated.

https://sap.github.io/fundamental/components/action-bar.html - #879 - Design Issue Added

https://sap.github.io/fundamental/components/modal.html
https://sap.github.io/fundamental/demo-pages/sidebar-app-demo.html
https://sap.github.io/fundamental/demo-pages/modal-overlay-demo-page.html
https://sap.github.io/fundamental/demo-pages/alert-overlay-demo-page.html

Update button docs page to include guidance for action order.

**Comment by xak** [comment]
@jeannewalters Can you link reference details regarding this new guideline? Thanks.

**Comment by jeannewalters** [comment]
@xak I started the list of updates from the specs on Friday and will update wires with the information from the spec today.
