### ISSUE TITLE
Fix UI padding on full width demo page

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#841]
## Full demo page does not include proper UI padding

There should be a margin between the page content and the side of the browser window.

## Detailed description

The margins seem to be fine in all other demo pages.

<img width="244" alt="screen shot 2018-10-29 at 3 21 27 pm" src="https://user-images.githubusercontent.com/424119/47655943-63bd7600-db8e-11e8-92bb-c2a72ec50077.png">

**Comment by ckoutsiaris** [comment]
Should be ok now. Thanks
