### ISSUE TITLE
Bug: vertical alignment in calendar

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#854]
The month, year, and icons appear to be misaligned vertically: http://cl.ly/efa1a2c23cef

**Comment by ianquigley-sap** [comment]
@eboyer this seems to be resolved?  The vertical alignment in the screenshot below looks correct:

![image](https://user-images.githubusercontent.com/15449680/47996742-6ae60600-e0f1-11e8-831d-f688757f868c.png)
