### ISSUE TITLE
Bug: small dropdowns are missing borders

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#855]
In the smaller variations of dropdown, they are missing their top and bottom borders on the addon (could be a greater input group / addon issue): http://cl.ly/1154c801c87d

**Comment by ianquigley-sap** [comment]
@eboyer this one looks to be resolved? 

![image](https://user-images.githubusercontent.com/15449680/47857987-e9396400-dde2-11e8-90ef-23fb1653236e.png)

Closing this issue as a result.  Please re-open if I've mis-interpreted the bug.
