### ISSUE TITLE
Bug: Input-group addon focus state border-radius

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#859]
When the button is focused in an input-group addon, it loses its rounded corners that it once had: http://cl.ly/7814a6f895b8

**Comment by ianquigley-sap** [comment]
@eboyer I can't replicate this particular issue in the screenshot.  However, I did see the following issue, where on focus, with the button on the RHS, the focus doesn't apply on the RHS:

![image](https://user-images.githubusercontent.com/15449680/47863017-4dadf080-ddee-11e8-9193-07f6d8045fa5.png)

I'll fix that issue as part of this bug.
