### ISSUE TITLE
Bug: input-group addon missing borders

### ISSUE THREAD

**Issue by eboyer** [SAP/fundamental#860]
There's a state in input-group (also in dropdown) where the addon is losing its borders: http://cl.ly/67c9369082a3

**Comment by ianquigley-sap** [comment]
@eboyer this seems to be resolved?  See screenshot below:

![image](https://user-images.githubusercontent.com/15449680/47914246-c6688780-de96-11e8-8544-b84d0484801a.png)


Unless there's another scenario that I'm not seeing.  Can you please confirm and close if it makes sense?

**Comment by saadmhybris** [comment]
this is related to the readonly state and no border is the indented style for this state. the bottom blue border was corrected in another issue. no further work is needed on this issue. 

<img width="1377" alt="screen shot 2018-11-08 at 11 29 34 am" src="https://user-images.githubusercontent.com/15215400/48216213-a975fd80-e349-11e8-8d7a-7b2db8538ae0.png">
