### ISSUE TITLE
Design: Update Header Action Bar (Workstream Spec)

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#879]
The header action bar wire and documentation has been created based on the Floorplan workstream specification document.

Wires and Documentation (@saadmhybris you can cut/paste documentation from the prototype below):
https://w2ybdj.axshare.com/#g=1&p=header_action_bar

Attached the wire image below.

**Comment by jeannewalters** [comment]
![image](https://user-images.githubusercontent.com/24274321/47798884-891dc180-dcff-11e8-91bc-79d63388d922.png)

**Comment by saadmhybris** [comment]
header action page will be update under #1037
