### ISSUE TITLE
DESIGN UPDATE: Color Palette Updates  Pt:2

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#882]
DESIGN UPDATE: Color Palette Updates Pt:2

- [ ] Remove "Accent Avatar/Identifier - 4.5:1" section

- [ ] Addition of  5 new "Accessible Colors" section. 

Details can be found in the design sheet here: https://zpl.io/2ZzGpJE

**Comment by xak** [comment]
@LeoT7508 Is this a design or dev issue? What is supposed to be delivered here that is different from #881
