### ISSUE TITLE
Fiori 3.0 Component Status: Footer Toolbar

### ISSUE THREAD

**Issue by jeannewalters** [SAP/fundamental#908]
The footer toolbar is a new component based on the Floorplan Workstream specification.

Here is the documentation and wire for this component.
https://w2ybdj.axshare.com/#g=1&p=footer_toolbar_bar

Here is the wire:
![image](https://user-images.githubusercontent.com/24274321/48004437-86e4aa00-e0e7-11e8-9e91-59a20d2bedcb.png)

**Comment by saadmhybris** [comment]
@LeoT7508 will you be providing designs for this or we should just work off of the wires?

**Comment by LeoT7508** [comment]
We can use wires for now, but the design will have more detail, so this ticket should be open until then.

**Comment by eggward** [comment]
Hi,
I'm looking to contribute and looking out for a component to implement. I'd like to know the current status of this issue. Is this ready for implementation?

Regards,
Edward

**Comment by LeoT7508** [comment]
We do not currently have a design for this, so its not ready for implementation.
