### ISSUE TITLE
Unused sass variables

### ISSUE THREAD

**Issue by ckoutsiaris** [SAP/fundamental#913]
### Description

There is a number of variables that are not been used. Should we remove them (all/some?) or leave them for potential future use? 

./scss folder
<img width="408" alt="screenshot 2018-11-06 at 16 34 03" src="https://user-images.githubusercontent.com/44162302/48078965-57669800-e1e2-11e8-9ab4-8b45c363dad4.png">

./docs/scss folder
<img width="263" alt="screenshot 2018-11-06 at 16 34 22" src="https://user-images.githubusercontent.com/44162302/48078979-5cc3e280-e1e2-11e8-8327-d02a532405fc.png">

@xak @saadmhybris @eboyer @ianquigley-sap what do you think?

**Comment by xak** [comment]
The `fd-colors-*` vars are used to output CSS vars in the `root` file.
https://github.com/SAP/fundamental/blob/develop/scss/core/root.scss#L7

The `fd-font-path` is used for configuration.
https://github.com/SAP/fundamental/blob/develop/scss/fonts/72.scss#L4

The others do look outdated and can be removed.

**Comment by ckoutsiaris** [comment]
Thanks @xak , I will remove them.
