### ISSUE TITLE
Lib: Identifiers/Avatars

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#924]
Key differences in Fiori 3.0:

1. Addition of 5 new sizes: 20px, 32px, 64px, 88px, 112px. 

2. Removal of 36px size. 

GD Sketch file can be found here: https://sap.sharepoint.com/:f:/r/teams/SAPFioriDesignSystem/Shared%20Documents/General/Fiori3%20Stencils?csf=1&e=yk3JMj

**Comment by saadmhybris** [comment]
this is already done.
