### ISSUE TITLE
Fiori 3.0 Component Status: Create additional instances of Buttons

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#925]
Key differences in Fiori 3.0:

1. Addition of button with icons on the right after the label. 

2. Addition of a split button.

v1.3 Design sheet located here:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b314acf0473da4f36a101fa

**Comment by xak** [comment]
#954

**Comment by droshev** [comment]
Is this ready to be implemented?

**Comment by LeoT7508** [comment]
@droshev This is ready for implementation.

**Comment by saad-mo** [comment]
Split button has been added. an icon on the right will take some refactoring and we can revisit if there is a strong need from the teams
