### ISSUE TITLE
Fiori 3.0 Component Status: Modal/Dialog

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#935]
Key differences in Fiori 3.0:

1. There is a scenario where there won't be an "x" to close the dialog. This can in certain instances happen in the primary controls at the bottom of the window. 

2. The Action button should be to the left of the tertiary button. 

3. There is no longer a horizontal run above the main controls. We should check in with GD about this for scrolling purposes. 

GD Sketch file can be found here: https://sap.sharepoint.com/:f:/r/teams/SAPFioriDesignSystem/Shared%20Documents/General/Fiori3%20Stencils?csf=1&e=yk3JMj

**Comment by jeannewalters** [comment]
I will attach the doc soon.

**Comment by saadmhybris** [comment]
@jeannewalters assigning this to you since you are working on this. Please update the ticket once you have the wires ready.

**Comment by saadmhybris** [comment]
component will be updated under #977
