### ISSUE TITLE
Fiori 3.0 Visual Update: Left Navigation visual & spacing updates. 

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#936]
Visual updates as follows:

- Updated margins and  gutters per line item
- Icon color updated.
- Selected state updated. 
- Tree structure spacing updated. 
- Addition of icon only side nav option. 

Design sheer can be found here: https://zpl.io/2yOJ0e9

**Comment by eboyer** [comment]
@LeoT7508 ~ Hey dude, the Zeplin link shows that the design is still WIP, is this accurate?

**Comment by LeoT7508** [comment]
The left nav is still very much WIP, we will update to this and make adjustments as they come.

**Comment by droshev** [comment]
how about the mobile version?

**Comment by LeoT7508** [comment]
@droshev We have very little information about how this works on mobile. I would hold off on that for now. We know it turns into a drop down menu at the top of the screen, but we don't have any other information, we would be guessing at it at this point.

**Comment by droshev** [comment]
We need a complete solution(desktop, tablet and mobile) as teams need it

**Comment by jeannewalters** [comment]
Suggested mobile approach:
![image](https://user-images.githubusercontent.com/24274321/57630528-c34c0380-756b-11e9-9704-f26cdf83345e.png)
