### ISSUE TITLE
Bug: Fixed col table view markup is malformed

### ISSUE THREAD

**Issue by saadmhybris** [SAP/fundamental#943]
**Describe the bug**
The markup for the [fixed col table view](https://sap.github.io/fundamental/components/table.html#table-with-fix-column-header-and-context-menu) on the documentation page is malformed. 

- fix spacing issued on the fixed column when the non-fixed column has wrapping text resulting in varying height. 
- remove incomplete inline styles 

> Is this issue related to a specific component?
tables documentation page 

**To Reproduce**
1. Go to 'https://sap.github.io/fundamental/components/table.html#table-with-fix-column-header-and-context-menu'
2. check inline styles `style="left:200px; width:" `

Related to #914

**Comment by ritarora** [comment]
@saadmhybris Do we want to add ellipses to the table cells for long text .
Something like this 
![screen shot 2018-11-12 at 11 14 47](https://user-images.githubusercontent.com/43745372/48344253-69c25500-e66c-11e8-976b-a0f832a5b7af.png)

**Comment by ckoutsiaris** [comment]
@ritarora Sorry didn't see your question. @saadmhybris what should we do here? At the moment we assume that th and td have the same width.

**Comment by saadmhybris** [comment]
- we are missing documentation on how a width needs to be defined for `.fd-table__fixed-col` and the same width need to be used as the offset (`padding-left`) for `.fd-table--fixed`.

- if we can solve the equal height issues on the fixed column without the use of ellipsis, it would be ideal I am not sure how flex-box works with absolute positioned elements. 

Ideally, we would want to show an interactive example where you can fix/unfix column, drag to adjust their width. but this is all possible in ngx or react versions of this component.
