### ISSUE TITLE
Lib: Implement split button

### ISSUE THREAD

**Issue by xak** [SAP/fundamental#954]
#### Split action 
The button consists of one or two clickable areas. The first area can either contain text or any kind of content. The second area (optional) contains a drop-down arrow. 

![screen shot 2018-12-18 at 3 35 34 pm](https://user-images.githubusercontent.com/424119/50191902-974a9000-02f5-11e9-833c-69884cfadda4.png)

> Note: This should only be available for `--emphasized` buttons.

#### Reference

Example at https://www.w3schools.com/howto/howto_css_button_split.asp

Design at https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b314acf0473da4f36a101fa

**Comment by xak** [comment]
@LeoT7508 Can you prioritize design specs for the split button and show amnestying example with icon on the right?

**Comment by LeoT7508** [comment]
@xak 

Yes, this is already done. Design sheets will be uploaded this week.

**Comment by LeoT7508** [comment]
@xak 

Button design sheet attached.
