### ISSUE TITLE
Fiori 3.0 Component Status: Input field label updates

### ISSUE THREAD

**Issue by LeoT7508** [SAP/fundamental#955]
Key differences in Fiori 3.0:

- [x]  Label now has ":" after the label text. 

- [x]  We will need a variation with the label to the left of the field for scanning purposes. 

- [x]  For required labels and red asterisk "*" must be included after the label text.

Design

Design sheet can be found here:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b195719c295194d78afc36d

**Comment by bsrdjan** [comment]
Following on 2nd point of the original issue, the field label positioning should be configurable: above or left (right for LTR) of the input field. Also the responsive re-positioning of "left" to "above", when viewport width reduced, like TWBS "horizontal forms":
Example: https://getbootstrap.com/docs/4.2/components/forms/#horizontal-form
