### ISSUE TITLE
Bug: angular 4 aot compilation is very slow

### ISSUE THREAD

**Issue by teeSee** [SAP/fundamental#970]
We find node --max_old_space_size=8192 ./node_modules/.bin/ng build -prod -aot -d /SM/rest/dist/ -op target/classes/static/dist --sourcemaps=false

is very slow (more than 20 minutes) after we include fundamental ui to our style.scss

@import "./style/variables";
@import "./style/color";
@import './style/layout';
@import './style/mixins';
@import './style/material2-theme';
@import './style/material2-extra';
@import './style/prime-ng-custom';
@import './style/fundemental-ui';

fundemental-ui.scss

$fd-icons-path: "~fundamental-ui/scss/icons/"; // icon path in node module
$fd-fonts-path: "~fundamental-ui/scss/fonts/"; // fonts path in node module
// @import "~fundamental-ui/scss/all.scss";
@import "~fundamental-ui/scss/theme/fundamental";
// @import "~fundamental-ui/scss/core";
@import "~fundamental-ui/scss/settings";
@import "~fundamental-ui/scss/mixins";
@import "~fundamental-ui/scss/functions";
@import "~fundamental-ui/scss/icons/icon";

Please advise. How can we increase the AOT compilation time

**Comment by saadmhybris** [comment]
@droshev @mikerodonnell89 any ideas on this one?

**Comment by saad-mo** [comment]
@teeSee can you please confirm if this is still a valid issue?

**Comment by teeSee** [comment]
We plan to move away from angular 4. Please close the issue.
