### ISSUE TITLE
Bug: selectbox arrow not visible

### ISSUE THREAD

**Issue by antiheld** [SAP/fundamental#973]
The selectbox arrow is not displayed proper. Instead the user sees only a square. 

<img width="1136" alt="screen shot 2018-11-09 at 16 43 53" src="https://user-images.githubusercontent.com/1991339/48272464-f25bae00-e43e-11e8-9f32-0e2012641f49.png">

This bug might occur because the background-image of the selectbox holds text with the unicode of the icon from the sap-icon-font which is for some reason not displayed. 

<img width="890" alt="screen shot 2018-11-09 at 16 32 26" src="https://user-images.githubusercontent.com/1991339/48272696-8463b680-e43f-11e8-8c5d-3fca7cd403e0.png">

Note: It is not possible to reproduce this bug when the icon-font is locally installed and activated.

Tested on: 
Chrome 72.0.3605.0 (Official Build) canary (64-bit)
Chrome 70.0.3538.77 (Official Build) (64-bit)
Safari  11.1.2 (12605.3.8.1)
Firefox 63.0.1 (64-Bit)

**Comment by ckoutsiaris** [comment]
Should be ok now. Thanks
