### ISSUE TITLE
Lib: Update Modal/Dialog

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#977]
- [ ] Rename modal to dialog 
- [ ] update documentation pages 
- [ ] update demo pages 
- [ ] Design specs and wires  will be available under this ticket - #935 

Design

v1.3 Design sheet located here:
https://app.zeplin.io/project/5a8c458b6e231fc65bddbdfb/dashboard?seid=5b16a5462f6a743c5aa6a0a4

**Comment by saadmhybris** [comment]
UX/design specs under #977

**Comment by LeoT7508** [comment]
@saadmhybris 

Design sheet attached.

**Comment by ritarora** [comment]
@saadmhybris @xak I had created the new Dialog control based on the design link I saw before but i guess that was not the latest and is different from the new deign specs.
Can you have a look a the PR https://github.com/SAP/fundamental/pull/1046 and let me know if we want to keep those dialogs and add new ones to it?

**Comment by LeoT7508** [comment]
@saadmhybris 

Wires: https://w2ybdj.axshare.com/#g=1&p=dialog_-_need_to_finish
