### ISSUE TITLE
Docs: Update dialog(modal) documentation

### ISSUE THREAD

**Issue by saad-mo** [SAP/fundamental#983]
Modal will be renamed to dialog and we need update the following pages on the documentation site: 

- [ ] https://sap.github.io/fundamental/components/modal.html
- [ ] https://sap.github.io/fundamental/demo-pages/modal-overlay-demo-page.html

Related issues: #935, #977

**Comment by ritarora** [comment]
@saadmhybris As I have created the new Dialog component and we will be deprecating Modal, do we still want to update the documentation?
